### ISSUE TITLE
US 34 routing across the Missouri River

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#10]
Our current data has US 34 crossing the Missouri at Plattsmouth, NE.  I drove US 75 today, and US 34 joins US 75 near LaPlatte, at the positions shown in Google Maps.

**Comment by yakra** [comment]
US34 relocated & points relabeled on US75 in my local files.

I'll prioritize Nebraska as I start to dig out from under my update backlog, and make this part of my next pull request.
After that, this issue can be closed.

**Comment by yakra** [comment]
I sent Jeff a PM on AARoads WRT this, offering to upload IA US34 along with the rest of my update.
If I don't hear back in the near term, I'll just send updates for the other Nebraska items Jim mentioned, and leave this one, allowing some more time to coordinate with Jeff.

**Comment by jteresco** [comment]
The Iowa side is in the DB.

**Comment by jteresco** [comment]
And the Nebraska side's in the DB as well.
