### ISSUE TITLE
System distinction in Iceland (S? T?)

### ISSUE THREAD

**Issue by Duke87ofST** [TravelMapping/HighwayData#1017]
Linking to this discussion which started on the forum to ensure maximum exposure: http://tm.teresco.org/forum/index.php?topic=1774.msg4585#msg4585

Basically, Iceland distinguishes between different types of routes on paper ("S" and "T" are predominantly of concern here) but signs them all the same in the field. I've been putting everything in one system since they're all signed the same but apparently I have unwittingly deviated from precedent in at least one other European country by doing so. Need a consensus as to whether I should continue with isls as one system or split it into isls and islt. 

I personally favor keeping it one system but changing the waypoint labels for route intersections from "S123" to "RN123", since "road number 123" is what locals in Iceland would call it when speaking or writing (to tourists, in English, at least).

Note that the system name "Iceland Þjóðvegur" literally translates as "Iceland Highways", so the name is correct for keeping everything together and would need to be changed if split.

**Comment by si404** [comment]
IIRC, I thought the S Roads had yellow cartouches, with lesser roads in white, so I changed it to isls, from islth. TH123 is simply transliterating Þ123 to basic Latin. I'd go with the Icelandic rather than the English.

**Comment by Duke87ofST** [comment]
Yeah, that's not the case. There are a bunch of yellow cartouches in and around Reykjavik but they don't indicate anything about the type of route and are not seen anywhere else in the country.

As for using TH, that works for me. If there are no objections I'll go with that.

**Comment by michihdeu** [comment]
I think this issue can be closed now.

**Comment by Duke87ofST** [comment]
Agreed
