### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#1148]
Reminder to investigate https://travis-ci.org/ as a way to automate correctness checks for highway data pull requests.

**Comment by michihdeu** [comment]
Another option might be this: https://help.github.com/articles/about-status-checks/

**Comment by michihdeu** [comment]
Since we already have a way to check for hwy data correctness and automated checks are mentioned in https://github.com/TravelMapping/DataProcessing/issues/22 , can we close the issue here? @jteresco

**Comment by jteresco** [comment]
While I'm closing Issues.. I don't think we're going to want or need a tool at this level any time soon for our Highway Data.
