### ISSUE TITLE
OH: Ohio 794

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#121]
On AARoads forum from bejacob:

OH 794 no longer exists even though it still appears on Google Maps.

On 10/4/2015, I was south of Springfield, OH and drove what used to be OH 794. From what I can tell, it was decommissioned as a state route and turned over to Clark County in late 2013. All state signage has been removed along the entirety of the route.

**Comment by mapcat** [comment]
This has been deleted.
