### ISSUE TITLE
ID: Idaho 78 point label

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#122]
Reported by email:

I did stumble across an error in the points for ID 78.  The waypoint labeled ID67 should probably be ID167 since that's the route that intersects/ends at ID 78.  It's also present in the old cmap site so it's definitely been there for a while.  I'm not intimately familiar with the history of Idaho state routes; maybe it used to be ID 67 and it got renumbered when 67 was rerouted?  No idea.  I changed my list file to match what's in the system right now.  If it gets changed/corrected in the system, I'll update my list file again.  No big deal.

**Comment by si404** [comment]
This is done in my on-PC files, but I'm working through Poland (just E roads and missed S roads to do) and bringing that up-to-date, and would rather submit that as a block, so you'd have to wait a bit for it to be in part of a pull request.
