### ISSUE TITLE
NV: I-15BLMes is also NV 144

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#123]
Noticed while driving the route in person this morning.

**Comment by the-spui-ninja** [comment]
I think that was decommissioned; as when I was last there, the only 144 references I saw were peeling.   However, that was several years ago, and things might have changed since then.

**Comment by jteresco** [comment]
Here's the one I got a picture of.
![dscf0268](https://cloud.githubusercontent.com/assets/3837120/10282457/5010d3e6-6b38-11e5-8224-bc5d2c476bc4.jpg)

**Comment by the-spui-ninja** [comment]
Yeah, that was going the other way from what I did.

Well, I tried to dig into the NDOT site, but they didn't have an embedded program, just a dowload of GIS data that I couldn't use: https://www.nevadadot.com/About_NDOT/NDOT_Divisions/Engineering/Location/GEOSPATIAL_DATA.aspx
I hope that helps.

**Comment by michihdeu** [comment]
@ovoss did never response to this. I guess he wasn't aware of this. I've crossposted it on the [forum](forum.travelmapping.net/index.php?topic=2771). I think it can be closed here.

**Comment by jteresco** [comment]
@michihdeu I agree with what you are doing.  Let's move all highway data update discussion to the forum and close issues here.
