### ISSUE TITLE
NV: US 93 Alt in Pioche?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#125]
There's signage for a "US 93 Alternate" that runs along what I assume is the old US 93 routing through Pioche.  The route is also well signed (as plain US 93) in places in town.  Is this official?  Official or not, should we add it?  It's no new mileage, as the road seems to be exactly NV 321.

**Comment by jteresco** [comment]
Correction: the sign on the mainline is for Business US 93.

![dscf0355](https://cloud.githubusercontent.com/assets/3837120/10273045/78fc1e4c-6ae7-11e5-90ec-45742ba63297.jpg)

**Comment by NickCPDX** [comment]
It's not listed in the state route guide as an official BR.

**Comment by jteresco** [comment]
I'm not sure of whether signed business routes that are not official end up being included.  I know we include some unofficial suffixed state highways like MA 2A in Shelburne Falls.  I'm OK leaving it out or adding it in, whatever's consistent with our treatment of similar situations for bannered US highways.

**Comment by jteresco** [comment]
I was reminded of this issue by some of what @ovoss  has been looking at with the NM truck routes in #288 and the fact that I just processed my pictures from my drive through Pioche.  New Mexico doesn't have any official information on bannered routes, but @NickCPDX's comment above implies that Nevada does.  If Nevada considered some bannered routes official but does not include this one, then it should be left out.

**Comment by NickCPDX** [comment]
For reference, the NV Guide is here:

http://www.nevadadot.com/About_NDOT/NDOT_Divisions/Planning/Roadway_Systems/State_Maintained_Highways,_Descriptions,_Index___Maps.aspx

**Comment by NickCPDX** [comment]
And, after a bit of research, an interesting discovery: The signed US 95 Truck bypass in Hawthorne is not  listed in the state index either. It's not like they don't list alts/bus/etc - The US 95 Business Rte in Las Vegas is listed. These are just omitted.

**Comment by michihdeu** [comment]
@ovoss did never response to this. I guess he wasn't aware of this. I've crossposted it on the [forum](http://forum.travelmapping.net/index.php?topic=2770). I think it can be closed here.
