### ISSUE TITLE
ND: US 2&85 Williston Bypass

### ISSUE THREAD

**Issue by the-spui-ninja** [TravelMapping/HighwayData#128]
So it looks like the permanent bypass is complete to the point of being driveable.
http://www.nddotwilliston.com/williston-bypass/
http://www.nddotwilliston.com/project-maps/
http://www.nddotwilliston.com/category/williston/
Should the two bypass routes be shifted over to the permanent alignment?

Also, Google Maps and OSM have the new alignment in.

**Comment by yakra** [comment]
Yes, looks like they should be.
I'll get working on this.

**Comment by yakra** [comment]
Pull request #129 submitted
