### ISSUE TITLE
regions, countries, continents

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#1336]
This one requires more thought and care about its consequences, but I'd like to consider the possibility of removing countries and continents from regions.csv and saving that only for subdivisions of countries.  In highway data and list files, that entity which is currently always a region could be a region, country, or continent.

**Comment by ssoworld** [comment]
The use of Country will eat lots of memory - I've seen this for both Firefox and Chrome when loading the USA into it.  Wouldn't be a factor for other countries, good luck trying to load continents - especially NA.
