### ISSUE TITLE
Utah State Route problems

### ISSUE THREAD

**Issue by the-spui-ninja** [TravelMapping/HighwayData#138]
So this will just be a running count of all the non-FP errors that are in the Utah SR set.

UT 190: weird route geometry; already discussed with Si in the UT 289 issue.
UT 284: needs to be realigned like UT 282; those entrance roads are part of the route. (Is this one even signed?)
UT 315: needs to be extended south into Willard Bay State Park; routing on OSM (relevant segment: https://www.openstreetmap.org/way/10077230)

There's probably more of these in there, but this is a good start.

**Comment by ovoss** [comment]
{I added an item to the end of the list -- o.v.]

So this will just be a running count of all the non-FP errors that are in 
the Utah SR set.
UT 190: weird route geometry; already discussed with Si in the UT 289 issue.
UT 284: needs to be realigned like UT 282; those entrance roads are part of 
the route. (Is this one even signed?)
UT 315: needs to be extended south into Willard Bay State Park; routing on 
OSM (relevant segment: https://www.openstreetmap.org/way/10077230)
UT 14 and UT 130: remove references to the deleted UT 289 (fortunately, 
I-15BLCed is unaffected)

--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by jteresco** [comment]
Re: UT 14 and UT 130: remove references to the deleted UT 289 (fortunately, I-15BLCed is unaffected)

I just made this change in my local branch.  Can't believe I forgot that when removing 289.  Anyway, on UT 14, are we good with just "UT130" (I am) or should we include the I-15BL in the label?

**Comment by the-spui-ninja** [comment]
UT 190: weird route geometry; already discussed with Si in the UT 289 issue.
UT 284: needs to be realigned like UT 282; those entrance roads are part of
the route. (Is this one even signed?)
UT 315: needs to be extended south into Willard Bay State Park; routing on
OSM (relevant segment: https://www.openstreetmap.org/way/10077230)
UT 14 and UT 130: remove references to the deleted UT 289 (fortunately,
I-15BLCed is unaffected)
UT 154: needs to be extended east of I-15 to the end of the Bangerter.
While this isn't a known problem, does anyone know if UT 303 is actually signed? There's no StreetView for it, and it doesn't connect to any other route.

Also, here is the UDOT interactive State Route map for reference: https://maps.udot.utah.gov/highway/f?p=184:4

**Comment by jteresco** [comment]
From @NickCPDX in the closed issue:

Responses to errorcheck -

Sharp angles on all - There were reasons for including those – mostly for cutting too much length from a route if excluded.

On the longer stretches without waypoints, I mean, it's Utah. Many of the side roads that might show up on mapping software would be hard to spot if you were driving by. For example, on UT 95, here is something shown on Google Maps as a road on a longer stretch between waypoints.

https://www.google.com/maps/@37.5933434,-110.0431948,3a,75y,77.25h,81.72t/data=!3m6!1e1!3m4!1s58vZJQwPToAlqxm785yDvw!2e0!7i3328!8i1664

Somewhere in some BLM archive they probably have a name for that road, but I haven't been able to find it. I just think there's not much point to adding a waypoint for waypoints' sake. But if someone disagrees, I think we should wager a beer for all waypoints added … I owe a beer for every time one is used, and you owe me a beer a year for every waypoint we add that goes unused.

UT 128 - Should we add one at a campground in the canyon?

UT 282 - This was discussed on the CHM forum. The goofy state route around the U campus.

UT 289 - Pull the route.

**Comment by jteresco** [comment]
My response to the above: not surprising that most angle and distance errorchecks are false positives.  That said, I found several places in NM when I was building that system where it really was points out of order causing the angle.  But yes, in mountainous areas, there are a lot of legitmate sharp angles that should be marked as FPs.

I agree we don't need to go crazy finding the most obscure points to break up segments where there is really no reasonable junction to include.  Just list those as FPs.

**Comment by the-spui-ninja** [comment]
Refreshed list:

UT 190: weird route geometry; already discussed with Si in the UT 289 issue.
UT 284: needs to be realigned like UT 282; those entrance roads are part of
the route. (Is this one even signed?)
UT 315: needs to be extended south into Willard Bay State Park; routing on
OSM (relevant segment: https://www.openstreetmap.org/way/10077230)
UT 154: needs to be extended east of I-15 to the end of the Bangerter.
UT 303: is it signed?
UT 128: is a point necessary at a campground in the canyon?

Also, here is the UDOT interactive State Route map for reference: https://maps.udot.utah.gov/highway/f?p=184:4

**Comment by the-spui-ninja** [comment]
Potential UT 190 fix:

Break it into two routes, ut.ut190 and ut.ut190gua.
Have the main route end in Brighton and the spur route go up the pass.

Would this work?

**Comment by jteresco** [comment]
Just to clarify about datacheck, only 9 errors remain, and it would not be surprising to find that they're mostly FPs.

**Comment by NickCPDX** [comment]
Is the Brighton resort loop signed? If unsigned, I think we're better off letting it be as one of UDOT's parking lot roads and extending 190 up to Guardsman's Pass.

**Comment by the-spui-ninja** [comment]
@NickCPDX, based on what I remember (corroborated by StreetView), neither are signed, but the through route up UT 190 heads to Brighton.

**Comment by NickCPDX** [comment]
So to be clear, you want OR 190 to look like this:

I-215 http://www.openstreetmap.org/?lat=40.637437&lon=-111.808763
UT210 http://www.openstreetmap.org/?lat=40.619295&lon=-111.789494
MaxDr http://www.openstreetmap.org/?lat=40.625549&lon=-111.742115
+X118247 http://www.openstreetmap.org/?lat=40.649583&lon=-111.661520
SprCG http://www.openstreetmap.org/?lat=40.642973&lon=-111.637015
SolRes http://www.openstreetmap.org/?lat=40.621608&lon=-111.592169
+X590758 http://www.openstreetmap.org/?lat=40.611705&lon=-111.581182
BriRes http://www.openstreetmap.org/?lat=40.603983&lon=-111.582513

**Comment by the-spui-ninja** [comment]
That makes sense.

**Comment by NickCPDX** [comment]
Before i send another batch to Jim, do we have any other edits that need to be made to Utah.

**Comment by jteresco** [comment]
I'd say send in what you've got and we can take another quick look.  I'd be very happy to be ready to activate!

**Comment by the-spui-ninja** [comment]
Here's the rest of the problems I found; but these don't necessarily have to be fixed.

**Comment by jteresco** [comment]
Update in progress that truncates UT 190 to Brighton, and extends UT 315 to the state park.

No update at the moment for UT 154.  I assume there was some discussion on this somewhere already, but does it actually extend east of I-15?  Mapping services seem to disagree.  I couldn't find any signs on an admittedly incomplete search in GMSV.

**Comment by NickCPDX** [comment]
It seems to only exist on paper east of I-15. Unsigned.

**Comment by the-spui-ninja** [comment]
Yeah, on the corcohighways.org page there were no signs on that segment.

**Comment by jteresco** [comment]
OK, I say let's leave UT 154 as is.

That leaves 8 visible distance errors that I expect should be marked as FPs.

So then is there any need to modify UT 284 right now or remove UT 303?

Is the UT 128 question about keeping or not keeping the FisTowRd point?  I see no reason to remove it.  Or maybe there's another point proposed to be added?

**Comment by the-spui-ninja** [comment]
I don't remember when the UT 128 thing came into the list. (or what it was, as I was so vague about it)

**Comment by jteresco** [comment]
We are active!  One minor label mistake was reported by a user, I didn't think it worthy of an updates entry.  I'm closing this issue.  Please open new issues here for any errors that arise or report them in AARoads.
