### ISSUE TITLE
NY US9 north end

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#145]
Don't know what NYSDOT (route logs? straight line diagrams? what again?) have to say about this.
Does US9 end at the I-87(43) interchange, or extend north to a dead-end as in the HB?
In any case, I'd move I-87(43) off of the I-87 thru lanes and onto US9 itself.
http://www.openstreetmap.org/?lat=44.999342&lon=-73.453715&zoom=15

**Comment by jteresco** [comment]
Here are the last few entries in the traffic data report entry for US 9.
![endus9](https://cloud.githubusercontent.com/assets/3837120/10560614/5a4e95b4-74de-11e5-8b01-587a608956d5.png)

I agree that the I-87 point needs to be on US9.

**Comment by ovoss** [comment]
I'd leave I-87(43) as is, on the mainline between the two RIROs. That would 
be an appropriate endpoint for US 9, if the endpoint isn't at the parking 
lot behind customs facilities on the northbound lanes just south of the 
border.

As for whether US 9 continues to the parking lot -- when I was last there a 
year or two ago, I don't recall seeing an "End" sign indicating that the 
north end of the route was there, or at the on-ramp to I-87, or anywhere 
else. A quick look at GMSV shows a sign at the north RIRO (next to some 
duty-free facility) indicating that US 9 is south but not north of there, 
but no other signage (either "End" signage, or signs telling the public to 
stay off the road north of the duty-free) indicating US 9 ends there. The 
GMSV camera car turned around before reaching the dead end, and satellite 
view indicates there's nothing north of the duty-free shop except the 
customs facility.

There were no hassles when I went up to, and turned around at, the dead-end 
despite its proximity to customs facilities, so it seems to be open to the 
public all the way to the dead-end.

Oscar

----- Original Message ----- 
From: Eric Bryant
To: TravelMapping/HighwayData
Sent: Saturday, October 17, 2015 2:42 PM
Subject: [HighwayData] NY US9 north end (#145)


Don't know what NYSDOT (route logs? straight line diagrams? what again?) 
have to say about this.
Does US9 end at the I-87(43) interchange, or extend north to a dead-end as 
in the HB?
In any case, I'd move I-87(43) off of the I-87 thru lanes and onto US9 
itself.
http://www.openstreetmap.org/?lat=44.999342&lon=-73.453715&zoom=15
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by ovoss** [comment]
The existing I-87 point is about halfway between the off-ramp from SB I-87 
to SB US 9, and the on-ramp from NB US 9 to NB I-87. So it works reasonably 
well from the perspective of both NB and SB travelers on US 9.

If we're going to move the US 9 endpoint, let's make End an alternate hidden 
label for the new endpoint, to not break my list file or anyone else's.

----- Original Message -----

**Comment by yakra** [comment]
The end is in fact at I-87(43). The road north of there is SR971B. Sources:
http://gis3.dot.ny.gov/html5viewer/?viewer=tdv
https://www.dot.ny.gov/divisions/engineering/technical-services/hds-respository/Traffic%20Data%20Report%202011.pdf (which is what Jim quoted upthread)

**Comment by yakra** [comment]
Traffic Data Viewer & Traffic Data Report agree.

**Comment by jteresco** [comment]
Yes, I think it should be truncated, then.  I say go ahead and create a pull request at your convenience.

**Comment by jteresco** [comment]
Since we're ending at I-87(43) anyway, any thoughts about aligning the point with I-87's 43?

**Comment by yakra** [comment]
The west service road is SR972D. How'bout I include a point for it on US9 proper?

**Comment by jteresco** [comment]
I guess I'm just thinking that US 9 essentially is now ending at that interchange, so why not just approximate the whole thing as a point somewhere in the middle of the ways you'd enter/exit I-87 at US 9's northern end?

**Comment by jteresco** [comment]
I can buy that, too.  I'm always looking at these things from my secondary perspective as someone who wants to turn this data into graph form to apply algorithms to it, and by having separate points, my graph wouldn't show US 9 and I-87 intersecting at that exit.  There are many cases (possibly including this one) where it's totally legitimate to keep them separate but I like to limit them if I can.

**Comment by jteresco** [comment]
I am OK with calling US 9 good and closing this, however.

**Comment by yakra** [comment]
> I can buy that, too. I'm always looking at these things from my secondary perspective as someone who wants to turn this data into graph form to apply algorithms to it, and by having separate points, my graph wouldn't show US 9 and I-87 intersecting at that exit. There are many cases (possibly including this one) where it's totally legitimate to keep them separate but I like to limit them if I can.

Willing to reconsider this. NYSDOT seems to only inventory a given route number in the primary direction. For couplets, the roadway carrying the other direction gets a reference route marker, even it's signed as the touring route in question.
Joe Traveler driving here won't realize he's on a reference route (if you look at the reference route LGSes, you're a roadgeek. :smile: ); if it's well-signed, he'll just see he's on the touring route.
Combine this with how we try to split couplets down the middle most of the time, and the fact that [two](https://www.google.com/maps/@44.9962208,-73.456898,3a,15y,314.08h,90.14t/data=!3m10!1e1!3m8!1sycd6XTa_fdAImNNjwdp5RQ!2e0!6s%2F%2Fgeo3.ggpht.com%2Fcbk%3Fpanoid%3Dycd6XTa_fdAImNNjwdp5RQ%26output%3Dthumbnail%26cb_client%3Dmaps_sv.tactile.gps%26thumb%3D2%26w%3D203%26h%3D100%26yaw%3D6.4155087%26pitch%3D0%26thumbfov%3D100!7i13312!8i6656!9m2!1b1!2i40) [outta](https://www.google.com/maps/@44.9958666,-73.4570809,3a,15y,231.23h,89.63t/data=!3m9!1e1!3m7!1sLRQlbsUvtumvfbUk7zebuw!2e0!7i13312!8i6656!9m2!1b1!2i40) [three](https://www.google.com/maps/@44.9944979,-73.4572082,3a,15.3y,218.05h,86.21t/data=!3m9!1e1!3m7!1sckKnvodZdRX1b6ucFgwVbQ!2e0!7i13312!8i6656!9m2!1b1!2i40) signs have US9 along the western service road, I can justify chaning US9 to end as @jteresco suggested.

**Comment by yakra** [comment]
#2948
