### ISSUE TITLE
SWE: point on E65

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#146]
Looks like a point in use was removed from E65.  Reported by user michih by email:

It's quite strange that I got this error after the last update:
Waypoint label(s) not found in line: SWE E65 14 SalVag
 
"SalVag" waypoint does no longer exist:
- http://tm.teresco.org/devel/hb.php?r=swe.e65
- http://cmap.m-plex.com/hb/hwymap.php?sys=allav&rg=swe.all&gr=p&r=swe.e65&showint=0&dl=0
 
Was there an update of Swedish roads without notification in the update list?

**Comment by si404** [comment]
The point wasn't on the labels-in-use list. Readded as part of pull request https://github.com/TravelMapping/HighwayData/pull/147
