### ISSUE TITLE
MO: MO 92

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#149]
From the_spui_ninja by email:

"I noticed while I was driving MO 92 that the MO 45 point in the HB is off."

**Comment by the-spui-ninja** [comment]
More details: MO 45 & 92 do not actually intersect; there is a short connector road between them. The current point in the HB is southeast of where that road is.

**Comment by mwasleski** [comment]
I agree with this.  There is no direct intersection between MO45 and MO92.  So, on the MO92 file, I'd recommend the current MO45 point be replaced with:

ToMO45 +MO45 http://www.openstreetmap.org/?lat=39.367948&lon=-94.867007

And then, on the MO45 file, the MO92 point should be replaced with:

ToMO92 +MO92 http://www.openstreetmap.org/?lat=39.368279&lon=-94.867330

Just my two cents on this.

-Michael

**Comment by the-spui-ninja** [comment]
Having driven that stretch recently, that makes sense.

**Comment by yakra** [comment]
I'd use those point locations, but I think that the current labels, without the "To" are fine. The routes are close enough, the connector short enough.
Think of it as the at-grade version of a double trumpet.
Compare the US6/CT10 junction, or ME US1 EMainSt.

**Comment by jteresco** [comment]
I'd also like to see the current labels remain, just move the points.  Essentially the same as we do with long ramps on many toll roads, also.

**Comment by the-spui-ninja** [comment]
I guess it's not like NE, where the connector is its own route. I'll throw my hat in the "keep the labels, move the points" group.
