### ISSUE TITLE
Numerous errors keeping site updates from running

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#15]
I was trying my "fork & pull" instructions for people to contribute highway data, and when I pulled down the latest master branch on the HighwayData repository to my local copy to run a site update, I was surprised to get a whole bunch of updates, mostly in Europe regions.  Errors seem to be things like mismatches in names between the .csv and _con.csv files.  For example, in eure.csv, the entry

    eure;NOR;E39;;Kvi;Kvivstunnelen;nor.e39;

should be

    eure;NOR;E39;;Kvi;Kvivstunnelen;nor.e39kvi;

to match the actual .wpt file name and the entry in eure_con.csv.

@si404, could you go through and make the fixes to these?  I'm getting a bunch of similar errors, one in fraa, and a whole bunch in gbnam, before my program dies with an error on a bad line in turo_con.csv (not enough fields).

**Comment by si404** [comment]
These should now be all fixed. Issue of the non-web-based access not working for me. Jim, can you check before we close the issue?

**Comment by jteresco** [comment]
Thanks.  Still getting some errors.

Could not find Route matching root svk.e575gyo in system eure.
No roots in _con.csv line [eure;E575;;Gyor;svk.e575gyo]
Could not parse _con.csv line: fraa;A89;;;fra.a089;A89Per
Could not find Route matching root eng.a4510 in system gbna.
No roots in _con.csv line [gbna;A4510;;;eng.a4510]

/hwy_data/ENG/gbna/eng.a003.wpt file not found.

**Comment by jteresco** [comment]
Can you remind me what trouble you're having with non-web-based access?

**Comment by si404** [comment]
Was the A3 the only one not found? Seems odd if so. Because gbna in England has so many files, the web interface won't show more than 1000 (It says "£orry, we had to truncate this directory to 1,000 files. 14 entries were omitted from the list."), so when I updated files, I moved them into gbna3 or whatever zone they were in, making the numbers in each folder smaller. I've moved them all back into gbna anyway. I had thought it didn't matter where the file was.

The issue with other interfaces comes when trying to create a local copy of the respository. On both my PCs, a .dll file is missing, and despite re-installs of Github for Windows (and it working before), it doesn't let me download.

All the listed errors are fixed.

**Comment by jteresco** [comment]
No more .csv or _con.csv errors on my next run, but now it doesn't find hwy_data/ENG/gbna/eng.kintun.wpt

Unfortunately, my program fails as soon as one missing file is encountered, so there could be others.

I haven't been a Windows user, so I'm not sure what could be going on there.  Can you use the "git shell" I've seen mentioned in a lot of the documentation?

**Comment by si404** [comment]
There shouldn't be others - I fixed that one (hard as I had to go a roundabout way to access that), and it was an issue specific to that file and its sister route (also fixed).

With GitShell, my issue like Oscar's - that command line stuff seems so 1990s that I've not bothered.

**Comment by jteresco** [comment]
Missing hwy_data/ENG/gbna/eng.thadri.wpt

Command line interfaces are old, yes, but very efficient for these kinds of tasks once you get the basics.

**Comment by si404** [comment]
Dealt with - that's gbna clear at least!

**Comment by jteresco** [comment]
OK, good.  Next one: hwy_data/SVN/svna/svn.a006.wpt

**Comment by si404** [comment]
Dealt with. Note to self, don't rely on memory of what route you added (it was H6 in Slovenia).

**Comment by jteresco** [comment]
Excellent, I've got a clean import of the data and an update is installed.  Before I close this issue, if you could poke around the maps of the changes you made to make sure it all looks right, that would be great.

**Comment by si404** [comment]
Looks good.

**Comment by jteresco** [comment]
Thanks, then I'll close the issue.

I think one of my priorities for the project needs to be to get everyone the ability to run the update script on their own branches/forks to be able to catch these before they get back to the master.  It shouldn't be too hard, but as a Mac/Unix user, I can't easily try it out in a Windows environment.
