### ISSUE TITLE
NC and VA I-/US routes changes

### ISSUE THREAD

**Issue by ovoss** [TravelMapping/HighwayData#151]
Based on rickmastfan67's report on the aaroads forum, we should not wait for Dave Filpus to update his states.

I can handle at least the changes to NC I-485 (completion of route around Charlotte) and VA US 460 (new business route in Grundy, and rerouting of mainline route there), as part of getting us up to date nationwide on Interstate and US routes. There are also some AASHTO-approved changes to US 17 and maybe other routes in Wilmington NC, which I don't have a handle on, but could be done later.

I would leave open other maintenance in VA and especially the far larger NC route set, as well as his other states.

**Comment by jteresco** [comment]
Last I heard, Dave was not interested in getting involved in Travel Mapping as a contributor because he was not interested in working with GitHub.  He has submitted a couple .list files.

**Comment by yakra** [comment]
Didn't he do an update the old-fashioned way sometime back by emailing files to another collab? (Oscar? Si? James?) Or did I just fabricate that whole story?

**Comment by ovoss** [comment]
You might have in mind jeffm's updates, one of which I put into GitHub for 
him. I would've thought, if Dave had done something like that, an update for 
the NC I-485 completion would've been included in that package.

That process was rather similar to what Dave and the rest of us did under 
CHM, sending files to Tim for him to insert into the database. The only 
difference is that Dave would also have to rely on us to pull from GitHub 
the latest versions of route files for him to update and send back to us --  
that task under CHM did not require human assistance.

I'm not sure why Dave seems reluctant to pursue that option. I'll hold off 
on doing any updates in NC and VA, in case people would like to try again to 
prevail upon Dave to do them himself (with our help getting them into 
GitHub).

Oscar

----- Original Message -----

**Comment by jteresco** [comment]
Oscar's right, that was Jeff.

**Comment by yakra** [comment]
I don't think we would have to pull anything from GitHub. The files can be viewed and copied from the web interface.
