### ISSUE TITLE
WY: US87BusBuf

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#156]
From sipes23 on the AARoads Forum:

US87Bus (Buffalo, WY) or US87BusBuf is goofed up. I was in Buffalo the other day (again, because once really isn't enough) and I'm pretty sure that Business 87 doesn't follow the north bypass. The signs weren't super clear on the ground (though I wasn't paying super close attention). If I'm in the area again (and I will be), I can field check this if it's still unclear.

**Comment by the-spui-ninja** [comment]
There was some stuff with this route a while ago, and I think that when those changes were implemented, the route got messed up. I think it was supposed to go to I-90, but the north terminal point didn't get changed.

In short, sipes23 is right, but this is just an error.

**Comment by the-spui-ninja** [comment]
Aha, found the old topic: http://clinched.s2.bizhat.com/viewtopic.php?t=2272&highlight=buffalo&mforum=clinched

**Comment by si404** [comment]
Fixed: https://github.com/TravelMapping/HighwayData/commit/5774bebeb9ecf6060412f9ca7a3375e639bcd5d7

I'm going to say no update log required as it was written when I made the original changes - this is an error fix, rather than update.
