### ISSUE TITLE
IN: usain corrections and suggestions

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#161]
From TM user cabiness42 by email.

Some of these are very minor, so I guess it's up to you to decide which ones are worth fixing

IN 1: IN 1 is not concurrent with I-469/I-69.  It is two separate sections.

IN 2: CR500W (between CR350S and CR100S) is a common waypoint for people going to/from Talltree Arboretum.
IN 2: NCougarRd (between US20 and TulipRd) is a common waypoint for people going to/from New Prairie HS

IN 3: You have IN 3 as a continuous route.  Officially there is a southern segment that ends at US224 and a northern segment that resumes at I-69(311) [INDOT does not have state route/interstate concurrencies unless they are very short]

IN 4 (La Porte): You have IN 4 ending at Old US 31.  It has been extended eastward to the new US 31 expressway and has an interchange there.

IN 25: You have the southern end in Logansport a block north of the actual end.  Actual end is at Market St.  Also, you have the waypoint for the southern end listed as US24Bus.  Old US 24 does not have an official Business designation in Logansport (though it does get called that by locals).

IN 37: IN 37 is not concurrent with I-465 or I-69.  It is two separate sections.

IN 39: Morgan St. (between IN67 and GarAve) is a common waypoint for people going to/from downtown Martinsville.

IN 60: There is a new bypass around the east/south sides of Salem.  IN 60 now follows IN 56 east from Salem to the bypass and then they bypass down to where it intersects the original route.

IN 67: IN 67 is not concurrent with I-465.  It is two separate sections.

IN 135: IN 135 rerouted around the entire length of the new Salem bypass and then along IN 56 back to its original alignment in Salem.

IN 203: IN 203 does not end at IN 362.  It continues south to IN 3.

IN 931: There is a northern (unsigned) section of IN 931 in St. Joseph county from Tyler Rd to Kern Rd.

Elkhart CR 17: This is a heavily-traveled 4-lane highway similar to Keystone Ave in Hamilton County.  Common waypoints would be IN119, CR28, Reith Rd, CR45, CR18, US20, IN120, CR10, I-80/90

**Comment by si404** [comment]
There's the question of implied concurrencies here, but I'm going to make the splits as the ones asked for are quite long implied concurrencies. I don't have to take point requests, but I will do.

Keystone Ave in Hamilton County isn't included (and is a higher standard than CR17 is). Unlike the Keystone Parkway, Elkhart CR17 not suitable for usasf. And unsigned IN931 won't be added either, as unsigned!

The rest is construction changes / errors and will obviously be done.

**Comment by si404** [comment]
I don't understand the IN25 one - Logansport is in the middle of it (and would surely be the northern end?). Also 'Bus-24' is a one-way pair, so the point where it is correct.

There's an issue of whether old US24 in Logansport is Bus-24, which I will look at.

**Comment by si404** [comment]
Pull request created https://github.com/TravelMapping/HighwayData/pull/164

**Comment by jteresco** [comment]
From cabiness42 by email:

Thanks, and I just realized that I typed IN 25 when I meant IN 27.  I realize that there is a one-way pair where IN 17 ends, but it is signed all the way to Market Street in both directions.
