### ISSUE TITLE
NS/ON: superfluous CANSPH directories

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#169]
Neither ON nor NS have any routes in the in-dev CANSPH system.
Both hwy_data/ON/cansph/ & hwy_data/NS/cansph/ exist -- containing the data from all provinces/territories./ These can both be safely deleted.

(There's evidence scattered around the repository of things having gone a little goofy during the initial big import of all the old CHM data; this looks like more of that.)

Requesting someone with more command-line capabilities than me do so for housekeeping purposes.

**Comment by jteresco** [comment]
I'll take care of these at the command line.
