### ISSUE TITLE
Need csv files for draft usava

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#171]
I just added the usava system draft that Dave F. had developed for CHM.  He sent them to me as a .zip.  If someone has a chance, please create a .csv and a _con.csv and then I can try loading them in as an in-dev system.  Thanks.

**Comment by yakra** [comment]
Did the .zip include files in any regions other than VA itself?

**Comment by jteresco** [comment]
No, but I only asked about VA based on a request from a user who helped review his VA work for CHM a few years back.

**Comment by yakra** [comment]
To clarify: are there any usava routes in other states; any wv.va999 or nc.va666?

**Comment by yakra** [comment]
To clarify: are there any usava routes in other states; any wv.va999 or nc.va666?

-----

I had a look at the file list, and the va.va999wyefoo files caught my eye, what with the nonstandard banner. Three of the four are covered by GMSV, and they're all signed with the letter 'Y' below the number in the shield (similar to a NH shield's layout). I suggest changing these to VA205Y etc., with no banner.

With no duplicates in the VA###Y routes, the abbrev & city can be left off. (I'd have done this if I'd drafted the set, probably.) They can just as easily be left in too; these are operationally spur routes. I'll remain officially agnostic for now.

**Comment by jteresco** [comment]
User mapmikey put together csv files for usava.  I'm temporarily removing each of these from the .csvs since the routes exist partially or entirely in usansf:

va.va027
va.va037
va.va076
va.va110
va.va146
va.va150
va.va164
va.va195
va.va199
va.va267
va.va288
va.va895

I'm going to try an update now that I hope will bring in the remaining usava routes as an in-dev system.

**Comment by yakra** [comment]
For the routes that exist only partially in USANSF, shall we extend them to their full lengths as we did with Texas?
I'll stop short of volunteering to do so ATM; I don't want to spread myself too thin. That, and there may be another more appropriate person to handle this.
