### ISSUE TITLE
MO: New I-44 exit at Prigmor Avenue / CR 190

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#178]
http://www.joplinglobe.com/news/local_news/new-i--interchange-ready-for-traffic-to-roll/article_a99388fb-0488-5c4a-82e9-f0e64593260b.html

This will be Exit 12 per David Backlin.

**Comment by jteresco** [comment]
Jeff M. submitted files, will be committing tonight.  He has it as Exit 13.  Affects I-44, I-49, US 71.

**Comment by jteresco** [comment]
If I'm remembering right, we don't do updates entries for new exits unless they affect existing .lists somehow.  This one doesn't.  So no entry.
