### ISSUE TITLE
US 310

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#18]
Reported by SD Mapman in the AARoads forum:

So is US 310 supposed to go to Greybull? Or is it just an error?

Reply from @ovoss: If it's an error (which I think it is, from my own travels there earlier this summer), it's one carried over from the CHM database. Looks like something else to add to our updates to-do list.

**Comment by si404** [comment]
Wyoming US310 truncated along overlap with US14/16/20 in branch.

Issue dealt with.
