### ISSUE TITLE
IN: issues reported by email

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#181]
From TM user vespertine by email:

* There is no direct access to IN160 to the Salem bypass route (IN60/135), so the label is not needed. In addition, IN160, as far as I can tell, still ends at Jackson St/Old IN60; there is no signage from IN60/135 @ Jackson St showing any sign of IN160.
* IN114 starts at US41, not the IL border. That mistake crops up on a lot of maps, but GMSV and the 2015 Indiana map confirm this.
* IN342 was unsigned last I checked (a couple years ago), and according to GMSV, may actually be permanently blocked now.
* IN38's start label should technically be Sagamore Pkwy, not US52, since US52 now heads just to the south of the endpoint.
* IN662's start label should be I-69 now instead of I-164, now that the change has been made.
* The northern IN337 route from IN56 at Livonia to IN37 at Orleans is missing. This may still be on its way as the other piece of IN337 is in and has a city associated with it, like a multi-piece route would have.

**Comment by si404** [comment]
(from https://github.com/TravelMapping/HighwayData/issues/161, thanks to cabiness42)

IN 27: You have the southern end in Logansport a block north of the actual end. Actual end is at Market St. Also, you have the waypoint for the southern end listed as US24Bus. Old US 24 does not have an official Business designation in Logansport (though it does get called that by locals).

**Comment by si404** [comment]
Dealt with in https://github.com/TravelMapping/HighwayData/pull/187. US24Bus is signed east of Logansport on Sept 2015 GMSV and the central area is a mess. Removing the one-way pair assumptions and have IN25 along Market Street as that's the nonsense signage declares to be the case.
