### ISSUE TITLE
WY: issues reported by email

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#182]
From TM user vespertine by email:

* I was in Wyoming earlier this year, and it looks like WY152 as recently decommissioned. WY154 has now been extended at its south end, east thru Yoder to US85 (& WY161). GMSV shows new signs on US85, and a green blade sign west of Yoder with "OLD HWY 152" on it.
* WY159's end is actually at CR48, not CR47. GMSV shows END STATE MAINTENENCE signs at CR48 (MP 12.81), and no further mileposts past there. Maybe it was truncated, because the pavement doesn't change until CR47.

**Comment by the-spui-ninja** [comment]
WyDOT's 2013 reference book has both those in it, and has WY 159's endpoint at MP 12.782 (not sure where exactly that is).

Also, to go somewhere completely different, WY 330 is too long; it should end at the hospital (also field-verified earlier this year)

**Comment by si404** [comment]
https://github.com/TravelMapping/HighwayData/pull/187 deals with this. 12.782 and 12.81 is 0.028 of a mile (just shy of 50yrds). End State Maintainance sign is a small amount before the CR24 junction, say 20yrds, and CR24 junction is about 20yrds across. I'm going to call it as being literally at the sign, but given it's proximity to the junction, will use the junction instead.
