### ISSUE TITLE
SD 50 and I-90 Business point issue in Chamberlain

### ISSUE THREAD

**Issue by the-spui-ninja** [TravelMapping/HighwayData#186]
I know this is kinda picky, but the SD 50/I-90 BL intersection point needs to be moved from Main Street to Courtland Street (a block west). Also (and this is even more picky), since 50 is signed E/W, should the SD50_N point be SD50_W? 

Just throwing this out there.

**Comment by yakra** [comment]
Picky is often appropriate here. :D

**Comment by the-spui-ninja** [comment]
Also, to go somewhere completely different, when SD 473 got added the concurrency between US 14A and US 85 got messed up in that area.

**Comment by jteresco** [comment]
I believe the SD 50/I-90 BL issue here was addressed by tonight's commit and site update with changes from Jeff M.

**Comment by the-spui-ninja** [comment]
Closing this and transferring the US 14A problem to the new forum: http://tm.teresco.org/forum/index.php?topic=60.0
