### ISSUE TITLE
Merged branches

### ISSUE THREAD

**Issue by rickmastfan67** [TravelMapping/HighwayData#220]
Just a heads up people, once your branches are merged here on 'master', please delete them.  The 'branch' list is getting really messy (currently over 30 branches).  If you need to do a lot of work, I'd recommend doing it on a fork instead of on master itself.

https://github.com/TravelMapping/HighwayData/branches/active

**Comment by jteresco** [comment]
I should also be able to clean all of these up.  Other than cluttering things up, they probably aren't doing any harm, but as they're probably also not doing any good, cleaning up is a good goal.

**Comment by ovoss** [comment]
I just went into the GitHub web interface about an hour ago, and deleted a 
dozen or so of my most recent branches. However, I'm about positive I 
created many more than that, but I can't find the older ones. Was there an 
earlier round of decluttering, that took care of those for me?

--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by si404** [comment]
I got rid of my old ones a while back, but left those of others.

**Comment by jteresco** [comment]
I cleaned up some of the older ones this afternoon.

**Comment by rickmastfan67** [comment]
It seems we've got a good handle on this now.  So, I'm closing it.
