### ISSUE TITLE
Highway Data Description in README.md

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#229]
This is a note to myself (or anyone else who'd like to take a shot at it) to write up a description of our data formats and organization in this repository's top-level README.md file.

**Comment by michihdeu** [comment]
I think it's done, isn't it?
Only `nmpfps.log` and `railsystems.csv` are not yet described. Proposal:
- `nmpfps.log` contains a temporary list of false positives for near miss points.
- `railsystems.csv` contains a list of the railway systems included in the project.

**Comment by jteresco** [comment]
I'd argue that nmpfps.log shouldn't be mentioned as part of the data, since it's a log generated by the site update.  For railsystems.csv I think we ignore it for now in the description since that's just a temporary file to try a few things out while we decide how to organize the data, DB, site update code, and Web site for non-highway systems.

**Comment by michihdeu** [comment]
I agree. You've not mentioned anything missing. I think we can close the issue...

**Comment by jteresco** [comment]
Agreed.  Closing.
