### ISSUE TITLE
Ohio changes

### ISSUE THREAD

**Issue by si404** [TravelMapping/HighwayData#240]
Sent to me via PM on AA Roads from mapcat

>Greetings Si.

>Since dfilpus retired, no one has been able to make changes to the Ohio state route set, so I hope you might be able to take the time to add two routes and adjust or delete some others.

>OH 26: rerouted (see [Marietta SR 26 Public Meeting](http://www.dot.state.oh.us/districts/D10/newsreleases/Pages/SR-26-Public-Meeting.aspx))
>OH 183 Truck (Alliance): deleted (see [Traffic headaches in Alliance have long-term benefit](http://www.timesreporter.com/article/20130810/News/308109911))
>OH 238: deleted (I can't find anything official any longer, but its former routing has been assumed by OH 38, whose routing south of Bloomingburg has been transferred to the county)
>OH 607: new (see [It’s official, Morgan County State Route 607](http://www.dot.state.oh.us/districts/D10/newsreleases/Pages/It%E2%80%99s-official,-Morgan-County-State-Route-607.aspx))
>OH 684: resurrected (see [Local residents and stakeholders help shape highway changes to Meigs County](http://www.dot.state.oh.us/districts/D10/newsreleases/Pages/Meigs-County-highway-changes-2013.aspx))
>OH 762: extended (see [Extension of Pickaway SR-762](http://www.dot.state.oh.us/Divisions/Planning/SPR/Pic-East-West/Documents/Planning%20Documentation/Duvall%20Journal%20Entry.pdf))
>OH 794: deleted (see [State Route 794 is now County Road 794 - West Blee Road](http://oh-clarkcounty.civicplus.com/CivicAlerts.aspx?AID=71&ARC=91))

>Thank you,
>mapcat/Dave

**Comment by si404** [comment]
> OH684 now continues along OH692's former alignment all the way north to OH681.
I just saw the old file still there and added a line in the .csvs. I couldn't open the ODOT links

**Comment by jteresco** [comment]
Everything taken care of in this one?  OK to close?

**Comment by si404** [comment]
Jim, no pull request for the last item, that is in a separate post after the merge (and I gather there's some polishing to be done on the earlier stuff) - does it look like everything is taken care of?

If it was done, it would have been closed by me before you posted your query.

**Comment by si404** [comment]
This is now done with 
https://github.com/TravelMapping/HighwayData/issues/245
