### ISSUE TITLE
Mexico: Campeche

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#2401]
Similar to #2199:

**Cause:**
* regions.csv lists Campeche as `MEX-CAMP`.
* in hwy_data, there's a`MEX-CAM` directory, containing `mexd/mexcam.mex180d.wpt` (the only route in this region).

**Effects:**
* No graph is produced for MEX-CAM, as no such region is included in regions.csv.
* No graph is produced for MEX-CAMP, as no such directory containing any hwy data exists.
* Campeche is not included in MEX-country.tmg.
* The only traveler .listing anything here is @ua747sp. The line is correctly formatted in ua747sp.list, considering the .list name shown in the HB now. [Travels get highlighted](http://travelmapping.net/hb/index.php?units=miles&u=ua747sp&r=mexcam.mex180d); [mapview](http://travelmapping.net/user/mapview.php?units=miles&u=ua747sp&rg=MEX-CAM) works. [ua747sp.log](http://travelmapping.net/logs/users/ua747sp.log) and [system.php](http://travelmapping.net/user/system.php?units=miles&u=ua747sp&sys=mexd) list some stats for MEX-CAM. [mexd-all.csv](http://travelmapping.net/stats/mexd-all.csv), [allbyregionactiveonly.csv](http://travelmapping.net/stats/allbyregionactiveonly.csv), and [allbyregionactivepreview.csv](http://travelmapping.net/stats/allbyregionactivepreview.csv) too. So far so good...
* **region.php:**
  - http://travelmapping.net/user/region.php?units=miles&u=ua747sp&rg=mex-camp has the page title "Campeche - ua747sp", but no stats.
  - http://travelmapping.net/user/region.php?units=miles&u=ua747sp&rg=mex-cam has stats, but is missing the region name.

**What to do?**
Which one is "right"? There's already a number of 4-letter state codes in use for Mexican regions, which match the "Conventional abbreviation"s listed at https://en.wikipedia.org/wiki/Template:Mexico_State-Abbreviation_Codes . (The one exception, "Tamps" -> "Tam" seems to follow in the "Truncate 5+ letters to 3 letters" CHM/TM tradition.)
Judging by this, MEX-CAMP may be the way to go.
I *could* just change the regions.csv entry to MEX-CAM, and maintain compatibility with ua747sp.list. BUT! If it's just one line in one list, and the person is active here on Github... :) *Worth a shot?*

@ua747sp, would you be okay with changing `MEX-CAM MEX180D MEX180_W MEX180_E` to `MEX-CAMP MEX180D MEX180_W MEX180_E`?

**Comment by si404** [comment]
Another difference between Tim's codes and the conventional abbreviations is 'EMEX' rather than just MEX. Since the move to TravelMapping we've tried to use ISO as far as possible and that is three-letter-codes.

Using the archive.org facility, Tim used MEX-CAM - I'm guessing the error crept in when regions.csv was made.

**Comment by yakra** [comment]
Good enough. MEX-CAM it is, and i don't need to bother ua747sp about it any more.

**Comment by yakra** [comment]
Or, no, wait... that's what I get for posting at 3am...
Of course it was MEX-CAM, as evidenced by the filename `mexcam.mex180d.wpt`.
The error did creep in when regions.csv was made, yes. But would MEX-CAMP be the better way to name the region, to be more consistent with the rest of MEX?

Of course, 3-letter ISO codes would be the better way to do this, and it's how I would design it if I were making Mexico from scratch now. But making that change would be a non-starter, as that would mess up a lot more existing .list files than just one.

**Comment by yakra** [comment]
Rather than put the onus on us747sp to respond here or change us747sp.list, I've opened #2418
