### ISSUE TITLE
KS US66HisGal

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#243]
from bassoon1986 on AARoads:
*I didn't know which page to post in, but I found a mistake while I was creating my own lists to submit. In the Kansas files under the Historic US 66 Galena route, waypoint 9 is labeled as KY26/66 instead of KS.*

-----

Si, should I assume maintenance of USAUSH routes in my regions (KS, TX, wherever else)?

**Comment by si404** [comment]
That would be good if you want to do it.

With this case, I've done it.
