### ISSUE TITLE
 AR I-130 Fut (Texarkana, AR)

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#247]
Now that AR I-130FutTex, in its entirety, has become part of I-49 proper, it looks pretty unlikely it'll ever actually be I-130 at any point in the future.
I vote we nix it. Who's with me?

**Comment by ovoss** [comment]
I agree. FutI-130 probably has been a derelict for many years, and it's high 
time to sink it.

----- Original Message ----- 
From: Eric Bryant
To: TravelMapping/HighwayData
Sent: Monday, December 07, 2015 3:14 PM
Subject: [HighwayData] AR I-130 Fut (Texarkana, AR) (#247)

Now that AR I-130FutTex, in its entirety, has become I-49 proper, it looks 
pretty unlikely it'll ever actually be I-130 at any point in the future.
I vote we nix it. Who's with me?

--
Oscar Voss - oscar.voss@comcast.net - Arlington VA

my Hot Springs and Highways pages (NEW ADDRESS):
http://www.alaskaroads.com/home.html

**Comment by yakra** [comment]
(TM pointsinuse are a subset of) CHM labelsinuse:
*29(549) 35(549) 37(549) AR/TX ARKBLVD I-30 US71*
AltLabels will have to be added to I-49Tex to enable its use as an AltRouteName.
