### ISSUE TITLE
IA I-480 Exit 0

### ISSUE THREAD

**Issue by the-spui-ninja** [TravelMapping/HighwayData#260]
I just drove this today, and the "41st St" waypoint is signed as Exit 0 in the field. Should this be edited (or would it break the HB or something?)?

**Comment by yakra** [comment]
This would break people's list files - (or, change people's 100% clinches to <100%.)
In the *very* early days of "Clinched Interstate Mapping", interstate endpoints without exit numbers of their own (such as those at state lines) were labeled "0" and "999". When these were replaced by descriptive labels such as NE/IA, I-29 etc. later on, the 0 and 999 were retained as hidden, deprecated labels for backwards compatibility, to avoid breaking .lists.

Back in those early days, some actual legitimate Exit 0s were fudged to Exit 0A in the HB (For example, [TX I-10](http://tm.teresco.org/devel/hb.php?r=tx.i010)). It's (very) slightly surprising to find that didn't happen here.

**Comment by the-spui-ninja** [comment]
Well that makes sense.

Unless anyone thinks this one should be a "0A" case, I'll close it.
