### ISSUE TITLE
Updating I-15BLs in Lake Elsinore CA

### ISSUE THREAD

**Issue by ovoss** [TravelMapping/HighwayData#27]

**Comment by ovoss** [comment]
As discussed in the CHM forum, the north end of the I-15 Lake Elsinore business loop needs to be truncated from I-15 to its western junction with CA 74. Also need to create a branch I-15 BL along Main Street in downtown Lake Elsinore, to include the well-signed third leg of the "business loop",

**Comment by jteresco** [comment]
This update is in the DB.
