### ISSUE TITLE
Highway data sources

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#270]
It's important that we create and maintain a list of sources like the one from CHM:

http://cmap.m-plex.com/docs/sources.php

I think it's appropriate to use CHM's list as a starting point.  Does anyone have the source (I assume a csv file) that was used to generate that list?

**Comment by yakra** [comment]
I remember there being XLSes.
CSVs? I don't remember those, but it seems it would be a No. (Semicolons in the HTML field could louse up the CSV columns.) I think Tim had us email the XLSes as needed, and he compiled our new entries into whatever source he used on the site behind the scenes.
I can email you sourceentries_eric.xls as an example if you want.

**Comment by ovoss** [comment]
I doubt any of us has the full .csv file or other source, which Tim created 
using among other things .xls/.csv files sent in by individual collaborators 
for their jurisdictions. Some of us might have our old submissions somewhere 
on our computers, though some of them and the corresponding Sources and 
Links items (like my own submission for Alaska) will be full of dead links 
and will need to be redone from scratch. Also, a "save as" copy of the HTML 
code for CHM's Sources and Links page would let us extract links and text 
from there, though with a fair amount of manual labor.

For Alaska and some other jurisdictions with new route systems in 
development (like California), current links to some state data have been 
posted in the AARoads forum. But some offline sources will need to be added 
too, such as the old Alaska route logs which no longer exist online, or 
California's old paper-only detailed route logs. Also, coordinates grabbed 
by my handheld GPS receiver (lots of them in the Arctic, but also used here 
and there south of the 60th parallel), and paper publications such as the 
Milepost guide to Arctic highways.

----- Original Message ----- 
From: Jim Teresco
To: TravelMapping/HighwayData
Sent: Sunday, December 20, 2015 9:41 AM
Subject: [HighwayData] Highway data sources (#270)


It's important that we create and maintain a list of sources like the one 
from CHM:
http://cmap.m-plex.com/docs/sources.php
I think it's appropriate to use CHM's list as a starting point. Does anyone 
have the source (I assume a csv file) that was used to generate that list?
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - ovoss@pobox.com (old address still works) - Arlington VA

my Hot Springs and Highways pages (new address):
http://www.alaskaroads.com/home.html

**Comment by jteresco** [comment]
Eric jogged my memory about the xls files.  I think Tim kept things in xls then exported as csv with semicolon separators for most things (like route lists for systems).  I assume he did the same for the sources, but didn't keep that information in the data directory.  I found the ones I had sent to Tim in 2013 for NY, MA, and NM.  It makes sense to me to start from scratch in an appropriate .csv file (no sense including the xls step in my opinion) and we can each add entries as we go.

I'm thinking to include the three fields Tim had in the xls (URL, link text, additional text after link) plus fields for which region(s) the source was used, and a date of access.  Non-web resources should also be listed, but they'd leave the URL and link text blank.

For now, if a few of us could gather up some of this information, I should be able to get us started on a csv file that I can read into the DB and display on the site.

**Comment by jteresco** [comment]
Re: @yakra's point about semicolons in the fields, we can use whatever delimiter we want as long as we come up with something that won't be in the actual text or URLs.  I'd probably start with semicolons as delimiters and figure something else out if/when that becomes a problem.

**Comment by ovoss** [comment]
If we're going to include a "region(s) used" field, should we submit a 
single file for all our jurisdictions?

Instead of that, we could submit files for each jurisdiction, displayed 
separately, with another file for a "General References" section (broadening 
CHM's "General Map References" section). "General References" would be a 
good place for my entry for something like "Coordinates from handheld GPS 
receiver, gathered on various dates by Oscar Voss". Such coordinates were 
most heavily used for my Arctic jurisdictions where the online open-source 
mapping can really suck, but also a little in HI, BC, SK, ON, and WV, and 
I'll probably use a few in CA and maybe other places.

Then there are the shapefiles Eric is so good with. He helped me out with 
those in YT and NT where I didn't have enough GPS coordinates, and he's used 
them in some of his own jurisdictions too. Eric, could you please writeup a 
short description (either geneal or jurisdiction-specific) for the shapefile 
coordinates you've used/provided?

The only .xls "sources" file I could find is for Alaska. Fortunately, it is 
more up-to-date than what CHM has (it was submitted but never used), and I'm 
working on additional updates. CHM looks more or less up to date for YT, NT, 
BC, SK, HI, and NM, which I can lift (with checks for dead links) and splice 
into an Excel spreadsheet. I'll have to recheck QC. Nothing at all for CA, 
so I'll need to create one from scratch.

Oscar

----- Original Message -----

**Comment by jteresco** [comment]
I'm thinking we'll have a single file like we have for the datacheck FPs and updates entries for this.  I guess Tim had to manage things with separate files being submitted since he kept the master version of the file hidden.

**Comment by yakra** [comment]
@ovoss wrote:
> Eric, could you please writeup a short description (either geneal or jurisdiction-specific) for the shapefile coordinates you've used/provided?

On CHM, we've got:

**Canada (CAN)**
* [List of Available Datasets.] (http://www.geobase.ca/geobase/en/search.do?produit=nrn&language=en) GIS shapefiles from GeoBase covering the Canadian provinces and territories.

...and similar for other jurisdictions where I've used shapefiles.
That's adequate, right?

**Comment by ovoss** [comment]
Seems pretty close. A quick peek indicates that the GeoBase information is 
copyrighted, but may be freely used under the Open Government Licence with 
the appropriate disclosure, 
http://open.canada.ca/en/open-government-licence-canada  I think the magic 
words, which are probably all we need to add (to cover your use of 
shapefiles from multiple provinces and territories), are "Contains 
information licensed under the Open Government Licence – Canada" (you could 
hyperlink that to the above Open Government Licence URL). When I'm more 
awake, I'll look again, but this should be enough, if perhaps too much.

This could open a can of worms, if we feel we need for consistency's sake to 
also cite terms of use for Google APIs and other mapping tools we use. This, 
too, is a "when I'm more awake" subject.

----- Original Message -----

**Comment by the-spui-ninja** [comment]
The SD source from the CHM sources link goes to a "page not found" error; here's the pavement logs (which is what I used to report errors) as a possible replacement:http://www.sddot.com/transportation/highways/planning/pavement/Default.aspx

**Comment by jteresco** [comment]
I'm considering making this a static, simple HTML page rather than having the sources in a csv file or files, imported to the DB, then read from the DB to display on the web.  Any thoughts?

**Comment by yakra** [comment]
I have no problem with that, and would feel comfortable editing it when I have new sources to add.
For those who don't, leaving it to another collab via posting the info in a pull request or issue is a possibility.

**Comment by michihdeu** [comment]
I think it's still important to have a list of sources, especially after adding so many new systems. Has anyone started a list meanwhile? Some CHM sources are off now...

**Comment by ovoss** [comment]
There are source lists for the two systems I have under development, usaak 
and usaca, in rhe forum topics (one on the AARoads forum, the other on 
Travel Mapping's new forum) for those systems. I suggest that similar source 
lists be posted for other new systems in development, or recently completed, 
as a start on compiling a updated consolidated list.

Oscar

----- Original Message -----

**Comment by jteresco** [comment]
See http://tm.teresco.org/forum/index.php?topic=238.0 in the TM forum collaborators section.

**Comment by michihdeu** [comment]
I think this issue can be closed because we have a [source page on the site](http://tm.teresco.org/credits.php) now and there's a thread on the forum.

**Comment by jteresco** [comment]
Yes, I think we're reasonably up to date on sources, and the forum is a better place to track that.  Closing.
