### ISSUE TITLE
Region to country/continent mappings

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#272]
I'm planning to add SQL tables to aid in mapping regions to countries and regions and countries to continents.  This issue serves as a reminder for me to do this, and as a request for any suggestions.  I see it working like this:

region table:

short code (e.g., AL, BC, ENG, FRA) - primary key
full name (e.g., Alabama, British Columbia, England, France)
country (USA, CAN, GBR) -- when region is a country, this is the same as the short code

country table:

short code (e.g., USA, CAN, GBR, FRA) - primary key
full name (e.g., United States of America, Canada, Great Britain, France)
continent (NA, EUR)

continent:

short code (NA, EUR, others later?) - primary key
full name (North America, Europe)

Am I correct that only Russian systems might span both Europe and Asia?  Should we just consider those as a single continent for our purposes?

**Comment by si404** [comment]
Turkey, Kazakhstan, Azerbaijan and Georgia also trans-continental to increasingly small amounts. ARM, AZE, GEO, KAZ, KGZ, RUS, TJK, TKM, TUR and UZB have both E roads (a European system) and Asian Highways. If we join the Americas together, Eurasia would be tolerable.

France is transcontinental already, with Martinique's A1 in NA. There's also SA (Guyana) and AFR (Reunion, Mayotte) routes there when I move the DOM-TOM's N roads in. Hawaii, American Samoa, Guam, etc are Oceania. Both these (and any Dutch/British/Danish/Norwegian self-governing possessions - eg Aruba, Cayman Islands, Greenland, Svalbard) would be different regions.

Would GBN (Great Britain, as opposed to GBR 'United Kingdom') have a place? It has systems (gbna, gbnam, gbnm) after all, but it's neither a country-level entity, nor a single region (Tim screwed us right up splitting the UK up into its constituent parts).

**Comment by jteresco** [comment]
Maybe the continent level is more trouble than it's worth...

**Comment by si404** [comment]
Maybe, or you attach it to the region, make Turkey, etc Asian and Russia (and Spain parts in Africa) European. It's a fudge, but would work well.

I've made files that cover the whole world. I've used the ISO3166-alpha3 codes as a base. I've split Australia, but left Brazil/India/China alone.
https://github.com/TravelMapping/HighwayData/pull/273

**Comment by jteresco** [comment]
#273 is pulled in.  I will get these into the DB soon, hopefully today.

**Comment by jteresco** [comment]
Some typo fixes just committed.  Working on adding to DB now.

**Comment by jteresco** [comment]
New DB tables are in, created as follows:

    CREATE TABLE continents (code VARCHAR(3), name VARCHAR(15), PRIMARY KEY(code));
    CREATE TABLE countries (code VARCHAR(3), name VARCHAR(32), PRIMARY KEY(code));
    CREATE TABLE regions (code VARCHAR(8), name VARCHAR(32), country VARCHAR(3), continent VARCHAR(3), PRIMARY KEY(code), FOREIGN KEY (country) REFERENCES countries(code), FOREIGN KEY (continent) REFERENCES continents(code));

Not used for anything, yet, but available to support web front-end enhancements.
