### ISSUE TITLE
IN: issues reported by email

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#277]
From user cabiness42 by email:

IN38 has a waypoint mislabeled as IL37 should be IN37
IN267 extends south from I-70 to IN42 but that section is not present in the browser.

**Comment by ajfarina** [comment]
IN38 now has end signs at its junctions with IN39. According to the signage on the roads, IN38 is officially separated into two segments: Lafayette to IN39/US421 and Antioch/IN39 eastward toward Ohio. Even the control city mileage signs have changed accordingly.

**Comment by si404** [comment]
These are dealt with in https://github.com/si404/HighwayData/commit/7ce9c7ca54b2c344df2a89a797c6b56c9e49397f which is merged
