### ISSUE TITLE
WI route changes?

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#280]
Reported by @ssoworld by email:

I noticed while driving US-18 around Mount Horeb that the business route designations (18 and 151) were removed from the BGS’s at both ends.  I did not verify the route itself yet.  The change is a mixture between green-out with “To WIS 92” over the top and newly replaced signs.  The routes followed CTH ID and WIS 78 and WIS 92 ended in town.
 
If I can visually confirm this I will let you know.  I cannot confirm any media reports on this though.

**Comment by ssoworld** [comment]
E-mail also sent to Jeff M regarding this (Jim was copied - thanks for posting)

**Comment by ssoworld** [comment]
an additional deletion - see http://agendas.menomonee-falls.org:8085/docs/2015/VBREG/20151019_1029/2693_Main%20St%20Jursidtional%20Transfer%20Presentation%202015-10-19.pdf regarding WI 74 (completely removed)
