### ISSUE TITLE
Adding new NM truck routes to HB

### ISSUE THREAD

**Issue by ovoss** [TravelMapping/HighwayData#288]
I have a long post in the AARoads forum, http://www.aaroads.com/forum/index.php?topic=15733.msg2115779#msg2115779, on whether to add to the HB two truck routes, Truck US 380 in Roswell and Truck US 82 in Artesia. Any comments, before I implement (or not) either or both those additions?

I think both are maybes, for different reasons.

**Comment by jteresco** [comment]
I'll go on record as having no strong opinion, but that I'd lean against US 380 Roswell more than I'd lean against US 82 in Artesia, but I do lean against including either.
