### ISSUE TITLE
Trying out issues

### ISSUE THREAD

**Issue by jimttesting** [TravelMapping/HighwayData#3]
This is to see if someone with no ties to the TravelMapping organization can submit an issue about one of its repositories.

**Comment by jteresco** [comment]
Sure looks like it.  Nice!

**Comment by jteresco** [comment]
Looks like I can reply to/comment on issues by email, too.

**Comment by jteresco** [comment]
Anyone else want to comment on this?

**Comment by ssoworld** [comment]
Sure, I'll comment on this ;)
