### ISSUE TITLE
CA Interstates cleanup

### ISSUE THREAD

**Issue by ovoss** [TravelMapping/HighwayData#30]
Reviewing all CA Interstates for needed changes such as for new interchanges, or waypoints out of synch with other Interstate route files. Updated locally so far: I-80 (includes waypoints for where new Bay Bridge peels away from old roadway, for people unlike me who consider the new bridge a de-clinch) , I-505.

**Comment by rschen7754** [comment]
The Ranchero Road interchange on I-15 (exit 140) is now open. Same for Duncan Canyon Road (exit 117) and Nisqualli Road (exit 148).

**Comment by ovoss** [comment]
Thanks for the heads-up. I'll make the changes to the I-15 route file, and 
include that in a pull request covering all the routes with new 
interchanges, etc. (I-80 and I-505 updated so far).

Oscar

----- Original Message -----
