### ISSUE TITLE
OH/KY: New US 62 routing

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#303]
Reported by user bejacob by email:

Also noted something unusual along US52/62/68 in southern Ohio. Looks like US62 now has a new routing across the Ohio R. into KY (concurrent with US68). The old routing is now signed Bus US 62/68. Could require changes in both OH and KY. Didn’t see Bus routes for either US62 or US68 in Maysville, KY or Aberdeen, OH.

**Comment by yakra** [comment]
http://clinched.s2.bizhat.com/viewtopic.php?t=1764

**Comment by yakra** [comment]
bejacob writes [on AARoads] (http://www.aaroads.com/forum/index.php?topic=15733.msg2117265#msg2117265)

>US62/68 rerouting in OH/KY.

>Old topic from CHM. http://clinched.s2.bizhat.com/clinched-ftopic1764.html&highlight=us62. The new site is still showing the old routing.

>Here's the best I can do finding signage https://www.google.com/maps/@38.6537576,-83.7574047,3a,49.4y,27.44h,90.97t/data=!3m6!1e1!3m4!1sk_LZKfgSDHpVSM4U6M_Feg!2e0!7i13312!8i6656. Here is a link that has a few photos http://www.alpsroads.net/roads/oh/bus_62/.

>Having just driving the route, I looked through the HB as I didn't recall seeing any Business routes in Ohio for US62.

>Anyway, I suspect someone may wish to explore the issue further for both KY and OH.

**Comment by mapcat** [comment]
I should be able to check how it's posted in the field in a few weeks. In general, will that suffice for determining how it should appear in TM, or will more official documentation of the new (or reverted) routing be necessary?

**Comment by yakra** [comment]
Official documentation may be dubious. Non-canon. Let's try to Match field signage -- and hope it's something sensible. Make sure you get a very good look! Everywhere. :D

**My hypothesis:**
* KY US62 comes in from the southwest, crosses over US68 without interchanging, heads east, picks up US68Bus and heads north, leaves US68Bus & joins KY9/10, following them west to US68 on the bypass, then follows US68 northeast to the state line.
* OH US62, we'll need to cut back at the south end, and reroute onto US68 on the bypass.
* US62Bus created in both states from the vacated waypoints. It should overlap US52 north to US62.
* US68 stays where it is.
* KY US68BusOld gets extended north along the newly-created US62Bus.

**Comment by mapcat** [comment]
Just sneaked into Maysville this morning and got out before Snowmageddon hit.

Your wise hypothesis is too logical for the local DOTs. For some strange reason, Ohio marks US62 on the Aberdeen side of the US68 bridge (the new-ish bypass) as US62Bus. But there is no plain vanilla US62! Well, to be precise, there is, since a few of the US62 signs lack the Business banner. But so few that they appear to be the erroneous signs rather than the other way 'round.

Kentucky is the sensible entity here. US62 follows the route shown in the HB. Signage is consistent and clear. There is no US62Bus marked anywhere in the region on the KY side. The bypass is US68 only.

So I propose that we change nothing. Either that, or make US62 discontinuous and use US62BusAbe to splice the two segments. Which would be ridiculous.

**Comment by yakra** [comment]
> But there is no plain vanilla US62! Well, to be precise, there is, since a few of the US62 signs lack the Business banner. But so few that they appear to be the erroneous signs rather than the other way 'round.

"There is just one US62 here. It is a business route. But it's the only US62 here."
Reminds me of how there's just one VT7A. Which is also "Historic" bannered VT7A. But it's the only VT7A.
I can dig it.

Leaving US62 & 68 as they are sounds like the right plan.
However... what did you see of [KY US68BusOld](http://tm.teresco.org/devel/hb.php?r=ky.us068busold)? Should that stay as is? Get extended?

**Comment by mapcat** [comment]
Oh, right. Signage for US68BusOld ends where it meets US62 in Old Washington, so it should be shortened. I have a couple other files to upload and will add this to it.

**Comment by mapcat** [comment]
Seems that this goes against the Manual, but...wouldn't it be appropriate to make the old northern end point (KY9/10) an alt label for the new northern endpoint (US62_W, which I'm gonna call US62)? Because KY9/10 is in use.

**Comment by mapcat** [comment]
The update that just ran included the truncated route with +KY9/10 as an alt label for US62.

**Comment by yakra** [comment]
Can't remember about the manual, but Tim discouraged using old points as AltLabels in cases of truncation.

Since transitioning from CHM to TM, we seem to be moving in this direction more (allowing it) now.
