### ISSUE TITLE
AUT: E523

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#311]
Reported by user bogdymol by email:

Austrian E532 seems it was missed/forgotten, as it does not appear in the list of E routes in Austria. (map: https://goo.gl/maps/N9GBK5iEDiJ2 ).

**Comment by si404** [comment]
This was raised after I revamped Austria and my answer is pretty much the same as then:
 - it isn't in the official UNECE log
 - if it is signed, and I see some evidence, I'll add it.

To add to this, I've just watched a video of most of the route (northbound) from Oct 2014 and found no signs for E532 in that half an hour. It's really not like I'm being aloof and not wanting to add it, it's that I can't find a valid reason to add it. See also the Spanish E903: not in the logs, on editable sources like wikipedia, OSM, Google Maps, but signed nowhere.

What I'll do is make a file (and for the E903) and if any evidence comes up of signage, it can be added very quickly.

**Comment by michihdeu** [comment]
I can confirm that I couldn't find any evidence on videos or any other source although I thought I've see an E534 sign there in October 2014.

Bogdymol is used to take pics on road trips. Maybe he has taken one showing an (Austrian) E532 sign?

**Comment by michihdeu** [comment]
There's no evidence that it's signed and concurrent B179/B189 is drafted now.
I think the issue can be closed.
