### ISSUE TITLE
NC US421 Sanford bypass

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#315]
via mapcat on AARoads:

>In North Carolina, US421 bypasses Sanford and the former route is signed as Business 421.

**Comment by ovoss** [comment]
As it happens, I'll be passing through Sanford tomorrow (via the bypass), on 
my way down to Florida for a few weeks. It looks like mapping the bypass, 
and the business route on the old alignment, should be straightforward. But 
if it isn't, and you see issues that could use a field check, let me know by 
around 3am tomorrow morning (when I start shutting down my computers for a 
pre-dawn departure), and I'll see what I can do.

Oscar

----- Original Message ----- 
From: Eric Bryant
To: TravelMapping/HighwayData
Sent: Tuesday, January 05, 2016 2:24 PM
Subject: [HighwayData] NC US421 Sanford bypass (#315)


via mapcat on AARoads:
In North Carolina, US421 bypasses Sanford and the former route is signed as 
Business 421
—
Reply to this email directly or view it on GitHub.



--
Oscar Voss - ovoss@pobox.com (old address still works) - Arlington VA

my Hot Springs and Highways pages (new address):
http://www.alaskaroads.com/home.html

**Comment by yakra** [comment]
I gave the HB a cursory look, and it looks straightforward enough.

Is it the case that Dave is inactive now that we're using GitHub to submit updates, and NC doesn't have a designated "owner"?

**Comment by ovoss** [comment]
Just a followup, after driving past Sanford yesterday:-- east of US 1, the new US 421 is also signed as Bypass NC 87, a route not in the HB. IIRC,, the part of the Sanford Bypass south of US421/Business US 421, which is not included in US 421, is signed as Bypass NC 87 as well. Some online maps show the new US 421 as "bypass" US 421, which extends south of what is now the US 421/Business US 421 eastern junction, but neither is true -- it's vanilla US 421 on the bypass, and turns east onto its old routing at the Business US 421 interchange. 

MQOpenMap, but no other online maps, shows this. It also shows the vanilla NC 87 still going through downtown Sanford as the HB has it. though I can't confirm that fact -- so NC 87 can remain intact except for renames of its waypoints for the Sanford Bypass. 

Oscar (in Georgia, heading south)

**Comment by rickmastfan67** [comment]
Also see in reference to the NC-87 Bypass: http://clinched.s2.bizhat.com/viewtopic.php?t=2244&mforum=clinched

**Comment by rickmastfan67** [comment]
I think this was dealt with #437 & #445.  So, I assume this is safe to close now?

**Comment by yakra** [comment]
Looks like it.
