### ISSUE TITLE
PA441 relocation, Columbia

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#316]
via 74/171FAN on AARoads:

>Has anyone mentioned the PA 441 relocation in Columbia here yet?  Basically it follows Front St instead of Locust St and 3rd St through downtown and connects to 3rd St at the north end of the US 30 interchange.  From a short field visit on Christmas Eve, it seems that PA 441 is exclusively being posted that way now (coming towards Columbia I saw 3rd St being posted as "TO PA 462", I did not check the borough itself.

>In result, PA 441 does not intersect PA 462 anymore ... and the US 30 point should be moved to the north end of the interchange.

PA462 will need its PA441 point relabeled.

**Comment by rickmastfan67** [comment]
Already added the new route into OSM thanks to NAIP.  I didn't update route tags since I hadn't heard about how they signed it.
