### ISSUE TITLE
 NY NY146 CamRd

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#32]
Jim, once upon a time you submitted my point request for NY146.
But it appears that happened after Tim stopped processing CHM data updates, and it's not in the HighwayData master here now.

CamRd http://www.openstreetmap.org/?lat=42.775661&lon=-73.934319

http://clinched.s2.bizhat.com/viewtopic.php?p=16036&mforum=clinched#16036

**Comment by jteresco** [comment]
This is in the DB and in the GitHub master.
