### ISSUE TITLE
MD 200 extension

### ISSUE THREAD

**Issue by ovoss** [TravelMapping/HighwayData#33]
MD 200 (Intercounty Connector toll road in the D.C. suburbs) was extended awhile ago, east from I-95 to US 1. No further extensions planned.

I was not planning on taking on any other updates in this unassigned state, but I can take care of this one if nobody else wants it.

**Comment by jteresco** [comment]
This update is in the DB.

**Comment by yakra** [comment]
US1 is still missing its MD200 point.

**Comment by jteresco** [comment]
The US1 fix is now in the DB as well.  All good on this one?
