### ISSUE TITLE
KY: Clinton County notes

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#332]
reposition ky.us127busalb south end
KY1076 south end, minor reroute

**Comment by yakra** [comment]
US127 & US127BusAlb fixed in #364.

Leaving this issue open, as US127 still needs a little TLC in southern KY.
• points on old alignment, e.g. KY558

**Comment by mapcat** [comment]
@yakra sorry for missing this. I made some slight realignments to US127 to match up with newer imagery. Anything else necessary?

**Comment by yakra** [comment]
KY558 is still off-center; that's about it really

**Comment by mapcat** [comment]
Ah, I hadn't checked that far north. Fixed in my files.

**Comment by mapcat** [comment]
Live in HB.

**Comment by yakra** [comment]
Shall I close the issue?

**Comment by mapcat** [comment]
If you consider it solved, then yes, please.
