### ISSUE TITLE
OH: I-275 exit 31

### ISSUE THREAD

**Issue by mapcat** [TravelMapping/HighwayData#334]
Reference map: https://www.google.com/maps/place/Blue+Rock+Rd,+Cincinnati,+OH/@39.2322946,-84.6291285,15.75z/data=!4m2!3m1!1s0x88403566f3536e63:0x1d19ec07df4a53bd

Exit 31 serves different roads, depending on the direction travelled. Westbound, it goes to Blue Rock Rd, but the eastbound exit serves as the beginning of Ronald Reagan Cross County Hwy, whose first exit is for Blue Rock Rd (via a different interchange). There is only one waypoint currently, centered on Blue Rock Rd. I'm planning on creating a new point for the eastbound exit, and want to call it 31A. The main reason is that eventually I'd like to create a new file for RRCC Hwy (separate issue), and otherwise there's no logical western endpoint for it.

Thoughts/concerns?

**Comment by yakra** [comment]
http://cmap.m-plex.com/tools/manual_points.php
> Double half interchanges: Usually use one central point and treat both halves as a single, full interchange. Exceptions: a clear gap of at least 0.5 mi/0.8 km separates the two halves, or each half connects to a different highway that we are also mapping.

I opened the file in WPTEdit, and added a new waypoint at http://www.openstreetmap.org/?lat=39.230142&lon=-84.634788 . WPTEdit listed the visible distance to Blue Rock Rd as 0.50 mi. So, potential rounding errors aside, that's at just about exactly the cutoff. If I were drafting the file now, I'd probably make 2 waypoints.

Labeling? The neat freak in me would have me follow alphanumeric order and make the new one 31, and relabel the existing one as 31A. That would cause a tiny disruption to .list files, so I'd write some updates text for it. OTOh, Would it be wrong to put 31A before 31? Well... Nova Scotia does this, like... everywhere. But I'm not aware of it happening anywhere in the US, especially on a large scale. Shrug.

**Comment by mapcat** [comment]
How about calling the new waypoint RonReaHwy? I don't want to affect anyone's .list. Or does the expectation that every numbered exit's waypoint be that number (besides end points) preclude using other labels?

**Comment by yakra** [comment]
Since it's an Interstate, yeah, numbered exits should be used.
http://cmap.m-plex.com/tools/manual_wayptlabels.php
>Two separate interchanges numbered 6. Distinguish them by picking the next available letter suffix for the second interchange. Number the first interchange normally.

Relabeling 31 to 31A is only the tiniest of disruptions to existing lists; it'll barely even register in maps & stats.
OTOH, if you wanna take a page from Nova Scotia's book (your original proposal)... Discuss? What do other collabs have to say here?

**Comment by mapcat** [comment]
I checked again to see if it was in use, and it is, but only in the CHM labels in use file. So since potential .list-breakage only exists for new imports of old CHM .lists, it seems that renaming 31 to 31A. Also, given that it's not currently in use *in TM*, 31A would **not** need to be given an alt label, and the renaming would not need to be reported as an update, correct?

**Comment by yakra** [comment]
>I checked again to see if it was in use, and it is, but only in the CHM labels in use file. So since potential .list-breakage only exists for new imports of old CHM .lists, it seems that renaming 31 to 31A.

w0ot!

> Also, given that it's not currently in use in TM, 31A would not need to be given an alt label, and the renaming would not need to be reported as an update, correct?

Correct.
Although, you could still optionally write updates text for those users importing old CHM .lists.

**Comment by jteresco** [comment]
Implemented.  Closing.

**Comment by yakra** [comment]
Checked this out when looking for issues to close.
And now, the nitpickiest of nitpicks:
> * 2-way high-speed interchanges: where the centerlines would cross if it were an at-grade intersection with the same shape. Not where the ramps of one road connect to the other.

A good example being ME I-295 2.
Something to keep in mind in the future; I won't ask that you bother to change this one. There are probably still plenty of examples floating around in my earlier work.
