### ISSUE TITLE
OH: Ronald Reagan Cross County Hwy

### ISSUE THREAD

**Issue by mapcat** [TravelMapping/HighwayData#335]
Reference map: https://www.google.com/maps/place/Blue+Rock+Rd,+Cincinnati,+OH/@39.2322946,-84.6291285,15.75z/data=!4m2!3m1!1s0x88403566f3536e63:0x1d19ec07df4a53bd

This limited access highway is not currently in the usasf set, but ought to be added. Most of it is also part of OH126, but there is a western segment that is not part of any other route.

If the highway is added, another waypoint will need to be added to I-275 (separate issue).

First off, how can I post a version of my file for RonReaCroCouHwy here for comments before submitting a pull request?

Second, since there is no usasf file for Ohio, how can I create one?

**Comment by jteresco** [comment]
I can create you the directory where it would live if that's not easy or obvious how to do.

One thing I note is that the name would be much shorter.  Maybe something like RReaCCHwy?

I'll leave it to others to comment on whether this makes sense to add.

**Comment by mapcat** [comment]
Well, it may be easy, but it's not obvious, sorry.

I've looked at some GMSV and note that many BGSs refer to it as Ronald Reagan Hwy now, so RonReaHwy I guess?

**Comment by jteresco** [comment]
Not a problem.  If and when it's ready to add, just email it to me and I can create the new directory at the command line and put the file into the correct place.

**Comment by yakra** [comment]
I was thinking RonReaHwy.
http://cmap.m-plex.com/tools/manual_wayptlabels.php
>If the cross road name has more than 3 words, use one of two options:
>1. Pick out the two most important words besides the road type and use only those: Martin Luther King Boulevard becomes MarKingBlvd. Three words in total are included in shortened form.
>2. Pick out one important word besides the road type and use it and the initials of the other words: Martin Luther King Boulevard becomes MLKingBlvd. Two words in total are included in shortened form along with initials of the rest.
Based on this, Jim's RReaCCHwy would also be acceptable. I just like RonReaHwy better. :)
If the BGSs are saying Ronald Reagan Hwy, then yeah, how'bout RonReaHwy?

To add the file using the GitHub web interface, surf to hwy_data/OH/ in the appropriate branch of your repo.
To the right of "HighwayData/hwy_data/OH/", Click on the "New file" button.
Still to the right of "HighwayData/hwy_data/OH/", in the small "Name your file..." field, type in "usasf/" and then continue to type the filename, in this case oh.ronreahwy.wpt.
Then edit the file as normal. After you make the commit, GitHub will create the file in the usasf directory.

> I'll leave it to others to comment on whether this makes sense to add.
If this were Texas, it would be signed as a state highway spur, and thus included.
We seem to be moving away from the initial CHM-legacy limits on minimum route length, number of interchanges, yadda yadda, and more toward better connectivity & filling in the missing links in the route systems. Anyone else wanna chime in? @si404? @ovoss? @rickmastfan67?

**Comment by jteresco** [comment]
I also like RonReaHwy better.

I am in favor of adding in even very short routes if they're part of systems we're otherwise developing.  The minimum route length or interchange count never made any sense to me on CHM.  If it was there because of the costs of site updates going up too fast or load on the server getting too high, I can say we have had no such issues with TM and I don't think the extent of our highway coverage or the number of users we'll attract will be causing those kinds of issues any time soon.

**Comment by jteresco** [comment]
I think this is all in now, so I'm closing the issue.
