### ISSUE TITLE
OH: point label changes

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#337]
Ping @mapcat:

**OH143:** OldOH684 -> OH684 (right?)

**OH183:**
MainSt -> MainSt_Mag
OH183Trk_S -> MainSt_All
OH183Trk_N -> ElySt

**Comment by mapcat** [comment]
On my list, thanks!

**Comment by mapcat** [comment]
Re the OH183 renamings, since neither OH183Trk_ point was in use, and they don't affect the shape, wouldn't it be acceptable to delete both?

**Comment by yakra** [comment]
Addressed in #345.
Personally, I'd have just changed the labels of the OH183Trk. It's what we've usually done, to my knowledge, and I like having the, uhh, "historical" points, noting that there used to something there. It's possible too that someone could come along in the future who did use them.
But I'm not going to cry about it. :) I've merged in your pull request.

**Comment by mapcat** [comment]
Noted. If it were a more significant route, rather than a 2-block bypass of a formerly low bridge, I would've done the same.
