### ISSUE TITLE
TM manual

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#339]
I know we're mostly still going by the CHM manual for naming routes, selecting points, naming points, etc.  I also know we've had some discussion about updates.

I propose we make the manual a wiki page in this repository here on GitHub.  It could start out with the content from CHM's manual, and we can all collaborate on it to update it.

I think this is better than a page on the web site, which would have to be separately maintained and installed.  Of course, we could have a link to the manual here from the web site, along with links to other tools for highway data managers.

Objections?

**Comment by mapcat** [comment]
Sounds like an ideal use for a wiki, either here or on TM proper.

**Comment by yakra** [comment]
No objections.

**Comment by mapcat** [comment]
I started a page:

[Updating a file and creating a pull request using the GitHub web app](https://github.com/TravelMapping/HighwayData/wiki/Updating-a-file-and-creating-a-pull-request-using-the-GitHub-web-app)

**Comment by yakra** [comment]
I've only barely started looking this over. It describes making changes to TravelMapping/master. I'd rewrite it to describe using one's own fork/branch to make changes. Which is worthy of more instructions & how-tos in its own right. (Oh dear, how deep this rabbit hole goes...) How to best do this could use some discussion.

**Comment by jteresco** [comment]
The one from @mapcat is for using GitHub, I'm thinking we get the CHM manual pages (about how to create various kinds of files, how to choose and name waypoints, etc) over here too.

**Comment by michihdeu** [comment]
This was discussed on the [forum](http://forum.travelmapping.net/index.php?topic=287) too (w/o result). I think this issue could be closed.

**Comment by jteresco** [comment]
Yes, another thing more appropriate for Forum discussion.
