### ISSUE TITLE
2 possible business routes in Ohio

### ISSUE THREAD

**Issue by mapcat** [TravelMapping/HighwayData#340]
One has been mentioned in the CHM forum: 

http://clinched.s2.bizhat.com/viewtopic.php?t=2196&highlight=portsmouth&mforum=clinched

I've seen the signs myself. It's marked fairly well southbound but there's no indication at all northbound. And as Dave said at the time, there's no easy way to map it given that mainline 23 runs parallel to it on a south/north pair, each a block away from the business route.

The other is a DIY Business 50 in Belpre, marked as "Business Loop" on a variety of signs, all of which are in Ohio. Belpre is on the river, so half of the so-called loop would therefore be in West Virginia, but West Virginia seems blissfully unaware of it. Nearly the entire route in Ohio is coextensive with OH618, and what isn't follows OH32 to the state line, so no new mileage is involved.

Are either of these worth any amount of attention?

**Comment by yakra** [comment]
**Portsmouth**, I'd probably be inclined to leave out. No good way to map it; sure, we could tweak point coords or add a hidden point to break the false multiplex, but it'd still look funky in mapview.php. I'll let the lack of good signage and probably-quasi-unofficial status further swing me in that direction. I don't see a listing for it in the AASHTO db, but OTOH that doesn't seem to have been fully updated from the 1989 log...

**Belpre:** FWIW, there's the case of RI US1AltPro signed as US1A only in RI; on the MA side of the border it's MA1APro.

**Comment by mapcat** [comment]
@yakra:
https://www.google.com/maps/@39.2721426,-81.5691233,3a,75y,323h,95.35t/data=!3m6!1e1!3m4!1sM4quI9aoFjdi7RpaVImwBw!2e0!7i13312!8i6656!6m1!1e1

https://www.google.com/maps/@39.2724971,-81.5702246,3a,75y,323h,95.35t/data=!3m6!1e1!3m4!1ssnHEITGMV-mDV_0a_0rpRg!2e0!7i13312!8i6656!6m1!1e1

https://www.google.com/maps/@39.2819999,-81.6805818,3a,16.5y,40.03h,85.26t/data=!3m6!1e1!3m4!1s7yZ_PXa6PBDodmWn7_sLBg!2e0!7i13312!8i6656!6m1!1e1

**Comment by mapcat** [comment]
Since this hasn't been dealt with yet, I'm not sure what closing it means: ignore the Belpre business route? Mark it in Ohio only and end it at the state line? Consult something to determine if it really exists in West Virginia?

**Comment by yakra** [comment]
Closed because old forum thread was ready to lock. Forgot that it didn't deal with Belpre.

**Comment by mapcat** [comment]
Added US50BusBel to OH but not WV a few weeks ago. Closing.
