### ISSUE TITLE
OH2 freeway end @ US 20

### ISSUE THREAD

**Issue by mapcat** [TravelMapping/HighwayData#341]
One of today's cleanup projects was OH2, which has had some more exit tabs bestowed upon its freeway portions. The easternmost freeway segment (and the route overall) ends at US20, whose waypoint we've been calling US20_E. However, the last BGS on the freeway provides an exit number, even though it's simply a road that narrows into a ramp that merges into US20, and not an exit in any conventional sense:

https://www.google.com/maps/@41.7519048,-81.2082186,3a,75y,42.72h,85.67t/data=!3m6!1e1!3m4!1s0MkHrakw7lSEz6uqnKoeiA!2e0!7i13312!8i6656

When is an exit not an exit? Am I right to continue calling this point US20_E?

**Comment by yakra** [comment]
Exit 227, huh? I'd say go for it.

**Comment by mapcat** [comment]
Done.

Related note: waypoints 174B(90) and 185(I-90) have associated OH2 exit numbers now (196B and 207). Should the OH2 exit numbers take over, or should the ones associated with the interstate take precedence?

**Comment by yakra** [comment]
The OH2 ones should take over.

**Comment by mapcat** [comment]
👍
