### ISSUE TITLE
File consistency checks and fixes

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#344]
This is a reminder to myself to put in extra checks for things like extraneous spaces, missing newlines at the end of files, and whatever else might be inconsistent across our csv and wpt files.  As part of this, I'd also intend to automate fixes to such problems, and then have new instances of such problems reported in a log file (or something like that).  Low priority.

**Comment by si404** [comment]
My anal retentiveness always deletes new lines at the ends of files as they seem extraneous - do they actually cause an issue?

Another thing to add would be hiding alt labels for waypoints (ie making sure there's a + there).

**Comment by jteresco** [comment]
Really I have no strong preferences for whether there's a newline at the end or not, but I would like consistency.

**Comment by yakra** [comment]
FWIW when I edit a file using GitHub's web interface, I delete the terminating newline, and GitHub adds it back in for me anyway.

Some text editors don't put a newline into the file if you don't add it in at the end (Windows Notepad). Others (eg Linux stuff such as gedit) will always add it into the file, but not show it in the editor interface.

Some programs that process text files can be gummed up by a file missing the terminating newline; I think it's a good policy to have them.

**Comment by jteresco** [comment]
The way I deal with it in the processing script is to strip off the new line (if it exists) as I read each line.  I edit with Emacs, and it warns if a file has no newline.  It's generally expected in a Unix world.

**Comment by yakra** [comment]
Ugh. God. I lose track of where it's expected and where not...

**Comment by michihdeu** [comment]
@jteresco I think that our check have been improved meanwhile. Is there anything still open? If so, I think we should open specific issues (and close this issue here)

**Comment by jteresco** [comment]
Agreed.  Closing.
