### ISSUE TITLE
Future I-66 in Kentucky

### ISSUE THREAD

**Issue by mapcat** [TravelMapping/HighwayData#358]
The recent adjustments in Kentucky got me thinking: what evidence is needed in order to delete Future I-66? Is there any chance of this being built?

"Federal transportation officials quietly pulled the plug on the 66 Corridor project this past summer after Kentucky withdrew its support for what was once envisioned as a coast-to-coast interstate that would invoke the iconic cross-country Route 66."
http://www.sj-r.com/article/20160101/NEWS/160109969

"There is no federal I-66 corridor-wide study, although an I-66 environmental study had begun with the three states involved," said Nancy Singer, a spokeswoman for the U.S. Department of Transportation's Federal Highway Administration.  "It has since been discontinued now that the three states are not pursuing the project."
Original behind paywall: http://www.paducahsun.com/news/local/010716_PS_66-Corridor
Cache: http://webcache.googleusercontent.com/search?q=cache:XYz9ADXen1IJ:www.paducahsun.com/PrintPage/010716_PS_66-Corridor+&cd=1&hl=en&ct=clnk&gl=us

**Comment by yakra** [comment]
I was just about to investigate relabeling KY KY I-66FutBow to use the numbered exits from the various parkways and Interstates it overlaps, then saw you'd posted this. Interesting.
I'd much rather just scrap this route than bother going thru that rigamarole. :D
Reading up on it, it looks like the designation is written into law (?), and there was still "Future" signage as of 2013. [East](https://www.google.com/maps/@37.0551902,-86.1063551,3a,66.8y,126.82h,85.06t/data=!3m4!1e1!3m2!1sBOBv9Vc5gQQW7FKjOFlVUA!2e0) [West](https://www.google.com/maps/@36.9822367,-85.9423008,3a,66.8y,303.49h,85.42t/data=!3m4!1e1!3m2!1sGFvzyMXPl9Nv6iveX7nZeQ!2e0)
I'd wait for confirmation that that's gone away, I guess.
It may also be worthwhile to ask H.B. Elkins; maybe he knows the latest about its status.

**Comment by mapcat** [comment]
Received a reply from H.B. Elkins:

> The new road plan submitted by KYTC and the governor actually lists at least two I-66 projects for Kentucky. One is an environmental study for the route between Somerset and London. The other is construction of the northeastern bypass.

So it's not exactly dead, although both of those projects could proceed regardless of I-66's future.

**Comment by yakra** [comment]
A modest proposal:

> 68(69) +I-24 +42(24) http://www.openstreetmap.org/?lat=37.071384&lon=-88.084973
71(69) http://www.openstreetmap.org/?lat=37.104907&lon=-88.033158
+X015(69) http://www.openstreetmap.org/?lat=37.109665&lon=-88.024156
+X016(69) http://www.openstreetmap.org/?lat=37.106738&lon=-87.986369
79(69) http://www.openstreetmap.org/?lat=37.122643&lon=-87.893119
81(69) http://www.openstreetmap.org/?lat=37.132831&lon=-87.871023
+X017(69) http://www.openstreetmap.org/?lat=37.142282&lon=-87.807401
+X018(69) http://www.openstreetmap.org/?lat=37.196258&lon=-87.698777
92(69) http://www.openstreetmap.org/?lat=37.198100&lon=-87.689137
+X019(69) http://www.openstreetmap.org/?lat=37.200027&lon=-87.668570
+X020(69) http://www.openstreetmap.org/?lat=37.189630&lon=-87.602749
+X021(69) http://www.openstreetmap.org/?lat=37.212648&lon=-87.469754
106(69) +PenPkwy http://www.openstreetmap.org/?lat=37.212451&lon=-87.441312
+X001(Wes) http://www.openstreetmap.org/?lat=37.212562&lon=-87.404480
+X002(Wes) http://www.openstreetmap.org/?lat=37.229521&lon=-87.371660
+X003(Wes) http://www.openstreetmap.org/?lat=37.236714&lon=-87.326058
+X004(Wes) http://www.openstreetmap.org/?lat=37.231161&lon=-87.290019
48(Wes) http://www.openstreetmap.org/?lat=37.234416&lon=-87.274414
53(Wes) http://www.openstreetmap.org/?lat=37.253479&lon=-87.198025
+X005(Wes) http://www.openstreetmap.org/?lat=37.256447&lon=-87.180355
+X006(Wes) http://www.openstreetmap.org/?lat=37.272286&lon=-87.155340
58(Wes) http://www.openstreetmap.org/?lat=37.281903&lon=-87.109206
+X007(Wes) http://www.openstreetmap.org/?lat=37.288817&lon=-87.084895
+X008(Wes) http://www.openstreetmap.org/?lat=37.315060&lon=-87.051474
+X009(Wes) http://www.openstreetmap.org/?lat=37.321758&lon=-87.032635
+X010(Wes) http://www.openstreetmap.org/?lat=37.320085&lon=-86.998072
+X011(Wes) http://www.openstreetmap.org/?lat=37.353648&lon=-86.914183
+X012(Wes) http://www.openstreetmap.org/?lat=37.352224&lon=-86.894281
75(Wes) http://www.openstreetmap.org/?lat=37.367565&lon=-86.842659
77(Wes) +WestKYPkwy_E +WHFWKYPkwy_N http://www.openstreetmap.org/?lat=37.384570&lon=-86.809099
+X011(Nat) http://www.openstreetmap.org/?lat=37.351750&lon=-86.785812
+X010(Nat) http://www.openstreetmap.org/?lat=37.330801&lon=-86.752982
+X009(Nat) http://www.openstreetmap.org/?lat=37.309535&lon=-86.737377
36(Nat) http://www.openstreetmap.org/?lat=37.298261&lon=-86.738879
+X008(Nat) http://www.openstreetmap.org/?lat=37.263743&lon=-86.748208
29(Nat) http://www.openstreetmap.org/?lat=37.214865&lon=-86.711268
28(Nat) http://www.openstreetmap.org/?lat=37.202915&lon=-86.701124
+X007(Nat) http://www.openstreetmap.org/?lat=37.178693&lon=-86.670161
+X006(Nat) http://www.openstreetmap.org/?lat=37.120372&lon=-86.642416
+X005(Nat) http://www.openstreetmap.org/?lat=37.101634&lon=-86.638801
+X004(Nat) http://www.openstreetmap.org/?lat=37.044195&lon=-86.578939
+X003(Nat) http://www.openstreetmap.org/?lat=37.033983&lon=-86.544762
+X002(Nat) http://www.openstreetmap.org/?lat=37.007741&lon=-86.509545
9(Nat) +US231_Bow http://www.openstreetmap.org/?lat=36.992334&lon=-86.504089
7(Nat) +US68 http://www.openstreetmap.org/?lat=36.957334&lon=-86.497078
+X001(Nat) http://www.openstreetmap.org/?lat=36.949626&lon=-86.494235
6(Nat) +US31W http://www.openstreetmap.org/?lat=36.942273&lon=-86.482363
20(65) http://www.openstreetmap.org/?lat=36.910231&lon=-86.432147
22(65) http://www.openstreetmap.org/?lat=36.934603&lon=-86.418124
26(65) http://www.openstreetmap.org/?lat=36.977748&lon=-86.390943
28(65) http://www.openstreetmap.org/?lat=37.005856&lon=-86.368697
+X002(65) http://www.openstreetmap.org/?lat=37.020599&lon=-86.253110
36(65) http://www.openstreetmap.org/?lat=37.031482&lon=-86.241238
38(65) http://www.openstreetmap.org/?lat=37.042067&lon=-86.209851
+X003(65) http://www.openstreetmap.org/?lat=37.041309&lon=-86.181967
43(65) http://www.openstreetmap.org/?lat=37.058388&lon=-86.111940
+X000(Cum) http://www.openstreetmap.org/?lat=37.043215&lon=-86.069319
+X001(Cum) http://www.openstreetmap.org/?lat=36.996182&lon=-85.990317
11(Cum) +US31E http://www.openstreetmap.org/?lat=36.978117&lon=-85.934812
+X002(Cum) http://www.openstreetmap.org/?lat=36.973407&lon=-85.912517
14(Cum) +KY90 http://www.openstreetmap.org/?lat=36.983413&lon=-85.894750
15(Cum) http://www.openstreetmap.org/?lat=36.994395&lon=-85.875278
27(Cum) +US68_Edm http://www.openstreetmap.org/?lat=36.996422&lon=-85.658534
+X003(Cum) http://www.openstreetmap.org/?lat=36.997202&lon=-85.632479
+X004(Cum) http://www.openstreetmap.org/?lat=37.008876&lon=-85.578620
+X005(Cum) http://www.openstreetmap.org/?lat=37.026253&lon=-85.549856
+X006(Cum) http://www.openstreetmap.org/?lat=37.028111&lon=-85.491067
+X007(Cum) http://www.openstreetmap.org/?lat=37.043793&lon=-85.449069
+X008(Cum) http://www.openstreetmap.org/?lat=37.072432&lon=-85.406669
46(Cum) http://www.openstreetmap.org/?lat=37.073044&lon=-85.339469
49(Cum) +KY55 http://www.openstreetmap.org/?lat=37.088481&lon=-85.303125
+X009(Cum) http://www.openstreetmap.org/?lat=37.088139&lon=-85.270627
+X010(Cum) http://www.openstreetmap.org/?lat=37.046392&lon=-85.138620
+X011(Cum) http://www.openstreetmap.org/?lat=37.044696&lon=-85.100001
62(Cum) http://www.openstreetmap.org/?lat=37.051452&lon=-85.070132
+X012(Cum) http://www.openstreetmap.org/?lat=37.069025&lon=-85.038713
+X013(Cum) http://www.openstreetmap.org/?lat=37.073691&lon=-84.964077
+X014(Cum) http://www.openstreetmap.org/?lat=37.087796&lon=-84.916758
+X015(Cum) http://www.openstreetmap.org/?lat=37.086607&lon=-84.889657
+X016(Cum) http://www.openstreetmap.org/?lat=37.100590&lon=-84.859997
78(Cum) http://www.openstreetmap.org/?lat=37.092645&lon=-84.800870
*OldCumPkwy http://www.openstreetmap.org/?lat=37.099371&lon=-84.676314
86(Cum) +KY914 http://www.openstreetmap.org/?lat=37.104698&lon=-84.662645
88(Cum) +US27 http://www.openstreetmap.org/?lat=37.125560&lon=-84.636961

**Comment by mapcat** [comment]
Thanks. I saved it locally and will do some more checking to ensure that this is still the planned route.

Did you have any opinion on the US31W issue in Elizabethtown? [pull 403](https://github.com/TravelMapping/HighwayData/pull/403)

**Comment by mapcat** [comment]
The route is still being called Future I-66 for now but signage is only present between I-65 and Somerset, so I removed everything west of I-65 exit 43. I realize there's still some discrepancy between its waypoint names and those of Cumberland Pkwy.

**Comment by yakra** [comment]
42(Cum) style labels look a bit... naughty, don't they? Of course, with the Cumberland now being the only route involved, we shouldn't need the suffix, and just plain old exit numbers ought to be OK, IMO.
OTOH, if this is considered a moribund route and as such you don't feel bothered to change it, well hey! Shrug!

**Comment by mapcat** [comment]
Right, there are numerous issues to deal with, but with the route likely to
be deleted (either because it's officially dead, or because Jim wants to
eliminate usaif entirely) I'm not particularly interested in doing all the
edits now.

I did make the changes to the datacheckfps file on my branch. Just waiting
until I have time to do some additional work before submitting a pull
request.
