### ISSUE TITLE
ROUDN issues

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/HighwayData#376]
1) E81 goes through Alba Iulia like DN1, it's not routed via the bypass (see street view sign just north of Alba).

2) DN1 just south of Alba Iulia has a different shaping point compared to E81:
+X412136 http://www.openstreetmap.org/?lat=46.008945&lon=23.537865
+X64 http://www.openstreetmap.org/?lat=46.010972&lon=23.537865

3) DN6 waypoint at A6 interchange and shaping point missing, please refer to E70:
StrTim http://www.openstreetmap.org/?lat=45.727454&lon=21.870518
**+X1A http://www.openstreetmap.org/?lat=45.721162&lon=21.874466
A6 http://www.openstreetmap.org/?lat=45.720563&lon=21.897339**
DJ609 http://www.openstreetmap.org/?lat=45.710075&lon=21.913090

4) DN7 waypoint and shaping point different to concurrent E68:

DN7_W http://www.openstreetmap.org/?lat=46.159799&lon=20.767937
+X01 http://www.openstreetmap.org/?lat=46.143686&lon=20.873766
DC103 http://www.openstreetmap.org/?lat=46.147492&lon=20.912905
DJ709D_E http://www.openstreetmap.org/?lat=46.169310&lon=20.994015

DJ709D_E http://www.openstreetmap.org/?lat=46.169310&lon=20.994015
**+X02 http://www.openstreetmap.org/?lat=46.149989&lon=20.937366**
DC103 http://www.openstreetmap.org/?lat=46.147492&lon=20.912905
+X01 http://www.openstreetmap.org/?lat=46.143686&lon=20.873766
**DJ709D_W http://www.openstreetmap.org/?lat=46.158907&lon=20.773001**
DN7G http://www.openstreetmap.org/?lat=46.159799&lon=20.767937

5) DN7 waypoint at A1 interchange Sebes-West missing, please refer to E68:
DJ704A http://www.openstreetmap.org/?lat=45.960041&lon=23.537951
**A1_SebW http://www.openstreetmap.org/?lat=45.977401&lon=23.521385**
+X27 http://www.openstreetmap.org/?lat=45.988077&lon=23.507309

6) DN1/DN7 waypoint at A1 interchange Sebes-East missing, please refer to E68/E81:

+X28 http://www.openstreetmap.org/?lat=45.924409&lon=23.620090
DN67C http://www.openstreetmap.org/?lat=45.957773&lon=23.565502

DN67C http://www.openstreetmap.org/?lat=45.957773&lon=23.565502
**A1_SebE http://www.openstreetmap.org/?lat=45.944824&lon=23.589706**
+X28 http://www.openstreetmap.org/?lat=45.924409&lon=23.620090

7) DN1 and E68 go through Fagaras like on Google Maps, not via the rural road around Fagaras

8) DN1 through Brasov is signed like on Google Maps, please refer to street view. I'm not sure about E68 routing but I guess it's like DN1 (I couldn't see any E numbering on the TM route when I drove there last September).

**Comment by si404** [comment]
Thanks for these Michael.

**Comment by michihdeu** [comment]
Thanks!
