### ISSUE TITLE
Add IND - Indian National Highways. 

### ISSUE THREAD

**Issue by naveenpf** [TravelMapping/HighwayData#397]
Please add Indian national highways to CHM. 
http://wiki.openstreetmap.org/wiki/IN:National_Highways_%28new_numbering%29
Gpx tracks are available here.

**Comment by si404** [comment]
Hi @naveenpf

They will be added, however it is a large system with many routes that will each (on average) take a long time to make, so please be patient. I probably won't start until the summer, when I will have more free time, and will have cleared more of my backlog of existing Travel Mapping tasks.

**Comment by jteresco** [comment]
Closing this issue - when the development begins, watch for a thread about this system in the project forum.

**Comment by si404** [comment]
@naveenpf might be pleased to know that some routes in India are now available to preview (ie travels can be mapped, but files might be changed without notice) - Asian Highways and National Expressways.
