### ISSUE TITLE
Endpoints inconsistencies at USA borders

### ISSUE THREAD

**Issue by ssoworld** [TravelMapping/HighwayData#4069]
I have been finding inconsistencies with the borders between USA and CAN/MEX
Just a sample - using the new long entry format
```CA I-5 MEX/USA WA I-5 WA/Can``` ???
```MT I-94 0 MI I-94 MI/Can``` ???

Some of these follow a convention of USA/CAN or CAN/USA - others follow a convention of MI/Can or Mex/TX, other still use the province/state name even on the international border

Note this affects multiple users (@ovoss (CA, NM, BC, QC, SK, YT) @compdude (WA, ID) @jteresco @yakra (TX, NH, ME, AB, MB, NB, NH, NY), @rickmastfan67 (ON) @the-spui-ninja (MT, ND) @mapcat (MI) @ajfroggie (MN, VT) @neroute2 (All MEX)

for AZ (no maintainer) - the border points are shown as MEX/USA so I did nothing to pull in this.  

Just a quick glance at EU shows entries having FRA/BEL, FRA/LUX, etc. as (@si404 @michihdeu) has at France/Belgium/Luxemburg.

I did not take the time to comb through all the possibilities.

Serious inconsistencies IMO exist here.  What is the correct way?  Can this be displayed consistently on the HB (obviously keep deprecated ones until such time as we have no need for them.

cross-posted to https://forum.travelmapping.net/index.php?topic=3754.0

**Comment by ssoworld** [comment]
Note: this still is an action required.  @mapcat, @compdude please see PMs.

**Comment by jteresco** [comment]
These all addressed by now?

**Comment by michihdeu** [comment]
I think we can close the issue albeit not fully addressed since we also have a [forum thread](https://forum.travelmapping.net/index.php?topic=3754)
