### ISSUE TITLE
NC fixes from @mapmikey

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#429]
If anyone has a chance to have a look at these, please do.  If not I will take a look as soon as work settles down a bit.

Here's Michael's message about them:

Please find attached these NC items:

New NC 906 wpt file which required new points on US 17 and US 17 busbol
Updated .csv files for NC 906
Fixes to I-73, I-74, US 220, and US 220ALT based on TM forum entry for exit recentering; also added Exit 72B to these 
I took the I-74futhig exit list and added to I-74hig list.  Don't know where/how to delete I-74futhig from the universe (or if that is even supposed to happen).
made a list of significant changes to add to the running list
[ncchanges2-17-16.zip](https://github.com/TravelMapping/HighwayData/files/135582/ncchanges2-17-16.zip)

**Comment by rickmastfan67** [comment]
Might be easier to figure out what has been changed if this was as a pull request instead of just a zip file.

**Comment by jteresco** [comment]
Basically I'm looking for someone to turn it into a pull request that I could merge in.  I won't be able to sort through it for a few days at least.  But if no one has a chance before I do, then I will.

**Comment by mapcat** [comment]
I'll do it.

**Comment by mapcat** [comment]
[Pull 430](https://github.com/TravelMapping/HighwayData/pull/430)

**Comment by jteresco** [comment]
These are merged in and an update is in progress, thanks.
