### ISSUE TITLE
NC fixes from @mapmikey, Part 2

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#435]
Again, I could sort through these maybe in a few days, but if someone wants to formulate a pull request, I can merge it in and get these in the system.

Here's the email description:

Dave mentioned changes involving a new bypass in Sanford NC...

Please find attached the following:

New US 421 BusSan file
New NC 87 BypSan file
Revised files from renaming points, etc:
US 1, US 1 Bus, US 15, US 421, US 501, NC 42, NC 78
Revised .csv files for usanc
Major changes entries and entries to add to the usausb.csv files

I made a syntax error on the NC 211 file I sent yesterday so here is the corrected version

Hopefully I got everything needed to reflect the Sanford changes...
[ncchanges2-18-16.zip](https://github.com/TravelMapping/HighwayData/files/137281/ncchanges2-18-16.zip)

**Comment by mapcat** [comment]
I should be able to get to them tomorrow.

**Comment by mapcat** [comment]
[Pull 437](https://github.com/TravelMapping/HighwayData/pull/437)

**Comment by jteresco** [comment]
I believe this is all set, so closing.
