### ISSUE TITLE
Highway Data Updates Page

### ISSUE THREAD

**Issue by mapcat** [TravelMapping/HighwayData#449]
Somehow the Montana Secondary State Highways got promoted to Preview without being mentioned in the Updates page.

**Comment by yakra** [comment]
Most recent commit, 4 days ago.
The systemupdates.csv entry would be *2016-02-20;(USA) Montana;usamts;Montana Secondary Highways;preview*
This was most likely intentional but just wanna confirm. Ping @si404.

**Comment by si404** [comment]
Yes it was intentional. I merely forgot that I had done it after sorting the file. I've simply added that to the .csv directly https://github.com/TravelMapping/HighwayData/commit/7426d454325b254e05d850ee90f1120dafc056b3
