### ISSUE TITLE
UTF-8 byte order mark

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#4561]
As of 87843cd792992a247815e69d7166a46442cedd1d, or.i105 is our first .wpt with a UTF-8 byte order mark.
~Python seems to cope with this just fine.~
Python flags this as LABEL_INVALID_CHAR once. C++ flags it 3 times; once for each byte.
Adding UTF-8 support to the siteupdate program by doing a quick check & stripping the BOM from .wpt files is the path of least resistance. @jteresco, shall I go ahead & do so?
As-is, the [datacheck entry](https://travelmapping.net/devel/datacheck.php?show=LABEL_INVALID_CHAR&rg=OR) isn't too helpful, as it displays what looks like a perfectly fine label.

**Comment by jteresco** [comment]
I'd like to keep the .wpt files all plain text, but also have some more meaningful error when they're not.

**Comment by yakra** [comment]
OK. I'll add in some additional checks for that, and a meaningful way to flag it in datacheck.
I can hit or.i105 with a hex editor & open a pull request, or leave that to you , whatever's clever.

**Comment by jteresco** [comment]
Thanks.  I just don't want non-ASCII waypoint labels creeping in, meaning .list files would also need them to be able to use such waypoints.

I'll fix or.i105.  @Bickendan if you want me to email it to you for your copy, let me know.

**Comment by yakra** [comment]
My first thought for a datacheck enhancement is to add the text `UTF-8 BOM` to the `Info` field, normally left blank for LABEL_INVALID_CHAR errors, and to add a blurb to syserr.php to clarify what that's about.

Is that sufficient, and clear?

Another approach is just to generically flag the route file itself, like I'm envisioning for [CSV-level datachecks](https://github.com/TravelMapping/DataProcessing/issues?q=is%3Aissue+is%3Aopen+label%3ACSVs+label%3Adatacheck).

---

Considering the rarity of these errors, the 1st option is less computationally expensive, and I'd like to go that route.

**Comment by jteresco** [comment]
I'd say computationally inexpensive is good here.

The best answer might be to use some GitHub tools/extensions to prevent such files from getting into the repository in the first place.  These are things I'm not really familiar with, however.

**Comment by yakra** [comment]
> I'd say computationally inexpensive is good here.

Our choices are inexpensive and *very* inexpensive. :)
It'd involve a wee extra check once LABEL_INVALID_CHAR is already flagged.

> The best answer might be to use some GitHub tools/extensions to prevent such files from getting into the repository in the first place. These are things I'm not really familiar with, however.

Not familiar with anything like that either. Gotta wonder what form that'd take, if GitHub might reject a pull request or a push of a commit merged on someone's home machine. If so... reverting their data or resolving conflicts might get hairy?

IMO handling it via datacheck is safest. Imagining the off chance of someone in the future using TM & siteupdate with their own data cooked up outside the official TM GitHub repos.

In any case, it's rare enough; it took 5 years for this to happen.

**Comment by jteresco** [comment]
Maybe I'll tackle the Issue I just created in DataProcessing (https://github.com/TravelMapping/DataProcessing/issues/415) to help keep these from getting in, at least from email submissions.
