### ISSUE TITLE
IN: Review

### ISSUE THREAD

**Issue by ajfarina** [TravelMapping/HighwayData#475]
I've finally had the chance to go through the first part of the Indiana system. I hope my review is welcomed and acceptable, as I recognize that Si is managing a ton of different projects simultaneously. Many of these are point suggestions and needed points for uncovered municipalities. Also, I've done my best to check concurrencies by comparing the coordinates for points; I did not check each intersection. So far, I've been able to get through IN55. I will try to get more done, if it helps out the project. Cheers.

**Routes to be added:** US33 Truck and IN15 Truck (Goshen)&mdash;see below

**General question:** Should all points at intersections with the lengthy duplex of US35 and IN22 be simply US35 or US35/22? I'm not entirely sure on the convention here. I'm basing this on what I see throughout the system, such as the points on IN3 in Rushville and elsewhere. I'd love to know how this works, since things like this comes up a couple of times below.

**US33:** Point suggestion for new north-south parkway (CR17) between Goshen and Dunlap

**US421:** Point needed in Frankfort (see IN28 below)

**IN 1:**
- In Connersville, suggestion for a point to cover 11th/Park and 11th/Eastern; points needed for 30th/Park and 30th/Western
- Point needed to cover Pennville (between IN18 and IN26)
- Point needed to cover Ossian (between US 224 and I-469)

**IN2:**
- Point needed in Lowell
- Point "CouRd" is located too far north of where the actual intersection is

**IN3:**
- Should the point "US35_N" be "US35/28?"
- Point "IN116_E" should be only "IN116"

**IN5:**
- Point "US224_S" should be "US224_E"
- Point "IN37" should be "US24BusHun" as IN37 doesn't go through Huntington anymore.
- Suggestion for point somewhere near Webster Lake to cover popular rec areas. Possibly CRs 600/200?
- Point needed in Cromwell (between CR100N and US33)
- Point needed in the (way-too-popular tourist trap) Shipshewana (between US20 and IN120)

**IN9:**
- Point needed at Progress Road on south side of Shelbyville (trucking bypass)
- Point suggestion at Michigan Road on north side of Shelbyville (old US 421 and covers Boggstown Road)
- Point suggestion in Alexandria in addition to the one on the far north end (one mile north of city center)
- Point suggestion for Etna Road, which is 2.5 miles south of US 24 and is former route
- Two possible shaping points between US30 and US33?
- Point suggestion at Baseline Road or E200 between US33 and IN8

**IN10:** Point suggestion at Michigan Street/Old US31 in Argos

**IN11 [Elizabeth]:** Point suggestion at 2nd Street, which continues into Mauckport; mainline IN11 is the bridge connector, so it seems prudent to have a point at the other end of it.

**IN13:**
- Point "IN15Trk" is quite incorrect and needs to be moved to intersection of Wabash and W Fulton {see IN15 point "IN15Trk_S"}
- Point "IN13Bus" should be "NWaySt"

**IN14:** Point suggestion for S900W (between IN13 and IN5_N) for shaping and only local bridge over Eel River

**IN15:**
- Point needed at intersection of 38th and Adams on south side of Marion
- Point suggestion at intersection of Detroit and E Winona in Warsaw
- Point needed in New Paris (between US6 and KerRd)

**IN15 Truck and US33 Truck (Goshen):**
- Routes need to be added
- Route follows 3rd Street between Pike Street and Madison Street, as seen here: https://goo.gl/maps/8opS8iKwBo22

**IN16:**
- Point needed in Brook (between US41 and IN55)
- Point needed in Denver (between US31 and IN19)
- Point suggestion for route shifting between roads at N800W, one mile west of Roann
- Point needed in Roann (between IN19 and IN15)

**IN17:**
- Point suggestion on north side of Logansport, such as Royal Center Pike
- Point suggestion to cover the two intersections at 12th Street near Lake Latonka (between IN8 and SycRd)
- Point suggestion at Lake Avenue and S Oak Road on the west side of Plymouth

**IN18:**
- Points suggested for S140E and S150E (over .5 mile apart) between US31 and CR400E
- Point needed in Converse {also needed on IN19, as listed below}
- Point needed in Sweetser (between IN13_N and IN9)
- Suggestion to move point in Montpelier two blocks east to Main Street (far more important roadway)
- Should the point "US27" be labeled "US27/67?"

**IN19:**
- Point "234thSt" should be renamed "JacSt" (Jackson Street)
- Point needed in Converse {also needed on IN18, as listed above}
- Suggestion to move point "CR550S" southward to 700S, the far more important roadway
- Suggestion to move point "CR1300N" one mile south to 1200N to cover turns in roadway
- Point suggestion at Etna Street on west side of Mentone
- Points suggested at CR 575N, a few miles north of US30, since turns in roadway are .5 apart
- Point needed in Wakarusa
- Point suggestion at Lusher Ave (recently decommissioned IN933) in Elkhart
- Point needed at Bus US20 (Lexington Ave) in Elkhart {listed in the HB as US20BusSou}

**IN28:**
- Should point "US41_S" be "US41/55?"
- Point "US421" should either be "US421_N" or "US421/39"
- Point needed at Hoke Avenue in Frankfort to cover turns in route {also needed on US 421}
- Point suggestion at CR300W (between IN37 and IN9) to cover Orestes
- Point suggestion at Mississinewa Avenue in Albany to cover the village and, I believe, former route 167

**IN29:** Point needed in Michigantown (between US421 and IN26)

**IN32:**
- Point suggestion to cover Perrysville (east of IN63)
- Point suggestion at intersection of South and Indianapolis Streets in Lebanon
- Point suggestion at Eagletown Road in Westfield
- Point suggestion at Little Chicago Road/Hazel Dell Parkway along Westfield/Noblesville border
- Point suggestion at Main Street (old US 27) in Winchester

**IN37 [Bloomington]:**
- The route begins at the point labeled "IN66_E" with no duplex west of that point
- Point "DeanRd" should be "DoanRd"

**IN38 [Noblesville]:** Points needed for Markleville and Greens Fork

**IN44 [Shelbyville]:**
- Point suggestion at Miller and Colescott Streets in Shelbyville
- Point suggestion at E Broadway and Michigan Road (old US 421) in Shelbyville

**IN44 Truck (Rushville):** The points are listed in the HB as east-to-west instead of west-to-east

**IN48 (Jasonville):** Point needed in Hymera

**IN51:** Points suggested for 10th Street intersections and railroad intersections in Hobart

_Routes that look good to my eyes:_
IN3 (Kendallville)
IN3 Business (Muncie)
IN4 [LaPorte]
IN4 (Ashland)
IN4 (Goshen)
IN7
IN8 [Knox]
IN8 (Auburn)
IN11 (Seymour)
IN15 Truck (Wabash)
IN22 [Upland]
IN22 (Burlington)
IN23
IN25 [Logansport]
IN25 (Westpoint) _Note: Largest town is actually Shadeland_
IN26 [Kokomo]
IN26 (West Lafayette)
IN37 (Harlan)
IN38 (Lafayette)
IN39 [Delphi]
IN39 (Little York)
IN42*
IN43 [Brookstown]
IN43 (Solsberry)
IN44 (Martinsville)
IN45
IN46
IN47
IN48 [Manchester]
IN48 (Bloomington)
IN49
IN53
IN54
IN55

**Comment by si404** [comment]
Thanks for this
> Should all points at intersections with the lengthy duplex of US35 and IN22 be simply US35 or US35/22?

That looks like US22 goes there, so I avoid doing such, though others like doing that. Either is fine, AFAICS. Two numbers are needed if they are the same class (eg I-80/90), but not if they are different.

>Point needed to cover Pennville (between IN18 and IN26)

These points aren't _needed_ but I've added most of them.

>IN28: Point needed at Hoke Avenue in Frankfort to cover turns in route {also needed on US 421}

Certainly not _needed_, and given it's a tiny deviation (moving south 100yrds), I'm not adding this and others like it. Some larger jumps between parallel routes mentioned have been included though.

>IN37: The route begins at the point labeled "IN66_E" with no duplex west of that point

The concurrency mapped reflects the signs at the location on GMSV. It's a silly little concurrency, sure, but it's a real one.

**Comment by mapcat** [comment]
I'm still learning, so please excuse the confusion, but why are these truck routes worth including? They're not signed, unless the GMSV imagery from last October is already out of date.

**Comment by ajfarina** [comment]
The routes are signed as "Truck Route" then "To US33" and "To 15" on both ends of the short detour. We've included other routes like this in OH and PA, so I thought it warranted inclusion here. I should have the chance to get back up to Goshen some time this summer (June-ish) and can check it out again. With the new alignment of US33 being built, it will probably change at the end of next year again anyway. I'm fine with not including the Goshen routes; just trying to be thorough.

**Comment by ajfarina** [comment]
Thank you, Si. I also appreciate the explanation about the waypoint labeling/placement. It makes more sense to me now. As for the points being mentioned for municipalities, I had been going with the premise (per statements made by contributors on the old CHM forum) that a point was needed for each municipality or other large settlement. I'll modify my thought process accordingly given what you said above. That said, I'll probably mention most just to be safe and leave it to your discretion.

I have some time, so I'll continue onward.

**Possible route to be added:**
- Does the ~2.5 mile freeway portion of Shadeland Avenue in Indianapolis fit within the scope of usanf? It is a full freeway with interchanges at I-465, Brookville Road, English Ave, and East Washington, before having its first at-grade intersection a half mile north of Washington. It was signed as IN100 as late as 1999 or 2000 and was part of the original beltway. Just wondering if it belonged here.

**IN57:** Point for Somerville (between IN168 and IN64)

**IN64:**
- Point needed for interchange about a mile east of the Illinois border
- Point needed for Georgetown (about three miles west of I-64)

**IN65:**
- Point suggestion for 1st and Brummitt in Owensville
- Point suggestion for all the turning in the eight mile gap between OldPetRd and CR300N_W

**IN66:**
- Point suggestion at 1st Ave on northwest side of Evansville
- Interchanges without points in Evansville: Weinbach Ave; Boeke Ave; Green River Road
- Point "IN245" should be renamed as route was decommissioned south of IN70 about 8 years ago
- Point "CarRidRd" should be "GerRidRd" and is a little off-center

**IN67:** Point for Paragon (between CulRd and SmoRd)

**IN75 [Jamestown]:** Point needed for Advance (between I-74 and IN32)

**IN75 (Flora):** Points suggested at 500N turns (between US421 and IN26)

**IN101 [Woodburn]:**
- Point suggestion for 1100N (between US224 and Monroeville)
- Point suggestion in Monroeville

**IN101 (Milan):** Points suggested in Milan and Sunman

**IN105:** Point suggestion in Andrews since it is more than a mile south of US24

**IN114 (North Manchester):** Point suggestion at Main and Wayne in North Manchester for old IN13 and being two miles east of current IN13 point

**IN120:** Point "CR3" should be "IN3"

**IN130:** The official Indiana inventory (https://gis.in.gov/apps/DOT/RoadwayInventory/) and the reference system (http://www.in.gov/indot/files/RA_ReferencePostBook_2015.pdf) both have the route terminating at IN149 and not extending east into Valpo. GMSV has signs for it continuing eastward. I'm not sure how you want to handle it. If leaving it as signed (not as officially designated), the route as shown in the HB is fine.

**IN135:** Point suggestion at either W Main Street or Smith Valley Road in Greenwood

**IN159 (Dugger):** The point label "Gre/Sul" seems strange. I'm not sure what it is supposed to be indicating.

**IN161:** Point suggestion for Holland and/or Old IN64 (between I-64 and IN64)

**IN201:** Southern terminus is actually at CR100S/Park entrance (per both INDOT sources and GMSV); perhaps strangely, the first sign on the northbound side is "JCT Indiana 201."

**IN227:** Point suggestion in Boston for Old IN122 and connector to OH122

**IN234 [Ladoga]:**
- Point suggestion at Main Street on west side of Cayuga
- Point suggestion in Kingman (west of US41)
- Point suggestion in Ladoga

**IN236 [Roachdale]:** Point suggestion at Morton-Russellville Road east of IN59

**IN246:** Points suggested at CRs 500W and 550W (east of IN159) with >.5 miles between



_Routes that look good to my eyes:_
IN56
IN58
IN59
IN60
IN61
IN62
IN63 [Harrison]
IN63 (Fairbanks)
IN68
IN69
IN70 [Newtonville]
IN70 (Derby)
IN71 [Dana]
IN71 (Dunnington)
IN101 (Brookville)
IN101 (Markland Dam)
IN103
IN104
IN106
IN109 [Anderson]
IN109 (Columbia City)
IN110 [Walnut]
IN110 (DeMotte)
IN111
IN114 [Rensselaer]
IN114 (Fulton)
IN115
IN116
IN117
IN119 [Winamac]
IN119 (Goshen)
IN121 [Connersville]
IN121 (Richmond)
IN124
IN127
IN128
IN129
IN130
IN134
IN140
IN142
IN143
IN144 [Mooresville]
IN144 (Franklin)
IN145
IN148
IN149
IN152
IN154
IN156
IN157
IN158
IN159 [Riley]
IN159 (Bicknell)
IN160
IN162
IN163
IN164
IN165
IN166
IN167
IN168
IN203
IN205
IN211
IN212
IN213
IN218 [Warren]
IN218 (Deer Creek)
IN225
IN229
IN232
IN234 (Kennard)
IN235
IN236 (Middletown)
IN237 [Cannelton]
IN237 (English)
IN240
IN241
IN243
IN244
IN245
IN249
IN250 [Pleasant]
IN250 (Brownstown)

**Comment by mapcat** [comment]
To me, this: https://www.google.com/maps/@41.5824839,-85.8344272,3a,43.5y,271.17h,93.74t/data=!3m6!1e1!3m4!1sUFyg4hH6dYGDjle6bAdoXg!2e0!7i13312!8i6656!6m1!1e1

does not seem to be the equivalent of this: https://www.google.com/maps/@41.2734635,-84.3682434,3a,75y,299.08h,89.85t/data=!3m6!1e1!3m4!1sm4xfgXETEMqiivkOiDDxGQ!2e0!7i13312!8i6656!6m1!1e1

If you know of any Ohio routes signed like the former, please let me know so I can investigate.

And thanks for all your help in getting the Indiana routes closer to activation.

**Comment by ajfarina** [comment]
I'm glad that I've been able to help out. Hopefully my look through has cleaned up what little there was to find.

As for the difference between the Goshen signage and the ones cited in Defiance: I agree that the two do not equate. In fact, I normally wouldn't have even bothered with Goshen had it not been for a few others we've discussed. The one in Ohio I recalled was the US50 Business route in Belpre. With signs like these two: https://goo.gl/maps/gJtxgeRJMn22 and https://goo.gl/maps/hpHttR2NhJH2 Although, after scanning further through the route tonight, I do see a BGS with the shield on it. Thus, even this one is different. For a while we still included the business loop in Upper Sandusky even after it was long gone on signage identical to the Goshen ones. Thankfully, Dave removed that one shortly before CHM idled. Some of the new Pennsylvania truck routes that have been added have fallen into the same category. Regardless, it's not even an issue for me, and I'm fine with their exclusion.

Here are a couple more questions relating to the usasf system in Indiana:
- Does the ~2.5 mile freeway portion of Shadeland Avenue in Indianapolis fit within the scope of usasf? It is a full freeway with interchanges at I-465, Brookville Road, English Ave, and East Washington. It was signed as IN100 as late as 1999 or 2000 and was part of the original beltway. Just wondering if it belonged here.
- Similarly, would the Sam Jones Expressway on the west side of the city near the airport qualify for usasf? It too is a full freeway between I-465 and just east of I-70.
- Since VetMemPkwy in Evansville includes an at-grade intersection in its listing, should KeyPkwy include the short span between 96th and I-465 or even include the freeway portion between I-465 and Woodfield Crossing? I personally don't care what is decided. Just curious how usasf works.

**Comment by si404** [comment]
usasf queries (which I myself asked when I looked at my states to see what could be added from them).

> Does the ~2.5 mile freeway portion of Shadeland Avenue in Indianapolis fit within the scope of usasf? It is a full freeway with interchanges at I-465, Brookville Road, English Ave, and East Washington. It was signed as IN100 as late as 1999 or 2000 and was part of the original beltway. Just wondering if it belonged here.

Only about a quarter of Shadeland Ave is freeway.

> Similarly, would the Sam Jones Expressway on the west side of the city near the airport qualify for usasf? It too is a full freeway between I-465 and just east of I-70.

Too many at-grades and not long enough freeway. I couldn't justify adding it.

> Since VetMemPkwy in Evansville includes an at-grade intersection in its listing, should KeyPkwy include the short span between 96th and I-465 or even include the freeway portion between I-465 and Woodfield Crossing? I personally don't care what is decided.

The road south of 96th is Keystone Ave, not Keystone Pkwy.

**Comment by ajfarina** [comment]
Thanks for the reply. I agree that the Sam Jones is probably too short. Please allow me to ask a couple of clarifying questions to know more about how the system works: For the Sam Jones, there are no at-grades between I-465 and I-70 (apart from the I-465 ramps), but it would have likely been included if it were longer than a 1.4 miles? Also, am I correct to assume that the freeway portion of Shadeland Ave doesn't qualify simply because the road and/or road name continues beyond the freeway segment?

I'm not sure it matters, but Keystone Parkway is actually signed "Parkway" all the way to I-465. The signs at 96th only say "Keystone Parkway" as do the ones on the north side of the I-465 ramp intersections. At the ramps, blades are posted on both sides of the intersections to show the name-change: on the north side of each intersection they show "Keystone Parkway" and those on the south side of each intersection say "Keystone Avenue." Apparently GMSV only has the north side of the interchange recent, but both are like this: https://goo.gl/maps/gV339uhRRLB2

**Comment by mapcat** [comment]
The wonky business route signs on Business 50 in Belpre aren't entirely unique; the ones for [Business 35 in Jackson](https://www.google.com/maps/@39.0597653,-82.6388418,3a,75y,6.48h,68.88t/data=!3m6!1e1!3m4!1s5L545K0KuWzcEU6sDmtdQA!2e0!7i13312!8i6656!6m1!1e1) are similar, and that's been in the HB as long as I can remember. The ones in Goshen don't have anything resembling a shield, and since Indiana does sign truck routes with shields (e.g. [Truck 44 & 52 in Rushville](https://www.google.com/maps/@39.6075235,-85.4447889,3a,75y,355.91h,90t/data=!3m6!1e1!3m4!1sZ6v9KWaLu0Ji5AzArkcWYQ!2e0!7i13312!8i6656!6m1!1e1)) these seem to me to cross the line...if we include these, then it's hard to argue against any generic shield-less Truck Route signs along a major road designed to keep truck traffic off

The second and third replies to [this topic in the old CHM forum](http://clinched.s2.bizhat.com/viewtopic.php?t=2083&highlight=truck&mforum=clinched) spell out rules for exclusion. Has that changed?

[These ](https://www.google.com/maps/@39.4023029,-84.5406246,3a,15y,275.07h,89.97t/data=!3m6!1e1!3m4!1sk3bzWJ7s_KfzQbh1vXLoKg!2e0!7i13312!8i6656!6m1!1e1)seem more worthy than the ones in Goshen, but they're not in the HB.

**Comment by mapcat** [comment]
IN201's southern terminus in the field is at the park entrance: [GMSV](https://www.google.com/maps/@40.7253785,-85.1230149,3a,73.7y,138.08h,88.57t/data=!3m6!1e1!3m4!1s8WB6hQaM3pTluTs7ZTqczQ!2e0!7i3328!8i1664)

**Comment by rickmastfan67** [comment]
I personally don't think that 'US33 Truck and IN15 Truck (Goshen)' don't qualify for this site.  I didn't see any shields for the route, plus the 'TO' text tells me that it isn't legitimate for our purposes.

Case in point, we haven't added a 'TO TRUCK PA-51' route(s) here in Pittsburgh because of the 'TO' text.  I don't see why this should be added then. https://goo.gl/maps/4sPncGmZUH82
