### ISSUE TITLE
Sunken Meadow State Parkway

### ISSUE THREAD

**Issue by vdeane** [TravelMapping/HighwayData#514]
I was looking at the NY reference route definition for the Sunken Meadow State Parkway and noticed that the reference route ends at the fee booths, just like with the Heckscher State Parkway.  Should the route file than be truncated to NY 25A in Travel Mapping?

**Comment by yakra** [comment]
This gets into the murky philosophical definition of...
What is the *Sunken Meadow State Parkway?* Is it the route that bears a certain reference number? Or is it all the roadway that is just named "Sunken Meadow State Parkway"?

**Comment by vdeane** [comment]
Indeed... and we'll probably have the same debate with the Bay Parkway when the NY Parkways system is added.  However, I will point out the Heckscher State Parkway (currently in the system as an extension of the Southern State Parkway), which is marked in TM as ending at the last exit before the fee booths.

**Comment by Duke87ofST** [comment]
If the reference route ends at the fee booth, why would the route in TM be truncated to NY 25A as opposed to to the fee booth itself?

**Comment by yakra** [comment]
> If the reference route ends at the fee booth, why would the route in TM be truncated to NY 25A as opposed to to the fee booth itself?

Probably invoking "One Point Per Interchange" here, as the fee booth is within the footprint of the interchange.

**Comment by yakra** [comment]
I plan on truncating SunMeaPkwy in the future, but will hold off until *usanyp* goes live.
http://tm.teresco.org/forum/index.php?topic=1928.msg5229#msg5229

Also notable that at the NY25A cloverleaf, the ramps to the south are signed with the parkway shield, and ramps to the north are signed with "Sunken Meadow State Park" text.
