### ISSUE TITLE
NY North Country Adjustments

### ISSUE THREAD

**Issue by vdeane** [TravelMapping/HighwayData#526]
I just saw a post on the AA Roads forum and got inspired to check the Traffic Data Report.  According to the report, NY 314 has indeed been truncated and NY 456 has been decommissioned.  I also checked NY 12E while I was there, and it appears that the report now has it ending at NY 12F at Paddy Hill instead of at NY 12, matching the signage.

http://www.aaroads.com/forum/index.php?topic=1487.msg2139228#msg2139228

**Comment by yakra** [comment]
I only see info thru 2011 online. Do you have a more recent TDR at work?
FWIW, both routes are still shown in the TDV.

**Comment by vdeane** [comment]
2014: https://www.dot.ny.gov/divisions/engineering/technical-services/hds-respository/NYSDOT_Traffic_Data_Report_2014.pdf

Looks like the station headers for those routes have been updated, but the traffic count reports haven't been reprocessed with the new headers (or reassigned new station numbers).

**Comment by vdeane** [comment]
FYI, there was another post to AA Roads with an image of NY 374 that prompted me to take a broader look.  From my post there: "I checked the 2014 Traffic Data Report and NY 314 east of US 9, NY 22 north of US 11, NY 374 north of US 11, and the entirety of NY 456 are no longer listed.  Neither is NY 12E southeast of Paddy Hill Road, and reference route 971H (Paddy Hill Road) no longer appears either, suggesting that NY 12E now officially follows the signs in the area (Main Office Traffic and Safety had mentioned something about a jurisdictional transfer in that area when I asked about it, in the two out of infinity questions I was able to get through before the guy left; there's also something going on with NY 324 at the I-190 overlap, and a new revision of the touring route log is in the works)."

**Comment by ajfroggie** [comment]
As a follow up regarding NY 314, I checked the Inventory Listing (accessible at https://www.dot.ny.gov/divisions/engineering/technical-services/highway-data-services/inventory-listing ), which still shows NY 314 as a reference route east of US 9, albeit county-maintained vice state-mantained.  That said, plenty of county maintained reference routes that are signed and within THM.

**Comment by ajfroggie** [comment]
Correction:  meant "touring routes" where I said "reference routes"

**Comment by yakra** [comment]
I believe #544 takes care of this. That's everything we need, right?

**Comment by vdeane** [comment]
I believe so.
