### ISSUE TITLE
USANES reclassification to Tier 5?

### ISSUE THREAD

**Issue by the-spui-ninja** [TravelMapping/HighwayData#528]
So I didn't really know where to put this, but should the usanes routes be classified as Tier 5 rather than Tier 4? It just seems like they are a lower tier than the normal NE routes, and some of them are even more minor than some of the MT Secondary (Tier 5) routes.

Again, I have no idea how these are classified; just throwing this out there.

**Comment by yakra** [comment]
My philosophy is that the Tier-4 vs Tier-5 question for small or minor regional systems is best settled on a case-by-case basis.
**My thought process was something like...**
For USANES, these are full-fledged state highways with state funding & maintenance -- just short ones (Short spurs off of main routes; short links between main routes), that get a different signage style accordingly.
Another thing I take into consideration is how it'll appear visually on the map. A few short spurs and stubs off of the main route system, and middlin'-length links, but not an overbearingly huge density of them, can get away with being displayed in the same color as the primary state system IMO, without the USANE routes getting lost in the visual noise.
Neighboring Kansas would have a lot of these spurs as USAKS routes on the primary state system (KS41 for example), and thus has a similar appearance.
It's when we get into denser systems with more, longer routes that I'd consider designating something as Tier 5. Think CANNSC, or CANABS (500-999 series).
Or consider Texas: USATXS & USATXL are both Tier 4, as is USATX. They don't add any large-scale visual clutter, just some clustering of short, extra brown routes in mostly urban areas. Many of these routes are freeways. Tier 5 would be for Farm to Market & Ranch to Market roads.

What are other people's thoughts on this?

**Comment by mapcat** [comment]
I agree with keeping them in Tier 4, mainly because of the Texas analog. The quality and even the signs are similar to the usane routes. To me there seems to be more of a step down from usamt to usamts, making it more sensible to differentiate between those systems.

**Comment by the-spui-ninja** [comment]
Okay, that makes sense. Now that I think about it, I don't know of any gravel usanes, while there are a significant number of usamts.
