### ISSUE TITLE
NY: Southern State/Heckscher Parkway

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#56]
The current Southern State Parkway route needs to be split.  The easternmost segment is now the Heckscher State Parkway.  Wikipedia shows the Sagtikos State Parkway as the changeover in designation and I'd try to find a citation for that in NYSDOT documents.

**Comment by yakra** [comment]
ping @vdeane

**Comment by vdeane** [comment]
Unfortunately detailed information on where those two parkways end is sparse.  They're still inventoried as one unit.  Wikipedia lists the Sagtikos as the changeover as well, but signage on NY 27 indicates NY 27.

**Comment by yakra** [comment]
Thanks. I will look around GMSV and see what I can see.

**Comment by jteresco** [comment]
I'd say pick one and call it close enough until we can find something definitive.  Or maybe keep it as a single route and call it "Southern State and Heckscher Parkways"?

**Comment by yakra** [comment]
The Traffic Data Viewer has the changeover at NY27.
Finally checked GMSV, enough to be satisfied that the changeover is there and not anywhere else.

**Comment by yakra** [comment]
As for Wiki[citation needed]pedia, enough of its info is inconsistent with itself or contradicted by imagery on HistoricAerials for me to write it off as unreliable.

Unless there are no objections, I'll put in a pull request to split the two routes within the next few days.
While I'm at it, I'll look into the fee booth issue @vdeane mentioned in #514, and see if the Heckscher should be extended.

**Comment by yakra** [comment]
> within the next few days

Haha nope. A bit after posting that, my plans changed to:

Make [several changes to NY's active *usasf* routes](http://tm.teresco.org/forum/index.php?topic=1928.msg5229#msg5229) all at once, and implement them at the same time*usanyp* either goes active or hits preview. Haven't decided which yet.
