### ISSUE TITLE
NY: I-90/I-790 Utica

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#57]
Reported on CHM forum:

I believe the HB has the incorrect waypoint for where I-790 ends/starts at the I-90 end. 

WB, this is where I think it begins (Genesee St). Note the 790 reference marker. 

https://goo.gl/maps/2H0bq 

The waypoint shown further east at Leland Ave has this posting WB. Note the TO 790 shield and the NY 5 reference marker. 

https://goo.gl/maps/lA9OL 

Coming the other way, there is an END 790 shield at Genesee St. 

https://goo.gl/maps/EHlLU 

Regrds- 
Mike
_________________
Mapmikey 
Co-curator Virginia Highways Project

**Comment by jteresco** [comment]
This sounds reasonable to me.  Is there any objection to me truncating I-790 to Genesee St.?  Its current eastern terminus predates my involvement in CHM, I believe.

**Comment by yakra** [comment]
No objection from me. Once I see this issue closed I'll update my .list entry.

**Comment by yakra** [comment]
Traffic Data Viewer & Traffic Data Report agree.
