### ISSUE TITLE
NM: US 491 southern terminus

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#63]
Regarding issue at http://clinched.s2.bizhat.com/viewtopic.php?t=2282&mforum=clinched

My reading of http://dot.state.nm.us/content/dam/nmdot/Data_Management/US_AADT_Listing.pdf leads me to believe there is a small piece of US 491 south of I-40.  But where, exactly?

**Comment by jteresco** [comment]
From mapcat on the CHM forum: 

"I was there in May, and US 491 appeared to start at I-40. I saw no indication of it south of I-40."

**Comment by the-spui-ninja** [comment]
Per GMSV, it's still signed from BL 40 as of 2012.
https://www.google.com/maps/@35.5220017,-108.761513,3a,15y,118.66h,89.47t/data=!3m6!1e1!3m4!1so_6mN6vijbzLmT2wj3eO7g!2e0!7i13312!8i6656
https://www.google.com/maps/@35.5227287,-108.759028,3a,75y,304.95h,74.49t/data=!3m6!1e1!3m4!1sLPFyljyacryDbZllQEZ9uw!2e0!7i13312!8i6656

Keep in mind, this is New Mexico, so these may or may not mean something.

**Comment by michihdeu** [comment]
@ovoss did never response to this. I guess he wasn't aware of this. I've crossposted it on the [forum](forum.travelmapping.net/index.php?topic=2772). I think it can be closed here.
