### ISSUE TITLE
NJ: Route 18 extended north

### ISSUE THREAD

**Issue by ajfarina** [TravelMapping/HighwayData#651]
Route 18 is apparently now signed north of the Rutgers campus. From the northern endpoint listed in the HB, it continues along the same roadway to the intersection with Centennial, then turns west to the I-287 interchange. It is signed on Centennial between Possumtown and the EB 287 ramps and on Possumtown between Centennial and the WB 287 ramps.

Related AARoads post: http://www.aaroads.com/forum/index.php?topic=10453.msg2144888#msg2144888

As a note, NJ has new straight line diagrams on their site to use as a primary source. See further down in the forum page linked above.

**Comment by yakra** [comment]
Silverfish? Adobe reader? Bleah, NJDOT really goes out of their way to make this info inaccessible to those of us on Linux systems. Can someone take screenshots of the relevant bits of NJ18?

**Comment by yakra** [comment]
extended in #930
