### ISSUE TITLE
NY: Rome area labels

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#67]
Copying in from CHM forum, needs addressing:

Just a reminder to myself to check out the labels on NY 26 and NY 365 south of Rome. Specifically the point on NY 26 labelled NY365_E and the point on NY 365 labelled NY26_E. Will take a look at others nearby when I do this.

**Comment by yakra** [comment]
Proposed changes:

**NY26:**
NY365_E -> SJamSt
NY46/69 +-> NY46/49
BloSt -> NJamSt

**NY49:**
NY365_W +-> NY26/365

**NY69:**
NY285 -> TabRd
NY49_N -> NY46/49
NY365_W +-> NY26/365

**NY365:**
NY26_W +-> NY26_S
NY26_E +-> JamSt
NY49/69 +-> NY26/46

**Comment by yakra** [comment]
Going ahead and making the above changes part of my pull request, with the understanding that if there are any strong objections, I can make a ninja edit before the new labels go into use. Low-numbered routes aren't always necessarily considered primary; case in point, NH NH9 NH101. I'll defer to those with more local knowledge than I have.
