### ISSUE TITLE
Datacheck FPs: New Brunswick

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#70]
nb.nb002;115;153;;VISIBLE_DISTANCE;23.85
nb.nb002;153;172;;VISIBLE_DISTANCE;11.63
nb.nb002;231;253;;VISIBLE_DISTANCE;14.14
nb.nb002;306;330;;VISIBLE_DISTANCE;14.81
nb.nb002;347;365;;VISIBLE_DISTANCE;11.09
nb.nb002;365;414;;VISIBLE_DISTANCE;30.76
nb.nb007;29;51;;VISIBLE_DISTANCE;13.47
nb.nb008;231;NB11_Bat;;VISIBLE_DISTANCE;10.29
nb.nb011;0;;;EXIT0;
nb.nb011;CapeRd;300;;VISIBLE_DISTANCE;12.25
nb.nb011;357;375;;VISIBLE_DISTANCE;11.60
nb.nb015;0;;;EXIT0;
nb.nb017;BigForkHwy;NB260_S;;VISIBLE_DISTANCE;20.92
nb.nb017;FalBroRd;SteRd;;VISIBLE_DISTANCE;14.76
nb.nb105;CamSetRd_W;KirkCemRd;;VISIBLE_DISTANCE;10.51
nb.nb107;JunRd;Dee;;VISIBLE_DISTANCE;10.42
nb.nb107;MainSt;NB625;;VISIBLE_DISTANCE;13.12
nb.nb108;NB390;Dee;;VISIBLE_DISTANCE;28.32
nb.nb108;Dee;NB420_W;;VISIBLE_DISTANCE;43.84
nb.nb116;GasERd;BroRd;;VISIBLE_DISTANCE;26.86
nb.nb117;LogRd;ChDai;;VISIBLE_DISTANCE;12.92
nb.nb123;GasERd;BetRd;;VISIBLE_DISTANCE;20.99
nb.nb160;NB134;RueDoi;;VISIBLE_DISTANCE;10.27
nb.nb180;ChRang18;NB385;;VISIBLE_DISTANCE;14.14
nb.nb180;NB385;Dal;;VISIBLE_DISTANCE;20.56
nb.nb180;Dal;CarMine;;VISIBLE_DISTANCE;17.86
nb.nb180;CarMine;OttRd;;VISIBLE_DISTANCE;16.96
nb.nb430;FraBurRd;MineRd_S;;VISIBLE_DISTANCE;14.07
nb.nb430;+x4;MineRd_N;+x5;SHARP_ANGLE;151.76
nb.nb625;MapGroRd;GorValeRd;;VISIBLE_DISTANCE;11.54
nb.nb770;LeeSetRd;PisRd;;VISIBLE_DISTANCE;10.47
nb.nb772;;;;DUPLICATE_COORDS;(44.980625,-66.970317)
nb.nb780;AlexJackDRd;DetRd;;VISIBLE_DISTANCE;11.17
nb.nb785;MtPleRd;GoreRd;;VISIBLE_DISTANCE;19.51
nb.nb845;;;;DUPLICATE_COORDS;(45.502778,-65.975012)
nb.nb933;ChMemEst_S;AboRd_S;;VISIBLE_DISTANCE;10.07
nb.tchmai;115;153;;VISIBLE_DISTANCE;23.85
nb.tchmai;153;172;;VISIBLE_DISTANCE;11.63
nb.tchmai;231;253;;VISIBLE_DISTANCE;14.14
nb.tchmai;306;330;;VISIBLE_DISTANCE;14.81
nb.tchmai;347;365;;VISIBLE_DISTANCE;11.09
nb.tchmai;365;414;;VISIBLE_DISTANCE;30.76

**Comment by si404** [comment]
added to HighwayData/datacheckfps.csv
