### ISSUE TITLE
 Datacheck FPs: Oklahoma

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#71]
ok.i035;5;15;;VISIBLE_DISTANCE;10.26
ok.i035;157;170;;VISIBLE_DISTANCE;13.19
ok.i040;200;212;;VISIBLE_DISTANCE;12.24
ok.i040;311;321;;VISIBLE_DISTANCE;10.46
ok.i044;5;20;;VISIBLE_DISTANCE;14.72
ok.i044;20;30;;VISIBLE_DISTANCE;10.25
ok.i044;62;80;;VISIBLE_DISTANCE;18.90
ok.i044;83;100;;VISIBLE_DISTANCE;16.36
ok.i044;138A(35);146;;VISIBLE_DISTANCE;11.64
ok.i044;146;158;;VISIBLE_DISTANCE;11.10
ok.i044;166;179;;VISIBLE_DISTANCE;13.02
ok.i044;179;196;;VISIBLE_DISTANCE;17.54
ok.i044;196;211;;VISIBLE_DISTANCE;14.55
ok.i044;255;269;;VISIBLE_DISTANCE;15.79
ok.i044;269;283;;VISIBLE_DISTANCE;13.16
ok.i044;289;302;;VISIBLE_DISTANCE;12.95
ok.i044;302;313;;VISIBLE_DISTANCE;11.43
ok.i044;313;OK/MO;;VISIBLE_DISTANCE;16.43
ok.indnattpk;1;16;;VISIBLE_DISTANCE;16.31
ok.indnattpk;16;38;;VISIBLE_DISTANCE;22.67
ok.indnattpk;38;63;;VISIBLE_DISTANCE;25.41
ok.indnattpk;70;82;;VISIBLE_DISTANCE;12.33
ok.indnattpk;82;92;;VISIBLE_DISTANCE;11.06
ok.indnattpk;92;104;;VISIBLE_DISTANCE;12.07
ok.mustpk;CreTpk;13;;VISIBLE_DISTANCE;11.20
ok.mustpk;37;55;;VISIBLE_DISTANCE;18.76
ok.ok001;D1625;OK/AR;;VISIBLE_DISTANCE;10.28
ok.ok003;N0520;OK95_N;;VISIBLE_DISTANCE;10.13
ok.ok003;OK95_S;CR22;;VISIBLE_DISTANCE;10.18
ok.ok010;N4340;N4240;;VISIBLE_DISTANCE;10.16
ok.ok010;BlaHolRd;US62_W;OK80;SHARP_ANGLE;141.21
ok.ok077dced;OK77D;;;LABEL_SELFREF;
ok.ok077smar;OK77S;;;LABEL_SELFREF;
ok.ok077sove;OK77S;;;LABEL_SELFREF;
ok.us259;D1650;+X25910;+X25911;SHARP_ANGLE;143.68
ok.us412;US77;US177;;VISIBLE_DISTANCE;12.33
ok.us412;OK18;OK99;;VISIBLE_DISTANCE;11.98
ok.us412;OK99;OK48;;VISIBLE_DISTANCE;10.37
ok.us412;OK82;US412Alt_C;;VISIBLE_DISTANCE;11.08
ok.us412;US412Alt_C;US59;;VISIBLE_DISTANCE;11.23

**Comment by si404** [comment]
added to HighwayData/datacheckfps.csv
