### ISSUE TITLE
Datacheck FPs: Texas

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#72]
This will leave about 7 possible errors to be addressed, which are also flagged on the old CHM datacheck, just not not marked as FPs. I'll save worrying about these until after my big upcoming Texas update.

tx.i010;0A;;;EXIT0;
tx.i010;55;68;;VISIBLE_DISTANCE;13.08
tx.i010;108;129;;VISIBLE_DISTANCE;21.31
tx.i010;192;206;;VISIBLE_DISTANCE;14.01
tx.i010;350;361;;VISIBLE_DISTANCE;11.40
tx.i010;508;520;;VISIBLE_DISTANCE;11.72
tx.i040;0A;;;EXIT0;
tx.i040;0A;15;;VISIBLE_DISTANCE;14.81
tx.i045;164;178;;VISIBLE_DISTANCE;14.81
tx.i410;;;;DUPLICATE_COORDS;(29.316788,-98.608438)
tx.i410;26B;166(35);165(35);SHARP_ANGLE;138.98
tx.i610;;;;DUPLICATE_COORDS;(29.680661,-95.381118)
tx.lp289;;;;DUPLICATE_COORDS;(33.529057,-101.844196)
tx.lp008;;;;DUPLICATE_COORDS;(29.712011,-95.153513)
tx.us180elp;I-10(0);;;EXIT0;
tx.us180elp;RepBlvd;SteRanRd;;VISIBLE_DISTANCE;24.11
tx.us180elp;McKRd;RM652;;VISIBLE_DISTANCE;11.55
tx.us183;DukeRanRd;TX239_E;;VISIBLE_DISTANCE;10.31
tx.us190;VolLn;FM1311;;VISIBLE_DISTANCE;11.21
tx.us277;PenRd;TXLp480;;VISIBLE_DISTANCE;24.81
tx.us277;FM1664_N;RM693;;VISIBLE_DISTANCE;14.57
tx.us277;TXLp79_N;GurMcBRd;;VISIBLE_DISTANCE;10.94
tx.us277;US377_N;DolCreRd;;VISIBLE_DISTANCE;13.97
tx.us277;BufRd;TX55;;VISIBLE_DISTANCE;20.29
tx.us285;PucRd;MonRd;;VISIBLE_DISTANCE;10.34
tx.us377;TXLp79;GurMcBRd;;VISIBLE_DISTANCE;10.94
tx.us385;DoveMtnRd;MirCreRd;;VISIBLE_DISTANCE;19.60
tx.us385;ChaRd;AlaRd;;VISIBLE_DISTANCE;16.41
tx.us057;FM481;ChaRan;;VISIBLE_DISTANCE;23.54
tx.us057;LanRanRd;LeoRivRd;;VISIBLE_DISTANCE;10.66
tx.us062;FM28_N;TX70;;VISIBLE_DISTANCE;15.85
tx.us062;CR247;CR290;;VISIBLE_DISTANCE;11.16
tx.us062elp;RepBlvd;SteRanRd;;VISIBLE_DISTANCE;24.11
tx.us062elp;McKRd;RM652;;VISIBLE_DISTANCE;11.55
tx.us067;PreAir;CibCrkRd;;VISIBLE_DISTANCE;14.14
tx.us067;CCRanAir;RM169;;VISIBLE_DISTANCE;26.35
tx.us067;BenRanRd;HovRd;;VISIBLE_DISTANCE;12.14
tx.us070;FM28_N;TX70;;VISIBLE_DISTANCE;15.85
tx.us070;CR247;CR290;;VISIBLE_DISTANCE;11.16
tx.us077;Tur;LaParAve;;VISIBLE_DISTANCE;15.63
tx.us077altcue;DukeRanRd;TX239_E;;VISIBLE_DISTANCE;10.31
tx.us083;SerGonRd;DolRd;;VISIBLE_DISTANCE;13.84
tx.us083;TX44;EspGatRd;;VISIBLE_DISTANCE;11.27
tx.us083;EspGatRd;FM133;;VISIBLE_DISTANCE;11.50
tx.us085;I-10(0);;;EXIT0;
tx.us090;AguaCalRd;ChiRanRd;;VISIBLE_DISTANCE;10.70

**Comment by si404** [comment]
added to HighwayData/datacheckfps.csv
