### ISSUE TITLE
IN: Indiana review, "Once More, With Feeling," as the song goes.

### ISSUE THREAD

**Issue by ajfarina** [TravelMapping/HighwayData#721]
I finally was able to take a few hours and start another run-through. I've done a bit of homework on how the site works, so hopefully the review will be beneficial. I apologize in advance for the lengthy post. I consolidated the entire system into one and include every route, even if it is fine. Once again, I don't see many major things to point out. I noticed it seems like OSM was the primary mapping base, but it has quite a few errors and misplaced alignments in Indiana. I tried to consult Google, Bing, various satellite images, and Mapquest to confirm when things looked off. I also point out a few inconsistencies with naming conventions in the system (almost all involving _X at the end). These may or may not be pertinent. I also tried to point out where points went too far afield from the intersections. As long as it was within or against the right-of-way, I ignored it.

Before I list everything below, please let me express my thanks for all the hard work put into drafting the system. It was fun plowing through it.

**IN1:**
- Point suggestion for the community of Everton
- Point suggestion at 900S for the community of Petroleum
- Point suggestion at Auburn Road for the community of Spencerville
- Point suggestion at CR40 (3 miles south of Butler), especially with Ohio SR249 ending only a couple miles east
- Point suggestion at the Johnson Lake Road/Teegarden Road exchange a couple miles north Clark's Landing.

**IN2:** Looks good.

**IN3 [Muncie]:**
- Suggestion to move point BlaRd north a mile to Main Street in Deputy to cover the town and more important roadway
- Point suggestion for Sandusky
- Point suggestion at 900N (9 miles north of Rushville) for connection to Mays, a park, and IN140
- Point suggestion at Old IN3, south of IN67/Muncie Bypass

**IN3 (Kendallville):** Looks good.

**IN3Bus (Muncie):** Looks good.

**IN4 [LaPorte]:** Looks good.

**IN4 (Goshen):** Looks good.

**IN5:**
- Point possible at Majenica
- Point suggestion at Etna Ave/Old IN9 just south of the river in Huntington
- Unlike others in Indiana, point US24/9 is labeled with both US Highway and IN route instead of just US Highway
- Point suggestion in Ligonier at North Street/N Center Street intersection

**IN7:** Point suggestion in Scipio

**IN8 [Knox]:** Point IN39 is just off center to the west

**IN8 (Auburn):** Point suggestion in Newville.

**IN9:** Point suggestion at Old IN9 on north side of LaGrange

**IN9Trk (Shelbyville):** Looks good.

**IN10:** Looks good.

**IN11 [Elizabeth]:** Looks good.

**IN11 (Seymour):** Point suggestion at CR200N exchange a few miles south of Seymour and at Jackson Street in Jonesville

**IN13:**
- Point suggestion in Urbana
- Point Bri should be BriDr (Briarwood Drive)
- Point suggestion at CR46 exchange south of Millersburg

**IN14:** Point suggestion at Old IN14 just east of Winamac

**IN15:** Looks good.

**IN15Trk (Wabash):** Looks good.

**IN16:**
- Point IN39_N is off center
- Was point 800N_W intended to be named 800N/1100W or just 800N?
- Point suggestion in Lucerne (1.5 miles west of IN17)
- Point suggestion at Stockdale mill (one mile west of Roann) with road exchange

**IN17:** Point suggestion at Olson Road (2 miles south of IN110) and in Burr Oak, north of Culver

**IN18:**
- Point suggestion on northwest side of Fowler at Main Street
- Point 840E should be 850E
- Point US421_N is substantially off-center (probably because they removed the turn a while back); this effects US421 and IN39 [Delphi], too
- Point suggestion at Howard Street in Delphi, along west bank of the Wabash River (also on IN39 and US421)
- Point suggestion in downtown Marion at Washington, which has been lots of different highways over the years

**IN19:**
- Point suggestion in Etna Green either at Old Lincoln Highway (Old US30) or a bit south and west of there, such as Main and Broadway
- Point(s) suggested for the turns north of Etna Green at 575N

**IN22 [Upland]:** Looks good.

**IN22 (Burlington):** Looks good.

**IN23:** Looks good.

**IN25 [Logansport]:**
- Point suggestions for towns of Buck Creek and Colburn
- Point suggestion in Delphi at Main Street (most of which was old IN25)
- Point suggestion at Clymers

**IN25 (Westpoint):** Looks good.

**IN26 [Kokomo]:**
- Point suggestion at Main Street in Fairmount, since it is more than one mile east of IN9
- Point 900E should be labeled 800E

**IN26 (West Lafayette):** Looks good.

**IN28:** Point ElmSt in Ridgeville is a bit too far off the intersection; suggestion that this point be moved east a couple blocks to the intersection of 2nd and Main, which seems to me to be a much more desired spot based on location/route direction

**IN29:** Looks good.

**IN32:**
- Should 1150N_W be just 1150N, as elsewhere?
- Points 500W (Denhart Road) and KinRd seem to be off the intersections
- As on IN47, the points US136/231 and US231 are redundant, only feet apart, covering the same intersection
- Suggestion to move point FulRd one block west to Main Street, a more important intersection

**IN37 [Bloomington]:**
- Point suggestion at Main Street in Oolitic (covers city and Old IN37/58)
- Point I-69 is not well centered and OSM doesn't quite have the smoothing down on the curving highway
- Point suggestion at Tapp Road in Bloomington (current signaled intersection with interchange opening soon)

**IN37 (Harlan):** Looks good.

**IN38 [Noblesville]:**
- Point CR835N should be 835N to be consistent within file and among other routes
- Should point 750N_W just be 750N?
- The routing in Sheridan hasn't been corrected yet: from the west, it travels east on 2nd Street to Main, then south on Main street to 6th, then east on 6th to White, then southeast on White
- Point suggestion in Markleville, just over one mile east of IN109
- Point suggestion at Washington Street in Hagerstown
- Point CenRd is a bit off the intersection

**IN38 (Lafayette):**
- Point 475E should be renamed for Veterans Memorial Parkway (numerical county name no longer applies with annexation and new signs at that intersection list the parkway)
- Point WyaDr should be renamed, since Wyandotte Drive doesn't connect here. Jefferson Road might be best since I believe it was a state highway back in the day. I could be wrong on that, though.

**IN39 [Delphi]:**
- Point suggestion at intersection of Morton and 39 Bypass (as it is called locally) in Martinsville, since it is Old IN37/39 and a pretty important intersection in town
- Point suggestion at Howard Street in Delphi, along west bank of the Wabash River (also on IN18 and US421)
- Point IN18_W is substantially off-center (see IN18 mention, also on IN18 and US421)
- Point suggested at 175N, north of Monticello, for resort area
- Point IN16_W is off center
- Point IN8 is a touch off center to the west

**IN39 (Little York):**
- Point suggestions at Washington Street in Little York and Scifers Road northwest of the town
- Shaping points possible between 550S and IN250

**IN42:** Point possible at Monroe Street on west side of Mooresville

**IN43 [Brookstown]:** Looks good.

**IN43 (Solsberry):** Looks good.

**IN44 [Shelbyville]:**
- Point suggestion at Cross Street in Manila
- Point 150S is a little off the intersection
- Point 850W is actually Main Street in Glenwood
- The points in Liberty look a little wonky on my viewer, but I can't quite figure out if it is the map underlays, or if the points could just use a little refinement. I figured I'd mention it just in case.

**IN44 (Martinsville):** Point 100W is quite off center

**IN44Trk (Rushville):** Looks good.

**IN45:**
- Point IN445 might warrant a little fine-tuning, but it's not far off
- Point suggestion at Walnut St in Bloomington (Old IN37 and major IU/B-town access point)
- Point CreRd is for Lower Bear Creek Road
- Point suggestion at Railroad Road, west of IN135

**IN46:**
- Point MatDr might need to be re-centered with Temperance and Main forming a one-way pair in Ellettsville
- Point suggestion at Walnut St in Bloomington (Old IN37 and a major B-town/IU sporting events access point)
- Points CroCreRd and UppSchRd are a bit off center
- Unless it changed in the last couple of months, the point HawCreRd is still signed as Central Avenue
- Point suggestion at Marr Road on southeast side of Columbus
- Point 200_S should be 200S
- Point suggestion at Clifty Street in hamlet of Newbern

**IN47:**
- As on IN32, the points US136/231 and US231 are redundant, only feet apart, covering the same intersection
- Point IN75 is a little off center

**IN48 [Manchester]:** Point SpaRd is a little off center

**IN48 (Bloomington):** Looks good.

**IN48 (Jasonville):** Looks good.

**IN49:**
- Interchange missing at Vale Park Road in Valparaiso
- Point 500N should be for BurBeaRd
- Point suggestion at Porter Avenue in Chesterton

**IN51:** The route in Hobart uses Lincoln St. between 10th and Main, not Linda St. I'm not sure where OSM got its routing from. I've confirmed it with state files, GMSV, and other maps.

**IN53:** Point I-80 should probably be I-80/94 to include both interstates

**IN54:**
- Point IN59_N is at an intersection north of the actual junction, because IN54 cuts the angle in its 90-degree turn. Not sure how you would want to handle it, as I could easily see leaving it alone to include access via 300N to IN59 (see IN59). Yet, the actual junction is what is plotted elsewhere in the system set and not the hypothetical vertex is. I hadn't seen any other shaped like this.
- Point AStNW_W should be PriRd (Price Road); (see also IN59)
- Points RayRd and ReuLn are a touch off the highway (see also IN58)

**IN55:**
- Point IN341 is half a long-block north of the intersection
- Should point 430E_S be just 430E as elsewhere?
- Points IN352_W and DivRd_W probably could have their positions tweaked
- It's probably not urgent, but the road might warrant a point at Front Street (1200N) in Thayer and another in Shelby to shape the highway a bit

**IN56:**
- Point suggestion at Green Street in Ireland
- Point suggestion at Baden Ave in West Baden Springs (big resort area)
- Point QuaRd should be Old56 (actual name of road on both sides of the highway is "Old 56")
- Point BaseCampRd should be BeeCampRd (Bee Camp Road) and is off the intersection to the west
- Point suggestion at Lake Geneva Road in the hamlet of Center Square

**IN57:**
- Point BooHarRd should be BooNewHarRd (Booneville-New Harmony Road)
- Point suggestion at Walnut/Van Trees pairing for downtown Washington

**IN58:**
- Point 1050 should be either 1050N or FreRd (Freelandville Road)
- Point ReuLn is a touch off the highway (see also IN54)
- Point suggestion at Lincoln Avenue in Bedford (old IN37/58 and downtown)
- Point BaiRd is a full block north of the intersection; it should also be BaiScaRd
- Shouldn't PowRd/MapRd just be PowRd as elsewhere?
- Point suggestion at Diamond Road in Heltonville for shaping, turning, and hamlet coverage
- Point suggestion at Cleveland Street in town of Kurtz
- Point suggestions in Freetown to cover bizarre routing through the community and provide shaping: point at 1st and Union or 1st and Maple to cover multiple turns in that part of the community and a point at Columbus Pike and Maple for the direct cut-off to IN135

**IN59:**
- Point AStNW_W should be PriRd (Price Road); (see also IN54)
- Point IN54_W is at an intersection north of the actual junction, because IN54 cuts the angle in its 90-degree turn (commentary included under IN54)
- Shouldn't 1450S/400W just have one road mentioned and 100W_S be just 100W?
- Point 137 should be AshRd (Ashboro Road)
- Point suggestion at 1500N near Carbon

**IN60:** Looks good.

**IN61:** Looks good.

**IN62:**
- Point suggestion on east side of Evansville at Green River Road
- Suggestion to move point 25W east just a touch to Main Street, where the route actually turns and was formerly US231
- Point OldForRd is about 2-3 block lengths north of the actual intersection, which OSM incorrectly places
- Point suggestion at Main Street in New Washington
- Point 325E is way too far east of the intersection (see also IN250 [Pleasant])

**IN63 [Harrison]:**
- I suggest renaming the reference community for this route, as Harrison is just a placename for a spot along the Wabash River well east of the road and not an actual community. The route enters Terre Haute, which is by far the largest city, and the second largest municipality along the route is Fairview Park.
- Point PineAve should be 39thAve
- Point suggestion at Washington Street in Fairview Park

**IN63 (Fairbanks):** Looks good.

**IN64:** Point 965 should be 965W

**IN65:** Looks good.

**IN66:**
- Point 5thSt_S should be 5thSt
- Shaping point possible at Old Lamar Highway east of IN70_W
- Point suggestion for turn/shaping at Deer Creek Road, east of IN166
- Point GarRidRd should be GerRidRd (German Ridge)
- Point LeoRd is a little off center
- Point OasRd misses intersection by a little bit

**IN67:**
- Point suggestion at Shipping Street in Edwardsport
- Point suggestion at either Mulberry or Elm in Marco
- Point suggestion at Border Street in Paragon
- Point suggestion at Walnut Street in Daleville

**IN67Bus (Muncie):** Looks good.

**IN68:** Looks good.

**IN69:** Looks good.

**IN70 [Newtonville]:** Looks good.

**IN70 (Derby):** Looks good.

**IN71 [Dana]:** Point suggestions at Jonestown Road in St. Bernice and somewhere in Dana

**IN71 (Dunnington):** Looks good.

**IN75 [Jamestown]:** Points suggested for shaping/turning at 500N, south of North Salem, and the point IN47 is a little off center

**IN75 (Flora):** Point suggested at 485S to cover Cutler and break up long gap

**IN101 [Woodburn]:**
- Point SouSt_ has the extra underscore in its name
- Point suggestion at Dawkins Road (north of US30) for old IN14 and nearby connection to OH613.

**IN101 (Brookville):** Looks good.

**IN101 (Markland Dam):** Looks good.

**IN101 (Milan):** Point suggestion at either Ellis St. or Carr St. in Milan

**IN103:** Points suggested at 300S (south of New Castle) and the intersection of 14th Street and 18th Street for better shaping and to cover turn in the city; the same could probably be done at the 14th Street and 16th Street intersection on the north side of the city

**IN104:** Looks good.

**IN105:** Looks good.

**IN106:** Looks good.

**IN109 [Anderson]:** Point suggested at E Street in Wilkinson

**IN109 (Columbia City):** Looks good.

**IN110 [Walnut]:** Looks good.

**IN110 (De Motte):** Looks good.

**IN111:**
- Points HedHillRd, StoHillRd, and IN211 are off the intersections
- Point StuRd probably could be tweaked while the file is being edited
- A shaping/turn point might be useful just south of I-64 at the Main Street intersections with the 4th/5th pairing

**IN114 [Rensselaer]:** Looks good.

**IN114 (Fulton):** Looks good.

**IN114 (North Manchester):** Looks good.

**IN115:** Looks good.

**IN116:** Should 550W/1050S just be 550W?

**IN117:** Looks good.

**IN119 [Winamac]:** Should BasRd_S be just BasRd as done elsewhere?

**IN119 (Goshen):** Looks good.

**IN120:** Points 525W and 1100W probably should be tweaked.

**IN121 [Connersville]:** I suspect the route probably qualifies for or could benefit from some shaping.

**IN121 (Richmond):** Looks good.

**IN124:** Looks good.

**IN127:** Looks good.

**IN128:** Looks good.

**IN129:** Points RobRd and CaveHillRd are off the intersection (see also US50 for CaveHillRd)

**IN130:** Looks good. I'm still hoping to get up there in October or so to check out if it is still signed east of IN149, since the decommissioning was a while ago now. GMSV is outdated on this now.

**IN134:** Looks good.

**IN135:**
- Point DutCreRd is a couple block-lengths off the intersection, and OSM does not have the correct routing here.
- Point RaySt is quite a ways south of Raymond Street. Was the point intended for 100W? That seems to be a better location.

**IN140:** Looks good.

**IN142:** Looks good.

**IN143:** Looks good.

**IN144 [Mooresville]:** Looks good.

**IN144 (Franklin):** Looks good.

**IN145:**
- Point CarCouRd should just be CarRd (Carlisle Road)
- Point OhioSt should be moved northward to Michigan Street or College Ave, since Ohio Street does not connect to IN145.

**IN148:** Looks good.

**IN149:** Looks good.

**IN152:** Looks good.

**IN154:** Looks good.

**IN156:** Looks good.

**IN157:** This route might be a candidate for some shaping on the north end of Worthington toward IN48, and point 200E/800S probably should be labeled just 200E.

**IN158:** Looks good.

**IN159 [Riley]:** Looks good.

**IN159 (Bicknell):** Looks good.

**IN159 (Dugger):** Looks good.

**IN160:** Looks good.

**IN161:**
- Point suggested in Richland City at Adams Street
- Point suggested in Tennyson at Oak Street
- Point IN68_W could be tweaked if time
- Point suggested in Holland

**IN162:** Looks good.

**IN163:**
- Point suggested in Centenary at 6th Street
- Suggest removing point at 6th Street in Clinton and putting points at 9th and Main instead

**IN164:** Looks good.

**IN165:** Looks good.

**IN166:** Looks good.

**IN167:** Looks good.

**IN168:** Looks good.

**IN201:** Looks good.

**IN203:** Looks good.

**IN205:** Should LineSt_N be LineSt?

**IN211:** Point IN111 is off the intersection

**IN212:** Looks good.

**IN213:** Point suggested in Windfall

**IN218 [Warren]:** Looks good.

**IN218 (Deer Creek):** Point suggestion in Bunker Hill

**IN225:** Looks good.

**IN227:** Looks good.

**IN229:** Point possible on southern end of Batesville with the turning in town.

**IN232:** Looks good.

**IN234 [Ladoga]:** Looks good.

**IN234 (Kennard):** Should points MadSt_E and KenRd_N be without the _x?

**IN235:** Suggestion to move point RilSt, which is off the intersection, either north a block to Main Street or south to Washington Street

**IN236 [Roachdale]:**
- Point suggestion in Marshall
- Point IndSt probably could be re-centered a bit
- From what I can see, point PutCouLineRd is signed as 900E; addresses are listed as that too.

**IN236 (Middletown):** Should the reference city here be listed as Anderson, since it is within the city limits for a mile?

**IN237 [Cannelton]:** Looks good.

**IN237 (English):** Looks good.

**IN240:** Point IndRd_W should be just IndRd

**IN241:** Looks good.

**IN243:** Looks good.

**IN244:** Looks good.

**IN245:** Point suggested at St. Peters Church Road or 1450N on south side of Santa Claus

**IN246:** Looks good.

**IN249:** Looks good.

**IN250 [Pleasant]:**
- Point 325E is way too far east of the intersection (see also IN62)
- Point suggested at sharp turn/Bennington Road, east of IN129

**IN250 (Brownstown):** Point 365W should be 385W and could be re-centered a touch

**IN252 [Edinburgh]:** The road has officially been truncated back from IN9 to 250W. I'll try to get down there soon to see if the signs are taken down, but the official communications said they were supposed to be when the road works finished.

**IN252 (Brookville):** Looks good.

**IN256:** Looks good.

**IN257:** Shouldn't point OldIN64_W drop the _W?

**IN258:** Looks good.

**IN261:** Looks good.

**IN262:** Looks good.

**IN263:** Point suggested at 3rd Street in West Lebanon.

**IN264:** Looks good.

**IN265:** Looks good.

**IN267 [Brownsburg]:** Looks good.

**IN267 (Plainfield):** Looks good.

**IN269:** Looks good.

**IN301:** Point possible for shaping/turns in Vera Cruz.

**IN312:** According to the state, this route has somewhat recently had its western terminus truncated back to White Oak Ave (Hammond city limits), just east of the Toll Road. GMSV is three years old in this area, so it isn't much help to confirm that signs are down.

**IN327:** Points suggested at CR34 intersections north of IN8

**IN331:**
- Point suggested at 18th Road to cover two hamlets opposite the river from each other
- Should point DogRd/2BRd be just one of them?

**IN332:** Looks good.

**IN335 [New Pekin]:** Suggestion to move point TraLn slightly northward to Martinsburg Road, where the route makes the hard eastward turn.

**IN335 (Crandall):** Looks good.

**IN337 [Corydon]:** Suggestion to move shaping point north of QuaRd to Moberly Road and unhide, even if a further shaping/turn point is needed.

**IN337 (Bromer):** Should this reference city be Orleans instead of the unincorporated hamlet of Bromer?

**IN340:** Looks good.

**IN341:**
- Point suggestion in Mellott
- IN55 is half a long-block north of the intersection

**IN350:** Looks good.

**IN352:** I believe point 600S_W should be just 600S

**IN356 [Lexington]:** Looks good.

**IN356 (Petersburg):** Looks good.

**IN357:** Looks good.

**IN358:** Looks good.

**IN362:** Looks good.

**IN364:** Looks good.

**IN427:** Looks good.

**IN441:** Looks good.

**IN445:** Looks good.

**IN446:** Looks good.

**IN450:** Looks good.

**IN458:** Looks good.

**IN462:** Looks good.

**IN520:** Looks good.

**IN524:** Looks good.

**IN545 [Troy]:** Looks good.

**IN545 (Dubois):** Point CuxRd should be CuzRd (Cuzco Road)

**IN550 (Bruceville):** Point 250N should be Kaiser Road

**IN550 (Loogootee):** Looks good.

**IN558:** Looks good.

**IN641:** Looks good.

**IN645:** Looks good.

**IN650:** Looks good.

**IN662:** Looks good.

**IN727:** Looks good.

**IN750:** Points US50 and IN3 are off the intersections. This is a new road, but satellite imagery is available now to help, as well.

**IN827:** Looks good.

**IN912:** Looks good.

**IN912 (WEC):** The naming of the 912 routes are a bit confusing to me. How come the other one is not listed in the HB as "East" with the city of East Chicago or Gary? All other split routes have both cities listed in the HB. As a note, two-thirds of this western route is in the larger city of Hammond. Would changing the city name result in the removal of "west" from the listing? That might make it IN912 (Hammond) for the shorter, western leg and IN912 (East Chicago) for the longer, eastern leg. I ask and propose this to eliminate the clunky "((West) East Chicago)" that appears and make the listing of the eastern leg more uniform by having an identifying city for both parts of a split route. The only change other than HB listing would be the file name for IN912wec, which can easily be hidden as an alternative name for IN912ham or something of the sort. We did that somewhat recently with US54elp, for example.

**IN930:** Looks good.

**IN931 [Kokomo]:** Looks good.

**IN931 (Lakeville):** Should point SJo/Mar be labeled End as all the other roads (examples: IN66, IN134), since it ends mid-highway?

**IN933:** Looks fine.

Whew. That's all!

**Comment by jteresco** [comment]
@si404's changes to usain are in the site update currently in progress.

**Comment by ajfarina** [comment]
Great job on this, @si404. I appreciate all your efforts! I'll close the issue. Cheers!
