### ISSUE TITLE
Datacheck FPs: misc.

### ISSUE THREAD

**Issue by yakra** [TravelMapping/HighwayData#73]
ab.tchmai;AB1A_W;AB93_S;;VISIBLE_DISTANCE;15.85
ab.tchyel;Dec;AB93;;VISIBLE_DISTANCE;12.99
ab.tchyel;PalCen;RgeRd275A;;VISIBLE_DISTANCE;19.17
ar.i030;18;30;;VISIBLE_DISTANCE;12.44
ar.i040;24;35;;VISIBLE_DISTANCE;10.53
ar.i040;183;193;;VISIBLE_DISTANCE;10.90
ar.i040;202;216;;VISIBLE_DISTANCE;13.73
ar.i040;221;233;;VISIBLE_DISTANCE;12.38
ar.i049;34;45;;VISIBLE_DISTANCE;11.27
ar.i055;23;34;;VISIBLE_DISTANCE;10.28
ar.us270;AR51_E;I-30(98);I-30(99);SHARP_ANGLE;154.81
ar.us061;I-55(21);I-55(23);AR77_S;SHARP_ANGLE;144.30
ar.us063;I-40(202);I-40(216);;VISIBLE_DISTANCE;13.73
ar.us063;I-40(221);I-40(233);;VISIBLE_DISTANCE;12.38
ct.ct071;CT150_N;CT150_S;CT70;SHARP_ANGLE;150.36
ct.ct262;WatRd_N;ThoAve;GreRd;SHARP_ANGLE;135.98
ks.i035;4;19;;VISIBLE_DISTANCE;15.61
ks.i035;19;33;;VISIBLE_DISTANCE;13.93
ks.i035;57;71;;VISIBLE_DISTANCE;13.77
ks.i035;76;92;;VISIBLE_DISTANCE;17.34
ks.i035;92;127;;VISIBLE_DISTANCE;34.59
ks.i070;183(KT);197(KT);;VISIBLE_DISTANCE;13.74
ks.i070;212(KT);224(KT);;VISIBLE_DISTANCE;12.52
ks.i335;127;147;;VISIBLE_DISTANCE;20.20
ks.i335;147;177;;VISIBLE_DISTANCE;30.73
me.i095;7;19;;VISIBLE_DISTANCE;12.47
me.i095;53;63;;VISIBLE_DISTANCE;10.66
me.i095;63;75;;VISIBLE_DISTANCE;12.16
me.i095;86;102;;VISIBLE_DISTANCE;15.88
me.i095;138;150;;VISIBLE_DISTANCE;12.11
me.i095;199;217;;VISIBLE_DISTANCE;17.36
me.i095;217;227;;VISIBLE_DISTANCE;10.96
me.i095;227;244;;VISIBLE_DISTANCE;17.26
me.i095;244;259;;VISIBLE_DISTANCE;14.63
me.i095;264;276;;VISIBLE_DISTANCE;11.81
me.i095;276;286;;VISIBLE_DISTANCE;10.03
me.i095;291;302;;VISIBLE_DISTANCE;10.78
me.me104;ME27;WatSt;TowRd;SHARP_ANGLE;136.04
me.me156;McCCorRd;ZioHillRd;KnoCorRd;SHARP_ANGLE;141.85
me.us002;US2AltMac;PondRd_Sil;;VISIBLE_DISTANCE;12.03
me.us002althou;DenRd;HodMilRd;;VISIBLE_DISTANCE;13.53
ne.i080;8;20;;VISIBLE_DISTANCE;12.45
ne.i080;38;48;;VISIBLE_DISTANCE;10.03
ne.i080;107;117;;VISIBLE_DISTANCE;10.03
ne.i080;133;145;;VISIBLE_DISTANCE;11.84
ne.i080;145;158;;VISIBLE_DISTANCE;12.56
ne.i080;164;177;;VISIBLE_DISTANCE;12.82
ne.i080;179;190;;VISIBLE_DISTANCE;11.36
ne.i080;199;211;;VISIBLE_DISTANCE;13.00
ne.i080;211;222;;VISIBLE_DISTANCE;10.88
ne.i080;237;248;;VISIBLE_DISTANCE;11.47
ne.i080;409;420;;VISIBLE_DISTANCE;11.28
ne.ne002;ToaRd_N;McMRd;;VISIBLE_DISTANCE;11.78
ne.ne002;HecRd;FaiRd;;VISIBLE_DISTANCE;10.68
ne.ne029;SDRd;MurRd;;VISIBLE_DISTANCE;14.85
ne.ne071;McMRd;ToaRd_N;;VISIBLE_DISTANCE;11.78
ne.ne097;VieRd;BryDr;;VISIBLE_DISTANCE;12.34
nh.nh003aman;+x00001;US3_ManS;I-293(4);SHARP_ANGLE;179.90
nh.nh031;AbbHillRd;NH101_E;+x0ChaWay;SHARP_ANGLE;136.97
nh.nh112;BigRock;GrePonTrl;HanOve;SHARP_ANGLE;144.05
nl.tchmai;SouBra_E;NL405;;VISIBLE_DISTANCE;22.77
nl.tchmai;NL404_N;NL403;;VISIBLE_DISTANCE;16.91
nl.tchmai;BluePonPP;4;;VISIBLE_DISTANCE;12.96
nl.tchmai;YDF;NL401;;VISIBLE_DISTANCE;16.73
nl.tchmai;NL420;ScabCove;;VISIBLE_DISTANCE;23.29
nl.tchmai;SheRd;IndRivPP;;VISIBLE_DISTANCE;10.57
nl.tchmai;NL380;Gul;;VISIBLE_DISTANCE;12.99
nl.tchmai;NL370;RedCli;;VISIBLE_DISTANCE;14.08
nl.tchmai;IndArm;SalPondRd;;VISIBLE_DISTANCE;11.02
nl.tchmai;BowRd;MagRd;;VISIBLE_DISTANCE;11.41
ns.ns101;3;4;;VISIBLE_DISTANCE;13.83
ns.ns101;21;22;;VISIBLE_DISTANCE;13.42
ns.ns102;0;;;EXIT0;
ns.ns103;*OldNS103;31;;VISIBLE_DISTANCE;11.26
ns.ns104;4;5;;VISIBLE_DISTANCE;12.93
ns.ns104;8;10;;VISIBLE_DISTANCE;15.17
ns.ns104;*OldNS104;29;;VISIBLE_DISTANCE;11.41
ns.ns105;+X12;NewCamRd;NewHarRd;SHARP_ANGLE;153.58
ns.ns203;IndFieRd;EastBraRd;;VISIBLE_DISTANCE;15.21
ns.ns209;NGreRd_N;NS242;;VISIBLE_DISTANCE;19.64
ns.ns217;AcrMeaRd;+X326024;LongIslFry;SHARP_ANGLE;154.72
ns.ns316;IsaHarRd;+X779412;SabRd;SHARP_ANGLE;152.42
ns.ns322;OchSt;NS7_E;NS7_W;SHARP_ANGLE;150.08
ns.ns374;AbrLakeRd;MalFalRd;;VISIBLE_DISTANCE;11.92
ns.ns007;ShoCutLp_W;+X996240;ShoCutLp_E;SHARP_ANGLE;147.23
ns.tchmai;NS104(4);NS104(5);;VISIBLE_DISTANCE;12.93
ns.tchmai;NS104(8);NS104(10);;VISIBLE_DISTANCE;15.17
ns.tchmai;*OldNS104;NS104(29);;VISIBLE_DISTANCE;11.41
ns.tchmai;+X12;NewCamRd;SteRd;SHARP_ANGLE;155.23
pe.pe247;AleDr;PE1_E;PE1_W;SHARP_ANGLE;155.07
vt.i089;4;5;;VISIBLE_DISTANCE;12.27
vt.i089;10;11;;VISIBLE_DISTANCE;14.60
vt.i091;4;5;;VISIBLE_DISTANCE;10.65
vt.i091;16;17;;VISIBLE_DISTANCE;12.96
vt.i091;17;18;;VISIBLE_DISTANCE;10.19
vt.i091;24;25;;VISIBLE_DISTANCE;16.09
vt.us002;VT2B_E;US5Alt_S;US5Alt_N;SHARP_ANGLE;136.30
vt.us002trkstj;US2_W;US5_S;US2_E;SHARP_ANGLE;155.61
vt.us007;VT313;VT11;;VISIBLE_DISTANCE;10.41

**Comment by si404** [comment]
added to HighwayData/datacheckfps.csv

**Comment by yakra** [comment]
Damn you, GitHub!
Their software mangles lines containing asterisks.

* The asterisk at the beginning of this line becomes a bullet point.

I think that these asterisks will italicize the text between them: *OldExit1 *OldExit2 *OldExit3 *OldExit4 *OldExit5
I think [asterisk] OldExit 5 retained its asterisk because there wasn't another complementary one to end the italics.

OldNS103, OldNS104, mumble mumble...

**Comment by yakra** [comment]
So in the OP, my OldNS103 and first OldNS104 FPs got mangled by GitHub, and my second OldNS104 FP appeared correctly.

Si dutifully copy/pasted all 3 into HighwayData/datacheckfps.csv.
The second OldNS104 FP, retaining its asterisk, was successfully flagged as an FP.

When Jim automated grabbing and converting the CHM FPs, the first OldNS104 FP was successfully flagged.
The OldNS103 Visible Distance FP, OTOH, was listed on CHM as 11.25 mi, and on TM as 11.26 mi. So now there are two entries in datacheckfps.csv, which still fail to flag the FP.

A quick comparison of the files on CHM and TM show that all points on this segment have the same coords, so this points to a small difference in math / rounding / fudge factor between the two sites. With one (known) occurrence out of thousands of errors, it looks like this will be pretty rare. I can live with it! :)

As Jim noted on AARoads, "I also will at some point add a list of items in the FP csv list that didn't match any actual error, which might also give some indication of more errors that can be flagged as FPs without much effort". The above demonstrates how that will indeed be useful.

Anyway. I can put in a pull request to clean up the Nova Scotia FP entries. Unless, Jim, you're planning on doing more work on that file soon and that would conflict with the edits you'll be making.
Or, unless -- someone else simply beats me to it. :)
