### ISSUE TITLE
Self-ref datacheck

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#74]
Reported by @yakra in AARoads Forum:

Datacheck doesn't seem to be picking up all of the label references own route error type.

The following OK examples, where the entire label matches the route name, were flagged:
```ok.ok077dced;OK77D;;;LABEL_SELFREF;
ok.ok077smar;OK77S;;;LABEL_SELFREF;
ok.ok077sove;OK77S;;;LABEL_SELFREF;
```

These false positives from the old page at CHM were not:

```
NB NB772 NB772_E label references own route
NB NB772 NB772_W label references own route
NB NB845 NB845_E label references own route
NB NB845 NB845_W label references own route
ND US52 US52/281Byp label references own route
```

**Comment by jteresco** [comment]
I'm not sure of all of the criteria that were used for CHM's "label references own route" so I'm going to leave this for now.  I'm tempted to remove that check altogether for now.

**Comment by yakra** [comment]
I'd say, leave it in. Better to have an imperfect check included than no check at all.
This check has helped us find & fix plenty of true errors in the past.

I'll take a stab at outlining criteria here...
Route Name = Route (as in, Route column in the system CSV) + Banner OR Route + Banner + Abbrev.

* Flag Label = Route Name
 ENG A6183 A6183 label references own route
 UT UT282For UT282 label references own route
A lot of these fitting the latter example will be FPs; we'll just have to live with that.

* Flag Label = Route Name + underscore
 CA CA180 CA180_W label references own route
 OH US50TrkCin US50Trk_W label references own route
 PA PA415EHa PA415_N label references own route

* Flag Label = Route Name + slash
 ND US52 US52/281Byp label references own route

* Here's a tricky one: route number after the slash:
 AZ AZ95 I-10BL/95 label references own route
 DE DE202 I-95/202 label references own route
(Both false positives, as /95 & /202 refer to US routes.)
I guess it stands to follow that, say, NH US202 US4/202_W and NH US202 US4/202_E should be flagged as well.
I'll leave how to best strip out the leading "route type" (I-, A-, A, US, DE, etc.) characters as an exercise for those implementing such an error check. :\

SD SD63 OldSD20/63_N label references own route was flagged as a FP on CHM. Such cases are probably rare enough that it's not worth the bother of coding an exception for labels beginning with "Old", and just crossing off the occasional FP instead.
(Oh wait -- Tim's manual referenced using the "native language word for 'Old' prepended or appended according to the grammar rules" -- hell no, not worth the bother!)

* Don't flag Label = Route Name + whatever text.
On ME ME9, ME9A, ME9B, ME9Spr, ME9Alt, ME9Bus_W, ME9Trk_E, etc. don't get flagged as errors.
It's worth noting that while OK OK77DCed OK77D, UT UT282For UT282, and UT UT282Mou UT282 were flagged as errors, OK OK77D OK77DCed, UT UT282 UT282For, and UT UT282 UT282Mou were not. As it should be; these are bona fide examples of spurs branching off of parent routes.

I think it's also wise to include a Route Name = Route + Banner + Abbrev criterion.
So, on TX US70BusFoo, labels of US70Bus_W, US70BusFoo_E, etc. would all get flagged.
As would OK OK77SOve OK77SOve.

**Comment by jteresco** [comment]
Thanks for that, very helpful.  I'll get some or all of these in when I can.

**Comment by jteresco** [comment]
Other than a handful of additional FPs as described in AARoads, I believe the datacheck for self-ref labels are now where we want them to be.

Will close this issue soon if there is no further discussion.

**Comment by jteresco** [comment]
I think datacheck detection has hit the "good enough" point, so closing this issue.  We can always add in new or refine existing checks later as was done in CHM.
