### ISSUE TITLE
unmatchedfps.log not updated

### ISSUE THREAD

**Issue by michihdeu** [TravelMapping/HighwayData#745]
For any reason, http://tm.teresco.org/logs/unmatchedfps.log was not updated with the latest update.

`Log file created at: 2016-08-12 16:32:38.706853`
`The most recent site update completed at 2016-08-13 23:57:48 US/Eastern.`

The error check is updated though...

**Comment by jteresco** [comment]
The transfer of the logs looks like it was interrupted by a network glitch (lots of nasty thunderstorms around here yesterday, so not surprising).  I'm manually transferred the logs and other files from last night's site update so they should match what's in the DB.

**Comment by michihdeu** [comment]
Thanks, I was confused that an unmatched FPs was still existing. I thought reporting is it worth if something's wrong with the update procedure. If it was caused by a network glitch, I think no further action is required.

**Comment by jteresco** [comment]
I'm glad you reported.  I wouldn't have noticed the error messages from the file transfer otherwise.
