### ISSUE TITLE
 Datacheck FPs: West Virginia

### ISSUE THREAD

**Issue by rickmastfan67** [TravelMapping/HighwayData#76]
Just nailing out some of these FP's for WV.  Keeping each network separate if they need to be added that way to the file.

wv.i077;28;40;;VISIBLE_DISTANCE;10.34
wv.i079;67;79;;VISIBLE_DISTANCE;11.64
wv.i079;79;91;;VISIBLE_DISTANCE;11.62

wv.us033;+X025(US33);+X026(US33);+X027(US33);SHARP_ANGLE;148.02
wv.us052;+X016(US52);+X017(US52);+X018(US52);SHARP_ANGLE;139.20
wv.us052ken;CR52/13;+X009(US52);+X010(US52);SHARP_ANGLE;136.30
wv.us250;+X005(US250);+X006(US250);+X007(US250);SHARP_ANGLE;150.53

wv.wv004;WV16_S;+X934408;+X176837;SHARP_ANGLE;141.78
wv.wv004;RivSt_W;ElkSt_N;+X664318;SHARP_ANGLE;142.18
wv.wv015;CR15/1;TurBoneRd;;VISIBLE_DISTANCE;11.72
wv.wv016;WV4_W;+X934408;+X176837;SHARP_ANGLE;141.78
wv.wv020;CR15/4;+X550571;WV15_E;SHARP_ANGLE;136.08
wv.wv055;+X027(US33);+X026(US33);+X025(US33);SHARP_ANGLE;148.02
wv.wv080;+X018(US52);+X017(US52);+X016(US52);SHARP_ANGLE;139.20
wv.wv085;RolBraRd;+X133932;+X188680;SHARP_ANGLE;150.29

(Please update the lines above as FPs, but leave this ticket open once they are applied so I can deal with the ones below once they have the updated 'angles' from fixes.  Rather deal with all of WV's FPs in one ticket.  Once I fix the ones below, then we can close it.)

=====

The following lines will need to be addressed separately when I get the chance as one of points in each isn't on the road it references correctly and need to be fixed.  Thus, the angle could change and it's not worth the trouble flagging it as a FP only to have it change when I fix the location of a point and the angle changes.

wv.wv020;CR15/18;CR15/4;+X550571;SHARP_ANGLE;140.23
wv.wv020;CR20/1_N;OldRt20;+X908625;SHARP_ANGLE;136.09
wv.wv063;+X015(US219);US219_S;CR41/2;SHARP_ANGLE;141.79
wv.wv093;+X319078;WV42_S;ToUS48_E;SHARP_ANGLE;139.76
wv.wv598;ParRd;US460_W;US460_E;SHARP_ANGLE;161.22

**Comment by jteresco** [comment]
The initial ones are in my local copy of the csv file to be included in an update tonight, and pushed up to the master soon.

**Comment by rickmastfan67** [comment]
Jim, please delete the following 'FP'.  I felt like adding in an extra shaping point to fix it was warranted since it's a short route, thus making it an invalid entry.

wv.wv598;ParRd;US460_W;US460_E;SHARP_ANGLE;161.22

As for the ones above mentioned at the end of the original post (excluding WV-598's one), they now have all of their intersections fixed where they were well off the route. (See #85)  Thus, all the angles should have been changed.  I'll list those fixes in here once the next update runs.  When that happens, you can just replace the new line over the old one since the labels wouldn't have changed (except for WV-93).

So, please don't close this ticket just yet.  I know I also created a sharp angle in WV-49's file when overhauling it, so, that will need to be also marked as a FP once it's shown on the list.

**Comment by jteresco** [comment]
OK, thanks.  Launching update now.

**Comment by rickmastfan67** [comment]
Here we go.  All of these are the last FP's in WV.  Once marked, this can be closed, and WV will be clean of errors.

wv.wv020;CR15/18;CR15/4;+X550571;SHARP_ANGLE;143.53
wv.wv020;CR15/4;+X550571;WV15_E;SHARP_ANGLE;136.82
wv.wv020;CR20/1_N;OldRt20;+X908625;SHARP_ANGLE;135.19
wv.wv049;+X008(WV49);MurBraRd;+X009(WV49);SHARP_ANGLE;165.56
wv.wv063;+X015(US219);US219_S;CR41/2;SHARP_ANGLE;141.30
wv.wv093;+X005(WV93);WV42_S;ToUS48_E;SHARP_ANGLE;140.93

**Comment by jteresco** [comment]
WV is clean!
