### ISSUE TITLE
KS: US 59 point addition in Atchison?

### ISSUE THREAD

**Issue by the-spui-ninja** [TravelMapping/HighwayData#779]
This isn't particularly urgent (so feel free to backed this), but I noticed that US 59 did not have a point at 4th Street in Atchison. As this is the main turnoff for Benedictine College (the main reason anyone comes to Atchison in the first place), I thought it deserved its own point. If not, no big deal.

**Comment by mapcat** [comment]
@yakra: any reason not to add this?

**Comment by yakra** [comment]
It's awful close to existing points. I just as soon leave it in "if someone specifically needs it for their list file" territory, if it means the difference from not being able to claim any mileage for those who crossed from the state line.

**Comment by michihdeu** [comment]
@yakra, can this be closed? There were no objections.
