### ISSUE TITLE
ND: ND 22 Truck (Dickinson)

### ISSUE THREAD

**Issue by the-spui-ninja** [TravelMapping/HighwayData#786]
Crossposting this from the forum so it doesn't get buried:

There is a signed ND 22 Truck in Dickinson, following (from south to north) SW 8th St, State Ave, W Villard St (I 94 Business), 113th Ave SW, and 33rd St SW.

The routing is now in OSM.

http://tm.teresco.org/forum/index.php?topic=331.0

**Comment by the-spui-ninja** [comment]
Fixed. 3535cfa

**Comment by jteresco** [comment]
https://github.com/TravelMapping/HighwayData/commit/3535cfaa6342c25bc82b4c7b475b6db7e2c31011

**Comment by jteresco** [comment]
Forgot the new csv lines for this, now have added, and site update is re-running.
