### ISSUE TITLE
NE 370 could use additional point at Werner Park

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#8]
NE 370 is the access for Werner Park, the AAA minor league baseball stadium for the Omaha Storm Chasers.  As travelers (like me) might find that an endpoint of their travels on NE 370, perhaps one of the nearby points could be moved to one of the stadium's main acces road at 126th St.

**Comment by yakra** [comment]
Added 126thSt to my local file, which otherwise had a lot of overdense points trimmed out when I truncated it.

I'll prioritize Nebraska as I start to dig out from under my update backlog, and make this part of my next pull request.
The Iowa side will still be an issue.

**Comment by jteresco** [comment]
This is in the DB.
