### ISSUE TITLE
NE 370 and IA 370

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#9]
Just drove NE 370 east of US 75 and what we have as IA 370 up to I-29.  The route is completely unsigned in NE (just a few "To I-29") and signed as a county route in Iowa.

**Comment by yakra** [comment]
NE370 truncated in my local file.

I'll prioritize Nebraska as I start to dig out from under my update backlog, and make this part of my next pull request.
The Iowa side will still be an issue.

**Comment by jteresco** [comment]
The Iowa side is in the DB.

**Comment by jteresco** [comment]
And now the Nebraska side is in the DB.
