### ISSUE TITLE
Routes in Iceland split at towns

### ISSUE THREAD

**Issue by Duke87ofST** [TravelMapping/HighwayData#968]
There are several cases in Iceland where the official map from Iceland's DOT (http://vegasja.vegagerdin.is/eng/) will show a route ending on one side of a town and reappearing on the other. Here is one example: http://i.imgur.com/dI93N5v.png

Thus far whenever I encounter a situation like this I have been splitting the route, but I find myself growing less confident that that is actually the best way of handling things. In each case where I have encountered this, there is no signage of the route in the field across its apparent gap, including cases (although S97 is not one) where navigating from one segment of the route to the other requires making one or two turns within the town that are not signed. 

But here's the thing. I know, from my travels in the country, that signage of turns within towns is often spotty, and not once did I ever see a reassurance marker within a town. None of these apparently discontinuous routes have any explicit signage in the field of them beginning or ending where the map shows, but no route in Iceland does. And all this holds just as true of routes which the official map shows continuing through a town (the case most of the time), such that from the perspective of a driver, there is no discernible difference.

Based on this I am starting to think I should combine these routes and consider the continuity to be "implied". Thoughts?

**Comment by michihdeu** [comment]
> Based on this I am starting to think I should combine these routes and consider the continuity to be "implied". Thoughts?

Well, I'm not an old hand, began drafting routes about 6 months ago, but I would also do it this way. Just my 2c because no one else has any comment...

**Comment by si404** [comment]
Go with implied routings through towns.

**Comment by Duke87ofST** [comment]
I've gone with implied routings through towns.
