### ISSUE TITLE
File format and ordering for updates.csv

### ISSUE THREAD

**Issue by jteresco** [TravelMapping/HighwayData#97]
I'd like to reorganize the updates.csv file in two ways: expand the date field to have the 4-digit year, and order the file by country/region.  As part of this, I'd probably switch the order of the first two fields so it could just be sorted alphabetically to get the country then region ordering.  This would allow people to make concurrent updates in different parts of the file and commit/merge operations would be much less likely to trigger edit conflicts.

If and when I make this change, I'll change the csv file and the code that parses it all at once.  Ideally, I'll also have a few minutes to make the updates.php page sortable by any field.

**Comment by michihdeu** [comment]
@jteresco , I think the changes to updates.csv have been done. Only the web issue is open.

If so, I think this issue could be closed and an issue on the web repositry should be submitted.

**Comment by jteresco** [comment]
I don't think the changes described have been made. We're still keeping the file sorted by date.  It has remained low priority.

**Comment by michihdeu** [comment]
Ah, got it. However, I think the default order should be by date on the site because (I think) user usually check the list from the top if there was any modification since their last site visit.

**Comment by jteresco** [comment]
Definitely would default to "by date" on the web display and probably by default show only the last month or something like that, with the option to expand to a larger range of dates or sort/filter by other criteria.  The main motivation here is to allow everyone to make and commit their own updates entries without as much risk of merge conflicts.

**Comment by jteresco** [comment]
Addressed by the commit referenced above.
